// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.

//go:build WITH_EBPF

// Real eBPF observer. Active only when the binary is built with the
// WITH_EBPF tag. Attaches a TC ingress program to configured interfaces and
// reads protocol-detection events from a ring buffer.
//
// Runtime prerequisites and the degradation rule (#493):
//
//   - Linux kernel >= 6.6 (the loader attaches via TCX, the only TC path
//     cilium/ebpf v0.22 ships); BTF optional (the program is CO-RE free,
//     see bpf/bpf_standalone.h)
//   - Privileges: root, or ambient CAP_BPF + CAP_NET_ADMIN
//   - Every failure mode is a degradation: unsupported/failed states silence
//     the observer only. Nothing here may panic or block active probing.
//
// The TC program (bpf/tc_ingress.c) emits an event for each packet whose
// payload starts with a known magic prefix:
//
//   - "SSH-"   → SSH banner (port-agnostic; captures server greeting)
//   - "RTSP/1" → RTSP banner
//   - "HTTP/1" → HTTP response banner
//   - UDP/3702 to/from 239.255.255.250 → ONVIF WS-Discovery (multicast)
//
// Each event is translated into a scannerv2.Evidence with Source
// "passive:ebpf:tc". Because passive observation captures the L2 broadcast
// domain, observed IPs may include hosts we never actively probed; the
// orchestrator/classifier layer handles dedup against active evidence.

package ebpf

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"strings"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"mibee-steward/internal/service/scannerv2"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang tcIngress ../../../../bpf/tc_ingress.c -- -I../../../../bpf

// tcIngressObjects is generated by bpf2go from bpf/tc_ingress.c. It exposes
// the loaded program (objs.TcIngress) and the events ring buffer map
// (objs.Events).

// BuiltWithEBPF reports that this binary contains the eBPF loader. Doctor
// uses it to distinguish "feature turned off" from "feature not compiled in".
func BuiltWithEBPF() bool { return true }

// drainBreaker is the ring-buffer read error threshold at which the drain
// goroutine gives up and degrades the observer instead of spinning (#493).
const drainBreaker = 100

// observerState holds the live TC links, the ring-buffer reader goroutine
// and the lifecycle status. Package-level by historical design: the engine
// constructs exactly one Observer per process.
type observerState struct {
	mu      sync.Mutex
	links   []link.Link
	objects *tcIngressObjects
	reader  *ringbuf.Reader
	stop    chan struct{}
	// recent buffers the most recent evidence per IP so Probe() can return it
	// when the orchestrator polls. This decouples the asynchronous ring-buffer
	// drain from the synchronous Probe() call model.
	recent map[string][]scannerv2.Evidence
	st     Status
}

var state observerState

// startOnce ensures the TC attach + drain goroutine starts a single time.
var startOnce sync.Once
var startErr error

func (o *Observer) Name() string { return "passive:ebpf:tc" }

func (o *Observer) statusSnapshot() Status {
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.st.State == "" {
		if !o.cfg.Enabled {
			return Status{State: StateDisabled, Reason: "scanner.ebpf.enabled is false"}
		}
		return Status{State: StatePending, Reason: "enabled; the observer starts lazily on the first probe"}
	}
	return state.st
}

// Probe returns passive evidence accumulated for ip since the last Probe call
// for that IP. It never returns an error for environmental reasons: an
// observer that could not start simply contributes no evidence.
func (o *Observer) Probe(_ context.Context, ip string, _ scannerv2.ProbeHint) ([]scannerv2.Evidence, error) {
	if !o.cfg.Enabled {
		return nil, nil
	}
	startOnce.Do(func() { startErr = o.start() })
	if startErr != nil {
		// The state (with the reason) was logged at warn level inside start;
		// this is a per-poll quiet no-op.
		return nil, nil
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	ev := state.recent[ip]
	delete(state.recent, ip)
	return ev, nil
}

// start attaches the TC program to the configured interfaces and launches the
// ring-buffer drain goroutine. Environmental failures set a terminal Status
// and are ALSO returned as an error (logged once here, swallowed by Probe):
// the observer degrades, the server keeps running.
func (o *Observer) start() error {
	if !o.cfg.Enabled {
		state.mu.Lock()
		state.st = Status{State: StateDisabled, Reason: "scanner.ebpf.enabled is false"}
		state.mu.Unlock()
		return nil
	}

	// 1. Prerequisites. Hard blockers end here as StateUnsupported, without
	//    touching the kernel at all.
	rep := defaultProbeSource().run()
	ev := evaluatePrereqs(rep)
	st := Status{
		Kernel:      rep.release,
		BTF:         rep.btf,
		CapsMissing: ev.MissingCaps,
		Reason:      "",
	}
	if len(ev.Unsupported) > 0 {
		st.State = StateUnsupported
		st.Reason = strings.Join(ev.Unsupported, "; ")
		logState(st)
		state.mu.Lock()
		state.st = st
		state.mu.Unlock()
		return nil
	}
	for _, w := range ev.Warnings {
		slog.Warn("eBPF observer: " + w)
	}

	// 2. Load. Failures are StateFailed; active probing is unaffected.
	if err := rlimit.RemoveMemlock(); err != nil {
		st.State = StateFailed
		st.Reason = fmt.Sprintf("remove memlock rlimit: %v", err)
		logState(st)
		state.mu.Lock()
		state.st = st
		state.mu.Unlock()
		return fmt.Errorf("ebpf: remove memlock: %w", err)
	}
	objs := &tcIngressObjects{}
	if err := loadTcIngressObjects(objs, nil); err != nil {
		st.State = StateFailed
		st.Reason = fmt.Sprintf("load TC program: %v", err)
		logState(st)
		state.mu.Lock()
		state.st = st
		state.mu.Unlock()
		return fmt.Errorf("ebpf: load program: %w", err)
	}
	state.objects = objs

	// 3. Attach. Per-interface failures are tolerated: attach what works.
	//    Zero attachments is StateFailed; a partial attach is StateDegraded.
	ifaces := o.cfg.Interfaces
	if len(ifaces) == 0 {
		ifaces = allNonLoopbackInterfaces()
	}
	st.InterfacesConfigured = ifaces
	for _, iface := range ifaces {
		// TCX (kernel 6.6+) is the only TC attach path cilium/ebpf v0.22
		// ships. It takes an interface index and needs no clsact qdisc,
		// which also helps minimal OpenWrt installs.
		nic, err := net.InterfaceByName(iface)
		if err != nil {
			slog.Warn("eBPF TC attach skipped, unknown interface", "iface", iface, "error", err)
			continue
		}
		l, err := link.AttachTCX(link.TCXOptions{
			Interface: nic.Index,
			Program:   objs.TcIngress,
			Attach:    ebpf.AttachTCXIngress,
		})
		if err != nil {
			slog.Warn("eBPF TC attach failed for interface", "iface", iface, "error", err)
			continue
		}
		state.links = append(state.links, l)
		st.InterfacesAttached = append(st.InterfacesAttached, iface)
		slog.Info("eBPF TC attached", "iface", iface)
	}
	switch {
	case len(st.InterfacesAttached) == 0:
		st.State = StateFailed
		st.Reason = "no interface could host the TCX program (kernel < 6.6? CAP_NET_ADMIN missing? interface down?)"
		logState(st)
		state.mu.Lock()
		state.st = st
		state.mu.Unlock()
		return fmt.Errorf("ebpf: no interfaces attached")
	case len(st.InterfacesAttached) < len(ifaces):
		st.State = StateDegraded
		st.Reason = fmt.Sprintf("attached %d/%d configured interfaces", len(st.InterfacesAttached), len(ifaces))
	default:
		st.State = StateActive
	}
	logState(st)

	state.recent = make(map[string][]scannerv2.Evidence)
	state.stop = make(chan struct{})
	reader, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		st.State = StateFailed
		st.Reason = fmt.Sprintf("open ring buffer: %v", err)
		logState(st)
		state.mu.Lock()
		state.st = st
		state.mu.Unlock()
		return fmt.Errorf("ebpf: ring buffer: %w", err)
	}
	state.reader = reader
	state.mu.Lock()
	state.st = st
	state.mu.Unlock()
	go o.drain()
	return nil
}

// drain reads ring-buffer events forever, translating each into Evidence and
// buffering it under the source IP. Exits when state.stop closes, the reader
// is closed (Stop), or after drainBreaker consecutive read errors — in that
// last case the observer degrades instead of burning a core on a hot error
// loop (#493).
func (o *Observer) drain() {
	consec := 0
	for {
		select {
		case <-state.stop:
			return
		default:
		}
		rec, err := state.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			consec++
			if consec == 1 || consec == drainBreaker {
				slog.Warn("eBPF ring buffer read error", "error", err, "consecutive", consec)
			}
			if consec >= drainBreaker {
				o.degradeDrain(err)
				return
			}
			time.Sleep(10 * time.Millisecond) // yield so a persistent error cannot busy-loop
			continue
		}
		consec = 0
		if len(rec.RawSample) < eventLen {
			continue
		}
		ev := decodeEvent(rec.RawSample)
		if ev.IP == "" {
			continue
		}
		state.mu.Lock()
		state.recent[ev.IP] = append(state.recent[ev.IP], ev)
		// Cap per-IP buffer to avoid unbounded growth from chatty hosts.
		if len(state.recent[ev.IP]) > 100 {
			state.recent[ev.IP] = state.recent[ev.IP][len(state.recent[ev.IP])-100:]
		}
		state.mu.Unlock()
	}
}

// degradeDrain marks the observer degraded after the drain breaker tripped.
// Attached TC programs stay in place (they are read-only observers); only
// the userspace reader stops. A restart retries.
func (o *Observer) degradeDrain(cause error) {
	state.mu.Lock()
	st := state.st
	st.State = StateDegraded
	st.Reason = fmt.Sprintf("ring buffer reader stopped after %d consecutive errors: %v (active probing unaffected; restart the server to retry)", drainBreaker, cause)
	state.st = st
	state.mu.Unlock()
	logState(st)
}

// Stop tears down the eBPF observer: closes the ring-buffer reader (which
// unblocks the drain goroutine's Read), signals state.stop, detaches the TC
// programs, and frees the BPF objects. Safe to call twice or when the
// observer never started (state.stop is nil). (#163)
func (o *Observer) Stop() {
	// Closing the reader unblocks an in-flight drain Read() → ErrClosed exit.
	if state.reader != nil {
		_ = state.reader.Close()
	}
	// Signal state.stop so the drain's select also catches it (defense-in-depth
	// for the case where Read already returned ErrClosed).
	state.mu.Lock()
	if state.stop != nil {
		select {
		case <-state.stop:
		default:
			close(state.stop)
		}
	}
	// Detach TC programs + free BPF objects.
	for _, l := range state.links {
		_ = l.Close()
	}
	state.links = nil
	if state.st.State != "" {
		st := state.st
		st.State = StateDisabled
		st.Reason = "observer stopped (graceful shutdown)"
		state.st = st
	}
	state.mu.Unlock()
	if state.objects != nil {
		_ = state.objects.Close()
		state.objects = nil
	}
}

// logState emits one line per lifecycle transition. Degradations log at warn
// (they are operator-actionable), activation at info.
func logState(st Status) {
	switch st.State {
	case StateActive:
		slog.Info("eBPF passive observer active",
			"kernel", st.Kernel, "btf", st.BTF, "interfaces", st.InterfacesAttached)
	case StateDegraded:
		slog.Warn("eBPF passive observer degraded (active probing unaffected)", "reason", st.Reason)
	case StateUnsupported, StateFailed:
		slog.Warn("eBPF passive observer inactive (active probing unaffected)", "state", string(st.State), "reason", st.Reason)
	default:
		slog.Info("eBPF passive observer state", "state", string(st.State), "reason", st.Reason)
	}
}

// allNonLoopbackInterfaces lists up, non-loopback interface names — the
// default attach set when cfg.Interfaces is empty.
func allNonLoopbackInterfaces() []string {
	ifaces, err := net.Interfaces()
	if err != nil {
		slog.Warn("eBPF observer cannot enumerate interfaces", "error", err)
		return nil
	}
	var out []string
	for _, ifc := range ifaces {
		if ifc.Flags&net.FlagLoopback != 0 || ifc.Flags&net.FlagUp == 0 {
			continue
		}
		out = append(out, ifc.Name)
	}
	return out
}
