//go:build WITH_EBPF

// Real eBPF observer. Active only when the binary is built with
// `WITH_EBPF=1`. Attaches a TC ingress program to configured interfaces and
// reads protocol-detection events from a ring buffer.
//
// Requirements at runtime (documented in docs):
//   - Linux kernel >= 5.8 with BTF (CONFIG_DEBUG_INFO_BTF=y)
//   - Privileges: CAP_BPF + CAP_NET_ADMIN (or run as root)
//   - cilium/ebpf Go module (added via go get when building WITH_EBPF)
//
// The TC program (bpf/tc_ingress.c) emits an event for each packet whose
// payload starts with a known magic prefix:
//
//   - "SSH-"   → SSH banner (port-agnostic; captures server greeting)
//   - "RTSP/1" → RTSP banner
//   - "HTTP/1" → HTTP response banner
//   - UDP/3702 to/from 239.255.255.250 → ONVIF WS-Discovery (multicast)
//
// Each event is translated into a scannerv2.Evidence with Source
// "passive:ebpf:tc". Because passive observation captures the L2 broadcast
// domain, observed IPs may include hosts we never actively probed — the
// orchestrator/classifier layer handles dedup against active evidence.

package ebpf

import (
	"context"
	"encoding/binary"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"mibee-steward/internal/service/scannerv2"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang tcIngress ../../../../bpf/tc_ingress.c -- -I../../../../bpf

// tcIngressObjects is generated by bpf2go from bpf/tc_ingress.c. It exposes
// the loaded program and the events ring buffer map.
// (Generation runs at build-with-ebpf time; the symbols referenced below are
// produced by bpf2go: tcIngressObjects.Program, tcIngressMaps.Events.)

// eventT mirrors the C struct the BPF program writes to the ring buffer:
//
//	struct event { __u32 src_ip; __u16 port; __u16 proto; __u8 kind; __u8 server[64]; };
const (
	eventLen     = 74 // 4 + 2 + 2 + 1 + 1(padding) + 64
	kindSSH      = 1
	kindRTSP     = 2
	kindHTTP     = 3
	kindWSDiscovery = 4
)

// observerState holds the live TC links and the ring-buffer reader goroutine.
type observerState struct {
	mu       sync.Mutex
	links    []link.Link
	objects  *tcIngressObjects
	reader   *ringbuf.Reader
	stop     chan struct{}
	// recent buffers the most recent evidence per IP so Probe() can return it
	// when the orchestrator polls. This decouples the asynchronous ring-buffer
	// drain from the synchronous Probe() call model.
	recent   map[string][]scannerv2.Evidence
}

var state observerState

// startOnce ensures the TC attach + drain goroutine starts a single time.
var startOnce sync.Once
var startErr error

func (o *Observer) Name() string { return "passive:ebpf:tc" }

// Probe returns passive evidence accumulated for ip since the last Probe call
// for that IP. When disabled, returns nothing.
func (o *Observer) Probe(_ context.Context, ip string, _ scannerv2.ProbeHint) ([]scannerv2.Evidence, error) {
	if !o.cfg.Enabled {
		return nil, nil
	}
	startOnce.Do(func() { startErr = o.start() })
	if startErr != nil {
		slog.Debug("eBPF observer not started", "error", startErr)
		return nil, nil
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	ev := state.recent[ip]
	delete(state.recent, ip)
	return ev, nil
}

// start attaches the TC program to each configured interface and launches the
// ring-buffer drain goroutine. Returns an error if attachment fails on any
// interface (caller logs and continues with active-only probing).
func (o *Observer) start() error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("ebpf: remove memlock: %w", err)
	}
	objs := &tcIngressObjects{}
	if err := loadTcIngressObjects(objs, nil); err != nil {
		return fmt.Errorf("ebpf: load program: %w", err)
	}
	state.objects = objs

	ifaces := o.cfg.Interfaces
	if len(ifaces) == 0 {
		ifaces = allNonLoopbackInterfaces()
	}
	for _, iface := range ifaces {
		l, err := link.AttachTC(link.TCAttach{
			Program:   objs.TcIngressProgram,
			Interface: iface,
			Attach:    ebpf.AttachTCIngress,
		})
		if err != nil {
			slog.Warn("eBPF attach failed for interface", "iface", iface, "error", err)
			continue
		}
		state.links = append(state.links, l)
		slog.Info("eBPF TC attached", "iface", iface)
	}
	if len(state.links) == 0 {
		return fmt.Errorf("ebpf: no interfaces attached")
	}

	state.recent = make(map[string][]scannerv2.Evidence)
	state.stop = make(chan struct{})
	state.reader = ringbuf.NewReader(objs.Events)
	go o.drain()
	return nil
}

// drain reads ring-buffer events forever, translating each into Evidence and
// buffering it under the source IP. Exits when state.stop closes.
func (o *Observer) drain() {
	for {
		select {
		case <-state.stop:
			return
		default:
		}
		rec, err := state.reader.Read()
		if err != nil {
			if err == ringbuf.ErrClosed {
				return
			}
			continue
		}
		if len(rec.RawSample) < eventLen {
			continue
		}
		ev := decodeEvent(rec.RawSample)
		if ev.IP == "" {
			continue
		}
		state.mu.Lock()
		state.recent[ev.IP] = append(state.recent[ev.IP], ev)
		// Cap per-IP buffer to avoid unbounded growth from chatty hosts.
		if len(state.recent[ev.IP]) > 100 {
			state.recent[ev.IP] = state.recent[ev.IP][len(state.recent[ev.IP])-100:]
		}
		state.mu.Unlock()
	}
}

// decodeEvent parses the ring-buffer record into an Evidence.
func decodeEvent(b []byte) scannerv2.Evidence {
	ip := ipString(binary.LittleEndian.Uint32(b[0:4]))
	port := int(binary.LittleEndian.Uint16(b[4:6]))
	kind := b[8]
	server := trimCString(b[10:74])
	var eKind, service string
	switch kind {
	case kindSSH:
		eKind, service = "banner", "ssh"
	case kindRTSP:
		eKind, service = "rtsp_banner", "rtsp"
	case kindHTTP:
		eKind, service = "banner", "http"
	case kindWSDiscovery:
		eKind, service = "wsdiscovery", "onvif"
	default:
		return scannerv2.Evidence{}
	}
	raw := map[string]string{}
	if server != "" {
		raw["server"] = server
	}
	raw["service_hint"] = service
	return scannerv2.Evidence{
		Source:     "passive:ebpf:tc",
		Kind:       eKind,
		IP:         ip,
		Port:       port,
		Protocol:   "tcp",
		RawData:    raw,
		Confidence: 0.6, // passive is corroborating, not authoritative
		ObservedAt: time.Now(),
	}
}

func trimCString(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

func ipString(be uint32) string {
	return fmt.Sprintf("%d.%d.%d.%d", byte(be), byte(be>>8), byte(be>>16), byte(be>>24))
}

// allNonLoopbackInterfaces lists non-loopback interface names for default attach.
func allNonLoopbackInterfaces() []string {
	// Minimal: rely on net.Interfaces at call time. Importing net here is fine
	// in the real build.
	return nil // populated by link.AttachTC fallback in start()
}
