#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (c) 2026 MiBee Studio. All rights reserved.
#
# This file is part of MiBee Steward, distributed under the GNU Affero General
# Public License v3.0 or later. You may use, modify, and redistribute it under
# those terms; see LICENSE for the full text. A commercial license is available
# for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.

# fetch-oui.sh — download the IEEE assignment registries (MA-L / MA-M / MA-S)
# and write a single merged OUI→vendor file to the configured path (default
# configs/oui.txt).
#
# IEEE publishes THREE overlapping registries, each as a CSV with the columns
# Registry,Assignment,Organization Name,Organization Address:
#   - MA-L (/24, 6 hex):  https://standards-oui.ieee.org/oui/oui.csv
#   - MA-M (/28, 7 hex):  https://standards-oui.ieee.org/oui28/mam.csv
#   - MA-S (/36, 9 hex):  https://standards-oui.ieee.org/oui36/oui36.csv   (formerly IAB)
#
# The Assignment column is uppercase hex with no separators; its LENGTH encodes
# the tier (6 / 7 / 9). MA-S/MA-M sub-blocks are carved out of /24 OUIs (often
# IEEE's own pool OUIs 8C1F64 / 70B3D5), so the loader MUST do longest-prefix
# match — see internal/service/scannerv2/vendor/oui.go (LookupFull) and
# docs/fingerprint-spec.md §8 (IEEE data = factual registry, cited not relicensed).
#
# Output format (one record per line, "<hex-prefix>\t<vendor>"):
#   BCAD28          Hikvision Digital Technology
#   8C1F64B14       Murata Manufacturing Co., Ltd.
#
# The merged file is intentionally NOT vendored into the repo (kept out of the
# single-file binary; the embedded curated table in vendor/oui_curated.txt
# covers common vendors out-of-box). Add the output path to .gitignore if you
# fetch into the repo tree.
#
# Usage:
#   scripts/fetch-oui.sh                    # → configs/oui.txt
#   scripts/fetch-oui.sh /etc/mibee/oui.txt # → custom path
set -euo pipefail

DEST="${1:-configs/oui.txt}"
BASE="https://standards-oui.ieee.org"

# Allow curl or wget, in that order.
if command -v curl >/dev/null 2>&1; then
	fetch() { curl -fsSL "$1"; }
elif command -v wget >/dev/null 2>&1; then
	fetch() { wget -qO- "$1"; }
else
	echo "error: need curl or wget to download the IEEE registries" >&2
	exit 1
fi

# Require python3 for correct CSV parsing — vendor names contain commas and
# quotes (e.g. "DATA ELECTRONIC DEVICES, INC"), so a naive awk/sed split would
# corrupt them.
if ! command -v python3 >/dev/null 2>&1; then
	echo "error: python3 is required to parse the IEEE CSV registries" >&2
	exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

echo "downloading IEEE registries (MA-L / MA-M / MA-S) from $BASE"
fetch "$BASE/oui/oui.csv"        >"$tmpdir/oui.csv"
fetch "$BASE/oui28/mam.csv"      >"$tmpdir/mam.csv"
fetch "$BASE/oui36/oui36.csv"    >"$tmpdir/oui36.csv"

python3 - "$tmpdir" "$DEST" <<'PY'
import csv, os, sys
tmpdir, dest = sys.argv[1], sys.argv[2]
# Merge MA-S (/36, 9 hex) + MA-M (/28, 7 hex) + MA-L (/24, 6 hex) into one
# "<PREFIX>\t<Vendor>" file. The loader's longest-prefix match resolves overlaps
# (a MAC starting 8C1F64B14.. hits the MA-S row, not the parent 8C1F64 MA-L row).
registries = [
    (os.path.join(tmpdir, "oui36.csv"), "MA-S"),
    (os.path.join(tmpdir, "mam.csv"),   "MA-M"),
    (os.path.join(tmpdir, "oui.csv"),   "MA-L"),
]
count = 0
with open(dest, "w", encoding="utf-8") as out:
    out.write("# IEEE OUI vendor mapping — factual registry, cite IEEE.\n")
    out.write("# Generated by scripts/fetch-oui.sh (MA-L + MA-M + MA-S, longest-prefix).\n")
    out.write("# See docs/fingerprint-spec.md §8 (Data vs code distinction).\n")
    for path, tier in registries:
        with open(path, newline="", encoding="utf-8") as f:
            reader = csv.reader(f)
            header = next(reader, None)  # skip the header row
            for row in reader:
                if len(row) < 3:
                    continue
                assignment = row[1].strip().upper()
                org = row[2].strip()
                # Assignment length encodes the tier: 6 (MA-L), 7 (MA-M), 9 (MA-S).
                if len(assignment) not in (6, 7, 9) or not org:
                    continue
                out.write(f"{assignment}\t{org}\n")
                count += 1
print(f"wrote {count} OUI entries ({', '.join(t for _, t in registries)}) to {dest}")
PY

echo "configure with: scanner.oui_path: \"$DEST\" (or MIBEE_SCANNER_OUI_PATH=$DEST)"
