// Generates Go-exact simple case-mapping + fold-orbit tables for the Rust
// port. Output: crates/mibee-fingerprints/src/tables.rs
// Run: go run gen_case_tables.go > ../crates/mibee-fingerprints/src/tables.rs
package main

import (
	"fmt"
	"os"
	"unicode"
)

func main() {
	fmt.Println("// @generated by difftest/gen_case_tables.go — Go unicode simple case")
	fmt.Println("// mappings and fold orbits. Do not edit.")
	fmt.Println("pub static LOWER: &[(u32, u32)] = &[")
	last := rune(-1)
	for c := rune(0); c <= unicode.MaxRune; c++ {
		l := unicode.ToLower(c)
		if l != c && l != unicode.ReplacementChar {
			// Runes 0x80000000.. are invalid; ToLower returns ReplacementChar
			// for surrogates — skip those (not valid chars in Rust anyway).
			if c >= 0xD800 && c <= 0xDFFF {
				continue
			}
			if last != -1 {
				fmt.Print(", ")
			}
			if c%6 == 0 && c != last2(c, last) {
				fmt.Print("\n    ")
			}
			fmt.Printf("(0x%X, 0x%X)", c, l)
			last = c
		}
	}
	fmt.Println("\n];")
	fmt.Println("pub static UPPER: &[(u32, u32)] = &[")
	last = -1
	for c := rune(0); c <= unicode.MaxRune; c++ {
		u := unicode.ToUpper(c)
		if u != c && u != unicode.ReplacementChar {
			if c >= 0xD800 && c <= 0xDFFF {
				continue
			}
			if last != -1 {
				fmt.Print(", ")
			}
			if c%6 == 0 {
				fmt.Print("\n    ")
			}
			fmt.Printf("(0x%X, 0x%X)", c, u)
			last = c
		}
	}
	fmt.Println("\n];")
	// Fold-orbit canonical representative (orbit minimum) for every rune in a
	// multi-member orbit; single-member orbits map to themselves (omitted).
	fmt.Println("pub static FOLD_REP: &[(u32, u32)] = &[")
	n := 0
	for c := rune(0); c <= unicode.MaxRune; c++ {
		if c >= 0xD800 && c <= 0xDFFF {
			continue
		}
		o := unicode.SimpleFold(c)
		if o == c {
			continue
		}
		// canonical rep = min of orbit
		rep := c
		f := c
		for {
			f = unicode.SimpleFold(f)
			if f < rep {
				rep = f
			}
			if f == c {
				break
			}
		}
		if n > 0 {
			fmt.Print(", ")
		}
		if n%6 == 0 {
			fmt.Print("\n    ")
		}
		fmt.Printf("(0x%X, 0x%X)", c, rep)
		n++
	}
	fmt.Println("\n];")
	os.Exit(0)
}

func last2(c rune, last rune) rune { return last }
