// Package main implements the fpimport tool: converts third-party fingerprint
// databases into the MiBee rule format (see docs/fingerprint-spec.md).
//
// Supported sources:
//
//	fpimport recog <recog-xml-dir> <out-yaml>   # Rapid7 Recog (Apache-2.0)
//	fpimport oui   <ieee-oui.txt> <out-oui.txt> # IEEE OUI (factual; validates)
//	fpimport pen   <iana-pen.csv> <out-yaml>    # IANA PEN → OID prefix rules
//
// License posture (see docs/fingerprint-spec.md §8):
//   - Recog is Apache-2.0 → converted rules carry source: recog + attribution.
//   - IEEE OUI / IANA PEN are factual registries → cite the source.
//   - nmap-service-probes is NOT supported (NPSL, not OSI-free).
package main

import (
	"bufio"
	"encoding/csv"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) < 4 {
		usage()
		os.Exit(2)
	}
	cmd, src, dst := os.Args[1], os.Args[2], os.Args[3]
	var err error
	switch cmd {
	case "recog":
		err = importRecog(src, dst)
	case "oui":
		err = importOUI(src, dst)
	case "pen":
		err = importPEN(src, dst)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand %q\n", cmd)
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "fpimport %s: %v\n", cmd, err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `usage: fpimport <subcommand> <input> <output>

subcommands:
  recog <recog-xml-dir> <out.yaml>   Convert Rapid7 Recog XML → MiBee rules (Apache-2.0)
  oui   <ieee-oui.txt> <out.txt>     Validate/normalize IEEE OUI vendor list
  pen   <iana-pen.csv> <out.yaml>    Convert IANA Private Enterprise Numbers → OID rules`)
}

// ── shared output types (subset of the rule format) ──────────────────────

type outRuleFile struct {
	Version int      `yaml:"version"`
	Rules   []any    `yaml:"rules,omitempty"`
	// PEN/OID tables reuse the snmp-data.yaml shape.
	OIDPrefixes []oidPrefixOut `yaml:"oid_prefixes,omitempty"`
}

type oidPrefixOut struct {
	Prefix string `yaml:"prefix"`
	Brand  string `yaml:"brand"`
	Type   string `yaml:"type"`
}

func writeFile(path string, v any) error {
	b, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	// yaml.Marshal produces no leading header; prepend a provenance comment.
	header := fmt.Sprintf("# Generated by fpimport from %s.\n# See docs/fingerprint-spec.md §8 for license/attribution.\n", path)
	return os.WriteFile(path, append([]byte(header), b...), 0o644)
}

// ── recog: Rapid7 Recog XML → MiBee rules ────────────────────────────────
//
// Recog fingerprints live in XML files like <fingerprint pattern="..." flags="REG_DOT_NEWLINE,REG_ICASE">
// with <param pos="0" name="service.vendor" value="..."/> children. We convert
// the regex pattern + the service.* params into MiBee match/emit rules.
//
// Recog is Apache-2.0. Every converted rule carries source: recog so the
// attribution is retained. Rules whose regex references Recog features we can't
// express (e.g. complex backreferences across params) are skipped with a warning.

type recogFingerprint struct {
	XMLName xml.Name      `xml:"fingerprint"`
	Pattern string        `xml:"pattern,attr"`
	Flags   string        `xml:"flags,attr"`
	Params  []recogParam  `xml:"param"`
}

type recogParam struct {
	Pos   int    `xml:"pos,attr"`
	Name  string `xml:"name,attr"`
	Value string `xml:"value,attr"`
}

type recogMatches struct {
	XMLName     xml.Name           `xml:"matches"`
	Fingerprints []recogFingerprint `xml:"fingerprint"`
}

func importRecog(srcDir, outPath string) error {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return fmt.Errorf("read recog dir: %w", err)
	}
	rules := []any{}
	skipped, converted := 0, 0
	for _, ent := range entries {
		if ent.IsDir() || !strings.HasSuffix(ent.Name(), ".xml") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(srcDir, ent.Name()))
		if err != nil {
			return fmt.Errorf("read %s: %w", ent.Name(), err)
		}
		var m recogMatches
		if err := xml.Unmarshal(b, &m); err != nil {
			fmt.Fprintf(os.Stderr, "warn: parse %s: %v (skipped)\n", ent.Name(), err)
			continue
		}
		for _, fp := range m.Fingerprints {
			rule, ok := convertRecogFP(fp, ent.Name())
			if !ok {
				skipped++
				continue
			}
			rules = append(rules, rule)
			converted++
		}
	}
	if err := writeFile(outPath, outRuleFile{Version: 1, Rules: rules}); err != nil {
		return err
	}
	fmt.Printf("recog: converted %d fingerprints, skipped %d → %s\n", converted, skipped, outPath)
	if skipped > 0 {
		fmt.Printf("(skipped fingerprints used unsupported Recog features; see warnings above)\n")
	}
	return nil
}

// convertRecogFP turns one Recog fingerprint into a MiBee rule. Returns ok=false
// if the pattern or params can't be expressed (skipped with a warning upstream).
func convertRecogFP(fp recogFingerprint, source string) (map[string]any, bool) {
	if fp.Pattern == "" {
		return nil, false
	}
	// Compile to validate; Recog patterns are Ruby regex (mostly PCRE-compatible).
	if _, err := regexp.Compile(fp.Pattern); err != nil {
		fmt.Fprintf(os.Stderr, "warn: %s: regex %q invalid: %v (skipped)\n", source, fp.Pattern, err)
		return nil, false
	}
	ci := strings.Contains(strings.ToUpper(fp.Flags), "REG_ICASE")
	// Derive service name + metadata from params.
	service, md := "", map[string]any{}
	for _, p := range fp.Params {
		switch p.Name {
		case "service":
			service = p.Value
		case "service.vendor", "os.vendor", "hardware.vendor":
			md["inferred_brand"] = p.Value
		case "os.product", "service.product", "hardware.product":
			md["product"] = p.Value
		case "service.version", "os.version":
			md["version"] = p.Value
		}
	}
	// Recog fingerprints don't carry a service name directly — the file name
	// (e.g. mysql_banners.xml) implies the protocol. We map common ones; if
	// unknown, we can't emit a meaningful service → skip.
	if service == "" {
		service = serviceFromRecogFile(source)
	}
	if service == "" {
		return nil, false
	}
	rule := map[string]any{
		"id":     "recog-" + sanitize(service) + "-" + hashShort(fp.Pattern),
		"source": "recog",
		"match": map[string]any{
			"kind":  "banner",
			"field": "banner",
			"op":    "regex",
			"value": fp.Pattern,
			"ci":    ci,
		},
		"service":    service,
		"protocol":   "tcp",
		"confidence": 0.85,
	}
	if len(md) > 0 {
		rule["extract"] = map[string]any{"metadata": md}
	}
	return rule, true
}

var recogFileService = map[string]string{
	"mysql": "mysql", "redis": "redis", "postgresql": "postgresql",
	"mongodb": "mongodb", "ssh": "ssh", "ftp": "ftp", "smtp": "smtp",
	"pop3": "pop3", "imap": "imap", "http": "http", "snmp": "snmp",
	"rtsp": "rtsp", "telnet": "telnet", "vnc": "vnc",
}

func serviceFromRecogFile(name string) string {
	base := strings.TrimSuffix(name, ".xml")
	if i := strings.IndexByte(base, '_'); i > 0 {
		base = base[:i]
	}
	return recogFileService[strings.ToLower(base)]
}

func sanitize(s string) string {
	s = strings.ToLower(s)
	r := strings.NewReplacer(" ", "-", "/", "-", ".", "-")
	return r.Replace(s)
}

func hashShort(s string) string {
	// Deterministic short id from the pattern (first 8 hex chars of a simple
	// FNV-ish hash). Good enough for rule-id uniqueness within a service.
	h := uint32(2166136261)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return fmt.Sprintf("%08x", h)
}

// ── oui: IEEE OUI → validated oui.txt ────────────────────────────────────
//
// The vendor/oui.go loader already reads IEEE's raw format directly, so this
// importer is primarily a validator + normalizer (ensures the file parses and
// reports entry count). It writes the normalized "PREFIX\tVendor" form.

func importOUI(srcPath, outPath string) error {
	in, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer out.Close()
	fmt.Fprintln(out, "# IEEE OUI vendor mapping — factual registry, cite IEEE.")
	fmt.Fprintln(out, "# Generated/validated by fpimport oui. See docs/fingerprint-spec.md §8.")
	count := 0
	scanner := newLineScanner(in)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.Contains(line, "(hex)") {
			continue
		}
		// Parse "XX-XX-XX (hex)\tVendor"
		idx := strings.Index(line, ")")
		if idx < 0 {
			continue
		}
		head := line[:idx]
		head = strings.TrimSuffix(head, " (hex")
		prefix := normalizeOUI(head)
		vendor := strings.TrimSpace(line[idx+1:])
		if prefix == "" || vendor == "" {
			continue
		}
		fmt.Fprintf(out, "%s\t%s\n", prefix, vendor)
		count++
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	fmt.Printf("oui: validated %d entries → %s\n", count, outPath)
	return nil
}

func normalizeOUI(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == ':' || r == '-' || r == '.' || r == ' ' {
			continue
		}
		if r >= 'a' && r <= 'f' {
			r -= 'a' - 'A'
		}
		if (r >= '0' && r <= '9') || (r >= 'A' && r <= 'F') {
			b.WriteRune(r)
		}
		if b.Len() == 6 {
			break
		}
	}
	if b.Len() < 6 {
		return ""
	}
	return b.String()
}

// ── pen: IANA Private Enterprise Numbers → OID prefix rules ──────────────
//
// IANA PEN CSV columns: "Registration Date","Registry","Organization","Private Enterprise Number".
// Each PEN N maps to OID prefix 1.3.6.1.4.1.N. We emit oid_prefixes entries
// (brand = Organization, type = "" since PEN alone can't tell device class).

func importPEN(srcPath, outPath string) error {
	in, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer in.Close()
	r := csv.NewReader(in)
	r.FieldsPerRecord = -1 // tolerate variable column counts / header quirks
	header, err := r.Read()
	if err != nil {
		return fmt.Errorf("read header: %w", err)
	}
	orgCol, penCol := -1, -1
	for i, h := range header {
		h = strings.ToLower(strings.TrimSpace(h))
		if strings.Contains(h, "organization") {
			orgCol = i
		}
		if strings.Contains(h, "private enterprise") || h == "pen" {
			penCol = i
		}
	}
	if orgCol < 0 || penCol < 0 {
		return fmt.Errorf("could not locate Organization / PEN columns in header %v", header)
	}
	prefixes := []oidPrefixOut{}
	count := 0
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: pen row: %v (skipped)\n", err)
			continue
		}
		if penCol >= len(rec) || orgCol >= len(rec) {
			continue
		}
		pen := strings.TrimSpace(rec[penCol])
		org := strings.TrimSpace(rec[orgCol])
		if pen == "" || org == "" {
			continue
		}
		// PEN numbers are sometimes quoted/numeric; validate digits.
		if !isDigits(pen) {
			continue
		}
		prefixes = append(prefixes, oidPrefixOut{
			Prefix: "1.3.6.1.4.1." + pen + ".",
			Brand:  org,
			Type:   "",
		})
		count++
	}
	if err := writeFile(outPath, outRuleFile{Version: 1, OIDPrefixes: prefixes}); err != nil {
		return err
	}
	fmt.Printf("pen: converted %d enterprise numbers → %s\n", count, outPath)
	return nil
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// lineScanner wraps bufio.Reader for line-by-line reading (IEEE oui.txt).
type lineScanner struct {
	r     *bufio.Reader
	token string
	err   error
}

func newLineScanner(r io.Reader) *lineScanner {
	return &lineScanner{r: bufio.NewReader(r)}
}

func (s *lineScanner) Scan() bool {
	line, err := s.r.ReadString('\n')
	if err != nil && err != io.EOF {
		s.err = err
		return false
	}
	if err == io.EOF && line == "" {
		return false
	}
	s.token = strings.TrimRight(line, "\r\n")
	return true
}

func (s *lineScanner) Text() string { return s.token }
func (s *lineScanner) Err() error   { return s.err }
