// Package main implements the fpimport tool: converts third-party fingerprint
// databases into the MiBee rule format (see docs/fingerprint-spec.md).
//
// Supported sources:
//
//	fpimport recog <recog-xml-dir> <out-yaml>   # Rapid7 Recog (Apache-2.0)
//	fpimport oui   <ieee-oui.txt> <out-oui.txt> # IEEE OUI (factual; validates)
//	fpimport pen   <iana-pen.csv> <out-yaml>    # IANA PEN → OID prefix rules
//
// License posture (see docs/fingerprint-spec.md §8):
//   - Recog is Apache-2.0 → converted rules carry source: recog + attribution.
//   - IEEE OUI / IANA PEN are factual registries → cite the source.
//   - nmap-service-probes is NOT supported (NPSL, not OSI-free).
package main

import (
	"bufio"
	"encoding/csv"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) < 4 {
		usage()
		os.Exit(2)
	}
	cmd, src, dst := os.Args[1], os.Args[2], os.Args[3]
	var err error
	switch cmd {
	case "recog":
		err = importRecog(src, dst)
	case "oui":
		err = importOUI(src, dst)
	case "pen":
		err = importPEN(src, dst)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand %q\n", cmd)
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "fpimport %s: %v\n", cmd, err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `usage: fpimport <subcommand> <input> <output>

subcommands:
  recog <recog-xml-dir> <out.yaml>   Convert Rapid7 Recog XML → MiBee rules (Apache-2.0)
  oui   <ieee-oui.txt> <out.txt>     Validate/normalize IEEE OUI vendor list
  pen   <iana-pen.csv> <out.yaml>    Convert IANA Private Enterprise Numbers → OID rules`)
}

// ── shared output types (subset of the rule format) ──────────────────────

type outRuleFile struct {
	Version int   `yaml:"version"`
	Rules   []any `yaml:"rules,omitempty"`
	// PEN/OID tables reuse the snmp-data.yaml shape.
	OIDPrefixes []oidPrefixOut `yaml:"oid_prefixes,omitempty"`
}

type oidPrefixOut struct {
	Prefix string `yaml:"prefix"`
	Brand  string `yaml:"brand"`
	Type   string `yaml:"type"`
}

func writeFile(path string, v any) error {
	b, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	// yaml.Marshal produces no leading header; prepend a provenance comment.
	header := fmt.Sprintf("# Generated by fpimport from %s.\n# See docs/fingerprint-spec.md §8 for license/attribution.\n", path)
	return os.WriteFile(path, append([]byte(header), b...), 0o644)
}

// ── recog: Rapid7 Recog XML → MiBee rules ────────────────────────────────
//
// Recog fingerprints live in XML files. The root <fingerprints> element has a
// `matches="..."` attribute naming the target field (ssh.banner, http_header.server,
// ftp.banner, etc.) and a `preference="0.90"` confidence. Each <fingerprint
// pattern="..."> has <param> children carrying vendor/product/version.
//
// We convert the regex + params into MiBee match/emit rules, mapping Recog's
// match target to our Evidence model:
//
//	ssh.banner          → banner field, but Recog matches the part AFTER
//	                      "SSH-x.x-" (software revision). We wrap the pattern
//	                      to match within the full banner (search, not anchor).
//	http_header.server  → server field (HTTP Server header value) — clean match.
//	ftp.banner          → banner field (Recog matches after the "220 " code;
//	                      we search within the full banner).
//	smtp.banner / pop3.banner / imap.banners → banner field (same strip logic).
//	rtsp_header.server  → server field.
//	mysql.banners       → banner field.
//
// Unsupported targets (x509.*, snmp.*, smb.*, mdns.*, ntp.*, sip.*, dns.*)
// are skipped — we don't have those evidence shapes as regex-matchable fields
// in the rule classifier yet. snmp_sysdescr could be added later via keyword_map.
//
// Recog is Apache-2.0. Every converted rule carries source: recog.

type recogFingerprint struct {
	XMLName xml.Name     `xml:"fingerprint"`
	Pattern string       `xml:"pattern,attr"`
	Flags   string       `xml:"flags,attr"`
	Params  []recogParam `xml:"param"`
}

type recogParam struct {
	Pos   int    `xml:"pos,attr"`
	Name  string `xml:"name,attr"`
	Value string `xml:"value,attr"`
}

type recogFingerprints struct {
	XMLName      xml.Name           `xml:"fingerprints"`
	Matches      string             `xml:"matches,attr"`
	Protocol     string             `xml:"protocol,attr"`
	Preference   string             `xml:"preference,attr"`
	Fingerprints []recogFingerprint `xml:"fingerprint"`
}

// recogTarget maps a Recog match target to our evidence model.
// field = the RawData key; serviceHint = the nominal service for the rule id.
// stripPrefix = if non-empty, the rule's match gets a transform that strips
// this prefix from the field value before regex-matching (Recog banner patterns
// expect the part after "SSH-x.x-" / "220 " / etc., but our evidence carries
// the full greeting).
type recogTarget struct {
	supported   bool
	field       string // RawData key to match against
	serviceHint string // nominal service for rule-id naming
	stripKind   string // "ssh" = strip "SSH-x.y-", "respcode" = strip "NNN "
	kind        string // evidence Kind to scope to (e.g. "snmp" — prevents sysDescr patterns matching banners)
}

var recogTargetMap = map[string]recogTarget{
	"ssh.banner":           {true, "banner", "ssh", "ssh", "banner"},
	"http_header.server":   {true, "server", "http", "", "http"},
	"html_title":           {true, "title", "http", "", "http"},
	"ftp.banner":           {true, "banner", "ftp", "respcode", "banner"},
	"smtp.banner":          {true, "banner", "smtp", "respcode", "banner"},
	"pop3.banner":          {true, "banner", "pop3", "respcode", "banner"},
	"imap.banners":         {true, "banner", "imap", "respcode", "banner"},
	"telnet.banner":        {true, "banner", "telnet", "", "banner"},
	"rtsp_header.server":   {true, "server", "rtsp", "", "rtsp_banner"},
	"mysql.banners":        {true, "banner", "mysql", "", "banner"},
	"mysql.error":          {true, "banner", "mysql", "", "banner"},
	"snmp.sys_description": {true, "sys_descr", "snmp", "", "snmp"},
	"snmp.sys_object_id":   {true, "sys_object_id", "snmp", "", "snmp"},
	"smb.native_os":        {true, "os", "smb", "", "smb"},
}

func importRecog(srcDir, outPath string) error {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return fmt.Errorf("read recog dir: %w", err)
	}
	rules := []any{}
	skipped, converted, unsupportedFiles := 0, 0, 0
	for _, ent := range entries {
		if ent.IsDir() || !strings.HasSuffix(ent.Name(), ".xml") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(srcDir, ent.Name()))
		if err != nil {
			return fmt.Errorf("read %s: %w", ent.Name(), err)
		}
		var rf recogFingerprints
		if err := xml.Unmarshal(b, &rf); err != nil {
			fmt.Fprintf(os.Stderr, "warn: parse %s: %v (skipped)\n", ent.Name(), err)
			continue
		}
		matchKey := rf.Matches
		// Fallback: some Recog files (telnet) omit matches= and use protocol=
		// instead. Derive "<protocol>.banner" as the match key.
		if matchKey == "" && rf.Protocol != "" {
			matchKey = rf.Protocol + ".banner"
		}
		tgt, ok := recogTargetMap[matchKey]
		if !ok || !tgt.supported {
			unsupportedFiles++
			continue // silently skip unsupported match targets
		}
		conf := recogPreferenceToConfidence(rf.Preference)
		for _, fp := range rf.Fingerprints {
			rule, ok := convertRecogFP(fp, ent.Name(), tgt, conf)
			if !ok {
				skipped++
				continue
			}
			rules = append(rules, rule)
			converted++
		}
	}
	if err := writeFile(outPath, outRuleFile{Version: 1, Rules: rules}); err != nil {
		return err
	}
	fmt.Printf("recog: converted %d fingerprints, skipped %d, %d unsupported-target files → %s\n",
		converted, skipped, unsupportedFiles, outPath)
	return nil
}

// recogPreferenceToConfidence converts Recog's preference (0.0–1.0 string) to
// our base confidence. Recog default is 0.90; some files (smtp) use 0.20.
func recogPreferenceToConfidence(pref string) float64 {
	if pref == "" {
		return 0.85
	}
	var f float64
	if _, err := fmt.Sscanf(pref, "%f", &f); err != nil || f <= 0 {
		return 0.85
	}
	if f > 1 {
		f = 1
	}
	return f
}

// convertRecogFP turns one Recog fingerprint into a MiBee rule. tgt tells us
// which evidence field to match and the nominal service; conf is the file-level
// preference. Returns ok=false if the pattern is invalid Go regexp.
func convertRecogFP(fp recogFingerprint, _ string, tgt recogTarget, conf float64) (map[string]any, bool) {
	if fp.Pattern == "" {
		return nil, false
	}
	// Validate the pattern compiles as Go regexp (RE2). Recog uses Ruby regex;
	// most patterns are PCRE-compatible but some use backreferences/lookahead
	// that RE2 rejects — those are skipped.
	if _, err := regexp.Compile(fp.Pattern); err != nil {
		return nil, false // silently skip RE2-incompatible patterns
	}
	ci := strings.Contains(strings.ToUpper(fp.Flags), "REG_ICASE")

	// Build metadata extractors from Recog params.
	// pos="0" params are constant values → {const: ...} extractor.
	// pos="N" params reference regex capture group N → {regex_capture: N}
	// extractor (the RuleClassifier re-applies the match regex and extracts group N).
	md := map[string]any{}
	for _, p := range fp.Params {
		var val any
		if p.Pos > 0 {
			val = map[string]any{"regex_capture": p.Pos}
		} else {
			val = map[string]any{"const": p.Value}
		}
		switch p.Name {
		case "service.vendor", "os.vendor", "hardware.vendor":
			md["inferred_brand"] = val
		case "service.product", "os.product", "hardware.product":
			md["product"] = val
		case "service.version", "os.version":
			md["version"] = val
		}
	}

	// The regex pattern with capture groups needs the full-match wrapper so the
	// RuleClassifier's regex extractor can reference groups. We keep the Recog
	// pattern as-is (it's already anchored with ^...$ in most cases); the rule
	// matcher does a regexp.MatchString which handles the anchors.
	match := map[string]any{
		"field": tgt.field,
		"op":    "regex",
		"value": fp.Pattern,
		"ci":    ci,
	}
	// Kind scoping: restrict the rule to evidence of this Kind so sysDescr
	// patterns don't match TCP banners (critical for snmp rules).
	if tgt.kind != "" {
		match["kind"] = tgt.kind
	}
	// Banner-strip transform: Recog's ssh/ftp/smtp patterns expect the part
	// AFTER "SSH-x.y-" or the "NNN " response code. Our evidence carries the
	// full greeting. Emit a transform so the RuleClassifier strips the prefix
	// before applying the regex.
	switch tgt.stripKind {
	case "ssh":
		match["transform"] = "strip_ssh_prefix"
	case "respcode":
		match["transform"] = "strip_resp_code"
	}
	// SNMP is UDP, not TCP.
	proto := "tcp"
	if tgt.kind == "snmp" {
		proto = "udp"
	}
	rule := map[string]any{
		"id":         "recog-" + tgt.serviceHint + "-" + hashShort(fp.Pattern),
		"source":     "recog",
		"match":      match,
		"service":    tgt.serviceHint,
		"protocol":   proto,
		"confidence": conf,
	}
	if len(md) > 0 {
		rule["extract"] = map[string]any{"metadata": md}
	}
	return rule, true
}

func hashShort(s string) string {
	// Deterministic short id from the pattern (first 8 hex chars of a simple
	// FNV-ish hash). Good enough for rule-id uniqueness within a service.
	h := uint32(2166136261)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return fmt.Sprintf("%08x", h)
}

// ── oui: IEEE OUI → validated oui.txt ────────────────────────────────────
//
// The vendor/oui.go loader already reads IEEE's raw format directly, so this
// importer is primarily a validator + normalizer (ensures the file parses and
// reports entry count). It writes the normalized "PREFIX\tVendor" form.

func importOUI(srcPath, outPath string) error {
	in, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer out.Close()
	fmt.Fprintln(out, "# IEEE OUI vendor mapping — factual registry, cite IEEE.")
	fmt.Fprintln(out, "# Generated/validated by fpimport oui. See docs/fingerprint-spec.md §8.")
	count := 0
	scanner := newLineScanner(in)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.Contains(line, "(hex)") {
			continue
		}
		// Parse "XX-XX-XX (hex)\tVendor"
		idx := strings.Index(line, ")")
		if idx < 0 {
			continue
		}
		head := line[:idx]
		head = strings.TrimSuffix(head, " (hex")
		prefix := normalizeOUI(head)
		vendor := strings.TrimSpace(line[idx+1:])
		if prefix == "" || vendor == "" {
			continue
		}
		fmt.Fprintf(out, "%s\t%s\n", prefix, vendor)
		count++
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	fmt.Printf("oui: validated %d entries → %s\n", count, outPath)
	return nil
}

func normalizeOUI(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == ':' || r == '-' || r == '.' || r == ' ' {
			continue
		}
		if r >= 'a' && r <= 'f' {
			r -= 'a' - 'A'
		}
		if (r >= '0' && r <= '9') || (r >= 'A' && r <= 'F') {
			b.WriteRune(r)
		}
		if b.Len() == 6 {
			break
		}
	}
	if b.Len() < 6 {
		return ""
	}
	return b.String()
}

// ── pen: IANA Private Enterprise Numbers → OID prefix rules ──────────────
//
// IANA PEN CSV columns: "Registration Date","Registry","Organization","Private Enterprise Number".
// Each PEN N maps to OID prefix 1.3.6.1.4.1.N. We emit oid_prefixes entries
// (brand = Organization, type = "" since PEN alone can't tell device class).

func importPEN(srcPath, outPath string) error {
	in, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer in.Close()
	r := csv.NewReader(in)
	r.FieldsPerRecord = -1 // tolerate variable column counts / header quirks
	header, err := r.Read()
	if err != nil {
		return fmt.Errorf("read header: %w", err)
	}
	orgCol, penCol := -1, -1
	for i, h := range header {
		h = strings.ToLower(strings.TrimSpace(h))
		if strings.Contains(h, "organization") {
			orgCol = i
		}
		if strings.Contains(h, "private enterprise") || h == "pen" {
			penCol = i
		}
	}
	if orgCol < 0 || penCol < 0 {
		return fmt.Errorf("could not locate Organization / PEN columns in header %v", header)
	}
	prefixes := []oidPrefixOut{}
	count := 0
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: pen row: %v (skipped)\n", err)
			continue
		}
		if penCol >= len(rec) || orgCol >= len(rec) {
			continue
		}
		pen := strings.TrimSpace(rec[penCol])
		org := strings.TrimSpace(rec[orgCol])
		if pen == "" || org == "" {
			continue
		}
		// PEN numbers are sometimes quoted/numeric; validate digits.
		if !isDigits(pen) {
			continue
		}
		prefixes = append(prefixes, oidPrefixOut{
			Prefix: "1.3.6.1.4.1." + pen + ".",
			Brand:  org,
			Type:   "",
		})
		count++
	}
	if err := writeFile(outPath, outRuleFile{Version: 1, OIDPrefixes: prefixes}); err != nil {
		return err
	}
	fmt.Printf("pen: converted %d enterprise numbers → %s\n", count, outPath)
	return nil
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// lineScanner wraps bufio.Reader for line-by-line reading (IEEE oui.txt).
type lineScanner struct {
	r     *bufio.Reader
	token string
	err   error
}

func newLineScanner(r io.Reader) *lineScanner {
	return &lineScanner{r: bufio.NewReader(r)}
}

func (s *lineScanner) Scan() bool {
	line, err := s.r.ReadString('\n')
	if err != nil && err != io.EOF {
		s.err = err
		return false
	}
	if err == io.EOF && line == "" {
		return false
	}
	s.token = strings.TrimRight(line, "\r\n")
	return true
}

func (s *lineScanner) Text() string { return s.token }
func (s *lineScanner) Err() error   { return s.err }
