// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_commands.sql

package db

import (
	"context"
)

const ackAgentCommand = `-- name: AckAgentCommand :exec
UPDATE agent_commands SET status = 'acknowledged', acknowledged_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'pending'
`

// Agent marks a command acknowledged (picking it up for execution).
func (q *Queries) AckAgentCommand(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, ackAgentCommand, id)
	return err
}

const completeAgentCommand = `-- name: CompleteAgentCommand :exec
UPDATE agent_commands SET status = ?, result = ?
WHERE id = ?
`

type CompleteAgentCommandParams struct {
	Status string  `json:"status"`
	Result *string `json:"result"`
	ID     int64   `json:"id"`
}

// Agent reports the result of a completed command.
func (q *Queries) CompleteAgentCommand(ctx context.Context, arg CompleteAgentCommandParams) error {
	_, err := q.db.ExecContext(ctx, completeAgentCommand, arg.Status, arg.Result, arg.ID)
	return err
}

const countAgentCommands = `-- name: CountAgentCommands :one
SELECT COUNT(*) FROM agent_commands
`

func (q *Queries) CountAgentCommands(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentCommands)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentCommand = `-- name: CreateAgentCommand :one

INSERT INTO agent_commands (agent_id, command, payload)
VALUES (?, ?, ?)
RETURNING id, agent_id, command, payload, status, created_at, acknowledged_at, result
`

type CreateAgentCommandParams struct {
	AgentID string `json:"agent_id"`
	Command string `json:"command"`
	Payload string `json:"payload"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// Center enqueues a command for an agent. status=pending until the agent polls.
func (q *Queries) CreateAgentCommand(ctx context.Context, arg CreateAgentCommandParams) (AgentCommand, error) {
	row := q.db.QueryRowContext(ctx, createAgentCommand, arg.AgentID, arg.Command, arg.Payload)
	var i AgentCommand
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Command,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.Result,
	)
	return i, err
}

const deleteAgentCommand = `-- name: DeleteAgentCommand :execrows
DELETE FROM agent_commands WHERE id = ?
`

func (q *Queries) DeleteAgentCommand(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentCommand, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllAgentCommands = `-- name: ListAllAgentCommands :many
SELECT id, agent_id, command, payload, status, created_at, acknowledged_at, result FROM agent_commands
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListAllAgentCommandsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Admin view: all commands across all agents (for the management UI).
func (q *Queries) ListAllAgentCommands(ctx context.Context, arg ListAllAgentCommandsParams) ([]AgentCommand, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgentCommands, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCommand{}
	for rows.Next() {
		var i AgentCommand
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Command,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgentCommands = `-- name: ListPendingAgentCommands :many
SELECT id, agent_id, command, payload, status, created_at, acknowledged_at, result FROM agent_commands
WHERE agent_id = ? AND status = 'pending'
ORDER BY id
LIMIT ?
`

type ListPendingAgentCommandsParams struct {
	AgentID string `json:"agent_id"`
	Limit   int64  `json:"limit"`
}

// Agent polls its pending commands (status=pending), oldest first.
func (q *Queries) ListPendingAgentCommands(ctx context.Context, arg ListPendingAgentCommandsParams) ([]AgentCommand, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAgentCommands, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCommand{}
	for rows.Next() {
		var i AgentCommand
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Command,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
