// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_status.sql

package db

import (
	"context"
	"time"
)

const listAgentStatus = `-- name: ListAgentStatus :many
SELECT agent_id, version, go_version, hostname, uptime_seconds,
    clock_offset_seconds, scans_total, last_report_at
FROM agent_status
ORDER BY last_report_at ASC
`

// All fleet snapshots oldest-report-first (the stalest agent draws the eye).
func (q *Queries) ListAgentStatus(ctx context.Context) ([]AgentStatus, error) {
	rows, err := q.db.QueryContext(ctx, listAgentStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStatus{}
	for rows.Next() {
		var i AgentStatus
		if err := rows.Scan(
			&i.AgentID,
			&i.Version,
			&i.GoVersion,
			&i.Hostname,
			&i.UptimeSeconds,
			&i.ClockOffsetSeconds,
			&i.ScansTotal,
			&i.LastReportAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentStatus = `-- name: UpsertAgentStatus :exec

INSERT INTO agent_status (agent_id, version, go_version, hostname, uptime_seconds,
    clock_offset_seconds, scans_total, last_report_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(agent_id) DO UPDATE SET
    version = excluded.version,
    go_version = excluded.go_version,
    hostname = excluded.hostname,
    uptime_seconds = excluded.uptime_seconds,
    clock_offset_seconds = excluded.clock_offset_seconds,
    scans_total = excluded.scans_total,
    last_report_at = excluded.last_report_at
`

type UpsertAgentStatusParams struct {
	AgentID            string    `json:"agent_id"`
	Version            string    `json:"version"`
	GoVersion          string    `json:"go_version"`
	Hostname           string    `json:"hostname"`
	UptimeSeconds      int64     `json:"uptime_seconds"`
	ClockOffsetSeconds float64   `json:"clock_offset_seconds"`
	ScansTotal         int64     `json:"scans_total"`
	LastReportAt       time.Time `json:"last_report_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. See LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// Refresh the fleet snapshot on every authenticated agent report (#278).
// clock_offset is passed precomputed by the handler (receive_time - scanned_at).
func (q *Queries) UpsertAgentStatus(ctx context.Context, arg UpsertAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentStatus,
		arg.AgentID,
		arg.Version,
		arg.GoVersion,
		arg.Hostname,
		arg.UptimeSeconds,
		arg.ClockOffsetSeconds,
		arg.ScansTotal,
		arg.LastReportAt,
	)
	return err
}
