// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_tokens.sql

package db

import (
	"context"
)

const createAgentToken = `-- name: CreateAgentToken :one

INSERT INTO agent_tokens (agent_id, token_hash, network_id, name)
VALUES (?, ?, ?, ?)
RETURNING id, agent_id, token_hash, network_id, name, created_at, last_used_at, revoked_at
`

type CreateAgentTokenParams struct {
	AgentID   string `json:"agent_id"`
	TokenHash string `json:"token_hash"`
	NetworkID *int64 `json:"network_id"`
	Name      string `json:"name"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, createAgentToken,
		arg.AgentID,
		arg.TokenHash,
		arg.NetworkID,
		arg.Name,
	)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenHash,
		&i.NetworkID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAgentToken = `-- name: DeleteAgentToken :execrows
DELETE FROM agent_tokens WHERE id = ?
`

func (q *Queries) DeleteAgentToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentToken = `-- name: GetAgentToken :one
SELECT id, agent_id, token_hash, network_id, name, created_at, last_used_at, revoked_at
FROM agent_tokens
WHERE id = ?
`

func (q *Queries) GetAgentToken(ctx context.Context, id int64) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentToken, id)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenHash,
		&i.NetworkID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgentTokenByHash = `-- name: GetAgentTokenByHash :one
SELECT id, agent_id, token_hash, network_id, name, created_at, last_used_at, revoked_at
FROM agent_tokens
WHERE token_hash = ?
`

// Look up a token by its hash for auth verification. Returns the row even when
// revoked so the middleware can distinguish "no such token" (401) from
// "revoked" (401 with a clearer message); the revoked_at check is in middleware.
func (q *Queries) GetAgentTokenByHash(ctx context.Context, tokenHash string) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentTokenByHash, tokenHash)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenHash,
		&i.NetworkID,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentTokens = `-- name: ListAgentTokens :many
SELECT id, agent_id, token_hash, network_id, name, created_at, last_used_at, revoked_at
FROM agent_tokens
ORDER BY id
`

func (q *Queries) ListAgentTokens(ctx context.Context) ([]AgentToken, error) {
	rows, err := q.db.QueryContext(ctx, listAgentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentToken{}
	for rows.Next() {
		var i AgentToken
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TokenHash,
			&i.NetworkID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentToken = `-- name: RevokeAgentToken :execrows
UPDATE agent_tokens SET revoked_at = CURRENT_TIMESTAMP WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeAgentToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAgentTokenLastUsed = `-- name: TouchAgentTokenLastUsed :exec
UPDATE agent_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAgentTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAgentTokenLastUsed, id)
	return err
}
