// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_queries.sql

package db

import (
	"context"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE (? = 0 OR user_id = ?)
  AND (? = '' OR action = ?)
  AND (? = '' OR resource_type = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
`

type CountAuditLogsParams struct {
	Column1      interface{} `json:"column_1"`
	UserID       *int64      `json:"user_id"`
	Column3      interface{} `json:"column_3"`
	Action       string      `json:"action"`
	Column5      interface{} `json:"column_5"`
	ResourceType string      `json:"resource_type"`
	Column7      interface{} `json:"column_7"`
	CreatedAt    *time.Time  `json:"created_at"`
	Column9      interface{} `json:"column_9"`
	CreatedAt_2  *time.Time  `json:"created_at_2"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.Action,
		arg.Column5,
		arg.ResourceType,
		arg.Column7,
		arg.CreatedAt,
		arg.Column9,
		arg.CreatedAt_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditLogsOlderThan = `-- name: DeleteAuditLogsOlderThan :execrows
DELETE FROM audit_logs WHERE created_at < ?
`

// Retention sweep: prune audit rows older than the cutoff. Batched deletion is
// done in Go (DELETE rowid IN (SELECT ... LIMIT ?)) to avoid a single giant
// transaction; this plain form is kept for small/fallback use.
func (q *Queries) DeleteAuditLogsOlderThan(ctx context.Context, createdAt *time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditLogsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAuditLogsOlderThanBatched = `-- name: DeleteAuditLogsOlderThanBatched :execrows
DELETE FROM audit_logs
WHERE rowid IN (
    SELECT rowid FROM audit_logs WHERE audit_logs.created_at < ? LIMIT ?
)
`

type DeleteAuditLogsOlderThanBatchedParams struct {
	CreatedAt *time.Time `json:"created_at"`
	Limit     int64      `json:"limit"`
}

// Batched form: deletes up to ? rows (by rowid) older than the cutoff. The
// sweeper loops this until the affected-row count drops below the batch size.
func (q *Queries) DeleteAuditLogsOlderThanBatched(ctx context.Context, arg DeleteAuditLogsOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditLogsOlderThanBatched, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, ip_address, user_agent, details, created_at
FROM audit_logs
WHERE (? = 0 OR user_id = ?)
  AND (? = '' OR action = ?)
  AND (? = '' OR resource_type = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Column1      interface{} `json:"column_1"`
	UserID       *int64      `json:"user_id"`
	Column3      interface{} `json:"column_3"`
	Action       string      `json:"action"`
	Column5      interface{} `json:"column_5"`
	ResourceType string      `json:"resource_type"`
	Column7      interface{} `json:"column_7"`
	CreatedAt    *time.Time  `json:"created_at"`
	Column9      interface{} `json:"column_9"`
	CreatedAt_2  *time.Time  `json:"created_at_2"`
	Limit        int64       `json:"limit"`
	Offset       int64       `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.Action,
		arg.Column5,
		arg.ResourceType,
		arg.Column7,
		arg.CreatedAt,
		arg.Column9,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
