// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: change_log.sql

package db

import (
	"context"
	"time"
)

const countChangeLog = `-- name: CountChangeLog :one
SELECT COUNT(*)
FROM change_log
WHERE (? = 0 OR network_id = ?)
  AND (? = '' OR change_type = ?)
  AND (? = '' OR entity_type = ?)
`

type CountChangeLogParams struct {
	Column1    interface{} `json:"column_1"`
	NetworkID  *int64      `json:"network_id"`
	Column3    interface{} `json:"column_3"`
	ChangeType string      `json:"change_type"`
	Column5    interface{} `json:"column_5"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) CountChangeLog(ctx context.Context, arg CountChangeLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChangeLog,
		arg.Column1,
		arg.NetworkID,
		arg.Column3,
		arg.ChangeType,
		arg.Column5,
		arg.EntityType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChangeLog = `-- name: CreateChangeLog :one
INSERT INTO change_log (agent_id, network_id, change_type, entity_type, entity_id, before_data, after_data, detected_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, network_id, change_type, entity_type, entity_id, before_data, after_data, detected_at
`

type CreateChangeLogParams struct {
	AgentID    *string   `json:"agent_id"`
	NetworkID  *int64    `json:"network_id"`
	ChangeType string    `json:"change_type"`
	EntityType string    `json:"entity_type"`
	EntityID   *int64    `json:"entity_id"`
	BeforeData *string   `json:"before_data"`
	AfterData  *string   `json:"after_data"`
	DetectedAt time.Time `json:"detected_at"`
}

func (q *Queries) CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRowContext(ctx, createChangeLog,
		arg.AgentID,
		arg.NetworkID,
		arg.ChangeType,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeData,
		arg.AfterData,
		arg.DetectedAt,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.NetworkID,
		&i.ChangeType,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeData,
		&i.AfterData,
		&i.DetectedAt,
	)
	return i, err
}

const deleteChangeLogOlderThanBatched = `-- name: DeleteChangeLogOlderThanBatched :execrows
DELETE FROM change_log
WHERE id IN (
    SELECT sub.id FROM change_log AS sub WHERE sub.detected_at < ? LIMIT ?
)
`

type DeleteChangeLogOlderThanBatchedParams struct {
	DetectedAt time.Time `json:"detected_at"`
	Limit      int64     `json:"limit"`
}

// Retention sweep. Deletes rows older than the cutoff in batches to avoid
// holding the write lock on large tables (mirrors the other retention deletes).
func (q *Queries) DeleteChangeLogOlderThanBatched(ctx context.Context, arg DeleteChangeLogOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChangeLogOlderThanBatched, arg.DetectedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listChangeLog = `-- name: ListChangeLog :many
SELECT id, agent_id, network_id, change_type, entity_type, entity_id, before_data, after_data, detected_at
FROM change_log
WHERE (? = 0 OR network_id = ?)
  AND (? = '' OR change_type = ?)
  AND (? = '' OR entity_type = ?)
ORDER BY detected_at DESC
LIMIT ? OFFSET ?
`

type ListChangeLogParams struct {
	Column1    interface{} `json:"column_1"`
	NetworkID  *int64      `json:"network_id"`
	Column3    interface{} `json:"column_3"`
	ChangeType string      `json:"change_type"`
	Column5    interface{} `json:"column_5"`
	EntityType string      `json:"entity_type"`
	Limit      int64       `json:"limit"`
	Offset     int64       `json:"offset"`
}

func (q *Queries) ListChangeLog(ctx context.Context, arg ListChangeLogParams) ([]ChangeLog, error) {
	rows, err := q.db.QueryContext(ctx, listChangeLog,
		arg.Column1,
		arg.NetworkID,
		arg.Column3,
		arg.ChangeType,
		arg.Column5,
		arg.EntityType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.NetworkID,
			&i.ChangeType,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeData,
			&i.AfterData,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
