// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard_configs.sql

package db

import (
	"context"
)

const createDashboardConfig = `-- name: CreateDashboardConfig :one
INSERT INTO dashboard_configs (name, type, data_source, query, refresh_interval, position)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, type, data_source, query, refresh_interval, position, created_at, updated_at
`

type CreateDashboardConfigParams struct {
	Name            string `json:"name"`
	Type            string `json:"type"`
	DataSource      string `json:"data_source"`
	Query           string `json:"query"`
	RefreshInterval int64  `json:"refresh_interval"`
	Position        string `json:"position"`
}

func (q *Queries) CreateDashboardConfig(ctx context.Context, arg CreateDashboardConfigParams) (DashboardConfig, error) {
	row := q.db.QueryRowContext(ctx, createDashboardConfig,
		arg.Name,
		arg.Type,
		arg.DataSource,
		arg.Query,
		arg.RefreshInterval,
		arg.Position,
	)
	var i DashboardConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DataSource,
		&i.Query,
		&i.RefreshInterval,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboardConfig = `-- name: DeleteDashboardConfig :execrows
DELETE FROM dashboard_configs
WHERE id = ?
`

func (q *Queries) DeleteDashboardConfig(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDashboardConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, name, type, data_source, query, refresh_interval, position, created_at, updated_at
FROM dashboard_configs
ORDER BY id
`

func (q *Queries) ListConfigs(ctx context.Context) ([]DashboardConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardConfig{}
	for rows.Next() {
		var i DashboardConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DataSource,
			&i.Query,
			&i.RefreshInterval,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboardConfig = `-- name: UpdateDashboardConfig :one
UPDATE dashboard_configs
SET name = ?, type = ?, data_source = ?, query = ?, refresh_interval = ?, position = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, data_source, query, refresh_interval, position, created_at, updated_at
`

type UpdateDashboardConfigParams struct {
	Name            string `json:"name"`
	Type            string `json:"type"`
	DataSource      string `json:"data_source"`
	Query           string `json:"query"`
	RefreshInterval int64  `json:"refresh_interval"`
	Position        string `json:"position"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateDashboardConfig(ctx context.Context, arg UpdateDashboardConfigParams) (DashboardConfig, error) {
	row := q.db.QueryRowContext(ctx, updateDashboardConfig,
		arg.Name,
		arg.Type,
		arg.DataSource,
		arg.Query,
		arg.RefreshInterval,
		arg.Position,
		arg.ID,
	)
	var i DashboardConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DataSource,
		&i.Query,
		&i.RefreshInterval,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
