// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_documents.sql

package db

import (
	"context"
	"time"
)

const getDeviceDocuments = `-- name: GetDeviceDocuments :many
SELECT d.id, d.title, d.type, d.url, d.file_path, d.file_size, d.mime_type, d.description, d.created_at, d.updated_at
FROM documents d
JOIN device_documents dd ON d.id = dd.document_id
WHERE dd.device_id = ?
`

func (q *Queries) GetDeviceDocuments(ctx context.Context, deviceID int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceDocuments, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Url,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentDevices = `-- name: GetDocumentDevices :many
SELECT dv.id, dv.name, dv.type, dv.brand, dv.model, dv.location, dv.purpose, dv.description, dv.status, dv.ip_address, dv.mac_address, dv.serial_number, dv.purchase_date, dv.warranty_expiry, dv.tags, dv.created_at, dv.updated_at
FROM devices dv
JOIN device_documents dd ON dv.id = dd.device_id
WHERE dd.document_id = ?
`

type GetDocumentDevicesRow struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	Brand          string    `json:"brand"`
	Model          string    `json:"model"`
	Location       string    `json:"location"`
	Purpose        string    `json:"purpose"`
	Description    string    `json:"description"`
	Status         string    `json:"status"`
	IpAddress      string    `json:"ip_address"`
	MacAddress     string    `json:"mac_address"`
	SerialNumber   string    `json:"serial_number"`
	PurchaseDate   string    `json:"purchase_date"`
	WarrantyExpiry string    `json:"warranty_expiry"`
	Tags           string    `json:"tags"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetDocumentDevices(ctx context.Context, documentID int64) ([]GetDocumentDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentDevices, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentDevicesRow{}
	for rows.Next() {
		var i GetDocumentDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Brand,
			&i.Model,
			&i.Location,
			&i.Purpose,
			&i.Description,
			&i.Status,
			&i.IpAddress,
			&i.MacAddress,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.WarrantyExpiry,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkDeviceDocument = `-- name: LinkDeviceDocument :exec

INSERT INTO device_documents (device_id, document_id)
VALUES (?, ?)
`

type LinkDeviceDocumentParams struct {
	DeviceID   int64 `json:"device_id"`
	DocumentID int64 `json:"document_id"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) LinkDeviceDocument(ctx context.Context, arg LinkDeviceDocumentParams) error {
	_, err := q.db.ExecContext(ctx, linkDeviceDocument, arg.DeviceID, arg.DocumentID)
	return err
}

const unlinkDeviceDocument = `-- name: UnlinkDeviceDocument :execrows
DELETE FROM device_documents
WHERE device_id = ? AND document_id = ?
`

type UnlinkDeviceDocumentParams struct {
	DeviceID   int64 `json:"device_id"`
	DocumentID int64 `json:"document_id"`
}

func (q *Queries) UnlinkDeviceDocument(ctx context.Context, arg UnlinkDeviceDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlinkDeviceDocument, arg.DeviceID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
