// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_configs.sql

package db

import (
	"context"
	"time"
)

const countDeviceConfigs = `-- name: CountDeviceConfigs :one
SELECT COUNT(*) FROM device_configs WHERE device_id = ?
`

func (q *Queries) CountDeviceConfigs(ctx context.Context, deviceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceConfigs, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceConfig = `-- name: CreateDeviceConfig :one


INSERT INTO device_configs (device_id, config_hash, config_text, protocol, diff_from_prev)
VALUES (?, ?, ?, ?, ?)
RETURNING id, device_id, config_hash, config_text, protocol, diff_from_prev, fetched_at
`

type CreateDeviceConfigParams struct {
	DeviceID     int64  `json:"device_id"`
	ConfigHash   string `json:"config_hash"`
	ConfigText   string `json:"config_text"`
	Protocol     string `json:"protocol"`
	DiffFromPrev string `json:"diff_from_prev"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. See LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// device_configs queries: the versioned running-config store (#137). The pull
// probe writes a row per fetch; the API/UI reads the version list (without the
// full text) + a single version's full text on demand.
// Insert one fetched config snapshot. diff_from_prev is the unified diff vs the
// prior version (computed by the caller via internal/configdiff); empty for a
// first-ever capture.
func (q *Queries) CreateDeviceConfig(ctx context.Context, arg CreateDeviceConfigParams) (DeviceConfig, error) {
	row := q.db.QueryRowContext(ctx, createDeviceConfig,
		arg.DeviceID,
		arg.ConfigHash,
		arg.ConfigText,
		arg.Protocol,
		arg.DiffFromPrev,
	)
	var i DeviceConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ConfigHash,
		&i.ConfigText,
		&i.Protocol,
		&i.DiffFromPrev,
		&i.FetchedAt,
	)
	return i, err
}

const getDeviceConfig = `-- name: GetDeviceConfig :one
SELECT id, device_id, config_hash, config_text, protocol, diff_from_prev, fetched_at FROM device_configs WHERE id = ?
`

// Full row for one version (the detail / diff view fetches config_text by id).
func (q *Queries) GetDeviceConfig(ctx context.Context, id int64) (DeviceConfig, error) {
	row := q.db.QueryRowContext(ctx, getDeviceConfig, id)
	var i DeviceConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ConfigHash,
		&i.ConfigText,
		&i.Protocol,
		&i.DiffFromPrev,
		&i.FetchedAt,
	)
	return i, err
}

const getLatestDeviceConfig = `-- name: GetLatestDeviceConfig :one
SELECT id, device_id, config_hash, config_text, protocol, diff_from_prev, fetched_at FROM device_configs WHERE device_id = ? ORDER BY id DESC LIMIT 1
`

// The most recent snapshot for a device -- the baseline a new fetch diffs
// against, and the "current config" the device detail shows.
func (q *Queries) GetLatestDeviceConfig(ctx context.Context, deviceID int64) (DeviceConfig, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeviceConfig, deviceID)
	var i DeviceConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ConfigHash,
		&i.ConfigText,
		&i.Protocol,
		&i.DiffFromPrev,
		&i.FetchedAt,
	)
	return i, err
}

const listDeviceConfigs = `-- name: ListDeviceConfigs :many
SELECT id, device_id, config_hash, protocol, diff_from_prev, fetched_at
FROM device_configs
WHERE device_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListDeviceConfigsParams struct {
	DeviceID int64 `json:"device_id"`
	Limit    int64 `json:"limit"`
	Offset   int64 `json:"offset"`
}

type ListDeviceConfigsRow struct {
	ID           int64     `json:"id"`
	DeviceID     int64     `json:"device_id"`
	ConfigHash   string    `json:"config_hash"`
	Protocol     string    `json:"protocol"`
	DiffFromPrev string    `json:"diff_from_prev"`
	FetchedAt    time.Time `json:"fetched_at"`
}

// Version history for the device-detail "Config History" tab. Omits config_text
// (potentially large) -- the list shows metadata; the full text loads by id.
func (q *Queries) ListDeviceConfigs(ctx context.Context, arg ListDeviceConfigsParams) ([]ListDeviceConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceConfigs, arg.DeviceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceConfigsRow{}
	for rows.Next() {
		var i ListDeviceConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ConfigHash,
			&i.Protocol,
			&i.DiffFromPrev,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
