// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_neighbors.sql

package db

import (
	"context"
	"time"
)

const countDeviceNeighbors = `-- name: CountDeviceNeighbors :one
SELECT COUNT(*) FROM device_neighbors
`

func (q *Queries) CountDeviceNeighbors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceNeighbors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeviceNeighborsForDevice = `-- name: DeleteDeviceNeighborsForDevice :execrows
DELETE FROM device_neighbors WHERE device_id = ?
`

func (q *Queries) DeleteDeviceNeighborsForDevice(ctx context.Context, deviceID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceNeighborsForDevice, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllDeviceNeighbors = `-- name: ListAllDeviceNeighbors :many
SELECT id, device_id, neighbor_device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen FROM device_neighbors ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAllDeviceNeighborsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Paginated admin view of all neighbor edges across all devices.
func (q *Queries) ListAllDeviceNeighbors(ctx context.Context, arg ListAllDeviceNeighborsParams) ([]DeviceNeighbor, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeviceNeighbors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceNeighbor{}
	for rows.Next() {
		var i DeviceNeighbor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborDeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceNeighbors = `-- name: ListDeviceNeighbors :many
SELECT id, device_id, neighbor_device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen FROM device_neighbors WHERE device_id = ? ORDER BY protocol, neighbor_mac
`

// All neighbors of a device (the local-end device_id), for the topology view.
func (q *Queries) ListDeviceNeighbors(ctx context.Context, deviceID int64) ([]DeviceNeighbor, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceNeighbors, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceNeighbor{}
	for rows.Next() {
		var i DeviceNeighbor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborDeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceNeighbor = `-- name: UpsertDeviceNeighbor :exec
INSERT INTO device_neighbors (device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(device_id, neighbor_mac, protocol) DO UPDATE SET
    local_port = CASE WHEN excluded.local_port != '' THEN excluded.local_port ELSE device_neighbors.local_port END,
    remote_port = CASE WHEN excluded.remote_port != '' THEN excluded.remote_port ELSE device_neighbors.remote_port END,
    network_id = COALESCE(excluded.network_id, device_neighbors.network_id),
    last_seen = excluded.last_seen
`

type UpsertDeviceNeighborParams struct {
	DeviceID    int64      `json:"device_id"`
	NeighborMac string     `json:"neighbor_mac"`
	Protocol    string     `json:"protocol"`
	LocalPort   *string    `json:"local_port"`
	RemotePort  *string    `json:"remote_port"`
	NetworkID   *int64     `json:"network_id"`
	FirstSeen   *time.Time `json:"first_seen"`
	LastSeen    *time.Time `json:"last_seen"`
}

// Insert or refresh a neighbor edge. ON CONFLICT updates last_seen (and ports
// if they changed) without losing first_seen. The UNIQUE(device_id, neighbor_mac,
// protocol) constraint backs the conflict target.
func (q *Queries) UpsertDeviceNeighbor(ctx context.Context, arg UpsertDeviceNeighborParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceNeighbor,
		arg.DeviceID,
		arg.NeighborMac,
		arg.Protocol,
		arg.LocalPort,
		arg.RemotePort,
		arg.NetworkID,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
