// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_systems.sql

package db

import (
	"context"
	"time"
)

const countDeviceSystemsByDevice = `-- name: CountDeviceSystemsByDevice :one
SELECT COUNT(*) AS count
FROM device_systems
WHERE device_id = ?
`

func (q *Queries) CountDeviceSystemsByDevice(ctx context.Context, deviceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceSystemsByDevice, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceSystem = `-- name: CreateDeviceSystem :one

INSERT INTO device_systems (
    device_id, name, entry_url, description, category,
    metrics_url, metrics_enabled, tags
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, device_id, name, entry_url, description, category, metrics_url, metrics_enabled, tags, created_at, updated_at
`

type CreateDeviceSystemParams struct {
	DeviceID       int64  `json:"device_id"`
	Name           string `json:"name"`
	EntryUrl       string `json:"entry_url"`
	Description    string `json:"description"`
	Category       string `json:"category"`
	MetricsUrl     string `json:"metrics_url"`
	MetricsEnabled int64  `json:"metrics_enabled"`
	Tags           string `json:"tags"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateDeviceSystem(ctx context.Context, arg CreateDeviceSystemParams) (DeviceSystem, error) {
	row := q.db.QueryRowContext(ctx, createDeviceSystem,
		arg.DeviceID,
		arg.Name,
		arg.EntryUrl,
		arg.Description,
		arg.Category,
		arg.MetricsUrl,
		arg.MetricsEnabled,
		arg.Tags,
	)
	var i DeviceSystem
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.EntryUrl,
		&i.Description,
		&i.Category,
		&i.MetricsUrl,
		&i.MetricsEnabled,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceSystem = `-- name: DeleteDeviceSystem :execrows
DELETE FROM device_systems
WHERE id = ?
`

func (q *Queries) DeleteDeviceSystem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceSystem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeviceSystem = `-- name: GetDeviceSystem :one
SELECT id, device_id, name, entry_url, description, category, metrics_url, metrics_enabled, tags, created_at, updated_at
FROM device_systems
WHERE id = ?
`

func (q *Queries) GetDeviceSystem(ctx context.Context, id int64) (DeviceSystem, error) {
	row := q.db.QueryRowContext(ctx, getDeviceSystem, id)
	var i DeviceSystem
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.EntryUrl,
		&i.Description,
		&i.Category,
		&i.MetricsUrl,
		&i.MetricsEnabled,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDeviceSystems = `-- name: ListAllDeviceSystems :many
SELECT id, device_id, name, entry_url, description, category, metrics_url, metrics_enabled, tags, created_at, updated_at
FROM device_systems
WHERE (? = '' OR category = ?)
ORDER BY id
LIMIT ? OFFSET ?
`

type ListAllDeviceSystemsParams struct {
	Column1  interface{} `json:"column_1"`
	Category string      `json:"category"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

func (q *Queries) ListAllDeviceSystems(ctx context.Context, arg ListAllDeviceSystemsParams) ([]DeviceSystem, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeviceSystems,
		arg.Column1,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSystem{}
	for rows.Next() {
		var i DeviceSystem
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.EntryUrl,
			&i.Description,
			&i.Category,
			&i.MetricsUrl,
			&i.MetricsEnabled,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSystemsByDevice = `-- name: ListDeviceSystemsByDevice :many
SELECT id, device_id, name, entry_url, description, category, metrics_url, metrics_enabled, tags, created_at, updated_at
FROM device_systems
WHERE device_id = ?
  AND (? = '' OR category = ?)
ORDER BY id
LIMIT ? OFFSET ?
`

type ListDeviceSystemsByDeviceParams struct {
	DeviceID int64       `json:"device_id"`
	Column2  interface{} `json:"column_2"`
	Category string      `json:"category"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

func (q *Queries) ListDeviceSystemsByDevice(ctx context.Context, arg ListDeviceSystemsByDeviceParams) ([]DeviceSystem, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceSystemsByDevice,
		arg.DeviceID,
		arg.Column2,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceSystem{}
	for rows.Next() {
		var i DeviceSystem
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.EntryUrl,
			&i.Description,
			&i.Category,
			&i.MetricsUrl,
			&i.MetricsEnabled,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSystemsForSD = `-- name: ListDeviceSystemsForSD :many
SELECT ds.id, ds.device_id, ds.name, ds.entry_url, ds.description, ds.category,
       ds.metrics_url, ds.metrics_enabled, ds.tags, ds.created_at, ds.updated_at,
       d.name AS device_name, d.type AS device_type, d.location AS device_location
FROM device_systems ds
JOIN devices d ON ds.device_id = d.id
WHERE ds.metrics_enabled = 1
`

type ListDeviceSystemsForSDRow struct {
	ID             int64     `json:"id"`
	DeviceID       int64     `json:"device_id"`
	Name           string    `json:"name"`
	EntryUrl       string    `json:"entry_url"`
	Description    string    `json:"description"`
	Category       string    `json:"category"`
	MetricsUrl     string    `json:"metrics_url"`
	MetricsEnabled int64     `json:"metrics_enabled"`
	Tags           string    `json:"tags"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	DeviceName     string    `json:"device_name"`
	DeviceType     string    `json:"device_type"`
	DeviceLocation string    `json:"device_location"`
}

func (q *Queries) ListDeviceSystemsForSD(ctx context.Context) ([]ListDeviceSystemsForSDRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceSystemsForSD)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceSystemsForSDRow{}
	for rows.Next() {
		var i ListDeviceSystemsForSDRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.EntryUrl,
			&i.Description,
			&i.Category,
			&i.MetricsUrl,
			&i.MetricsEnabled,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
			&i.DeviceType,
			&i.DeviceLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceSystem = `-- name: UpdateDeviceSystem :one
UPDATE device_systems
SET device_id = ?, name = ?, entry_url = ?, description = ?, category = ?,
    metrics_url = ?, metrics_enabled = ?, tags = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, device_id, name, entry_url, description, category, metrics_url, metrics_enabled, tags, created_at, updated_at
`

type UpdateDeviceSystemParams struct {
	DeviceID       int64  `json:"device_id"`
	Name           string `json:"name"`
	EntryUrl       string `json:"entry_url"`
	Description    string `json:"description"`
	Category       string `json:"category"`
	MetricsUrl     string `json:"metrics_url"`
	MetricsEnabled int64  `json:"metrics_enabled"`
	Tags           string `json:"tags"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateDeviceSystem(ctx context.Context, arg UpdateDeviceSystemParams) (DeviceSystem, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceSystem,
		arg.DeviceID,
		arg.Name,
		arg.EntryUrl,
		arg.Description,
		arg.Category,
		arg.MetricsUrl,
		arg.MetricsEnabled,
		arg.Tags,
		arg.ID,
	)
	var i DeviceSystem
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.EntryUrl,
		&i.Description,
		&i.Category,
		&i.MetricsUrl,
		&i.MetricsEnabled,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
