// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_neighbors.sql

package db

import (
	"context"
	"time"
)

const countDeviceNeighbors = `-- name: CountDeviceNeighbors :one
SELECT COUNT(*) FROM device_neighbors
`

func (q *Queries) CountDeviceNeighbors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceNeighbors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeviceNeighborsForDevice = `-- name: DeleteDeviceNeighborsForDevice :execrows
DELETE FROM device_neighbors WHERE device_id = ?
`

func (q *Queries) DeleteDeviceNeighborsForDevice(ctx context.Context, deviceID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceNeighborsForDevice, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDeviceNeighborsOlderThanBatched = `-- name: DeleteDeviceNeighborsOlderThanBatched :execrows
DELETE FROM device_neighbors
WHERE id IN (
    SELECT sub.id FROM device_neighbors AS sub WHERE sub.last_seen < ? LIMIT ?
)
`

type DeleteDeviceNeighborsOlderThanBatchedParams struct {
	LastSeen *time.Time `json:"last_seen"`
	Limit    int64      `json:"limit"`
}

// Retention sweep (batched) for device_neighbors. Removes edges whose
// last_seen is older than the cutoff, in batches to avoid holding the write
// lock on large tables (mirrors the other retention deletes).
func (q *Queries) DeleteDeviceNeighborsOlderThanBatched(ctx context.Context, arg DeleteDeviceNeighborsOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceNeighborsOlderThanBatched, arg.LastSeen, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllDeviceNeighbors = `-- name: ListAllDeviceNeighbors :many
SELECT id, device_id, neighbor_device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen FROM device_neighbors ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAllDeviceNeighborsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Paginated admin view of all neighbor edges across all devices.
func (q *Queries) ListAllDeviceNeighbors(ctx context.Context, arg ListAllDeviceNeighborsParams) ([]DeviceNeighbor, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeviceNeighbors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceNeighbor{}
	for rows.Next() {
		var i DeviceNeighbor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborDeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceNeighbors = `-- name: ListDeviceNeighbors :many
SELECT id, device_id, neighbor_device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen FROM device_neighbors WHERE device_id = ? ORDER BY protocol, neighbor_mac
`

// All neighbors of a device (the local-end device_id), for the topology view.
func (q *Queries) ListDeviceNeighbors(ctx context.Context, deviceID int64) ([]DeviceNeighbor, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceNeighbors, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceNeighbor{}
	for rows.Next() {
		var i DeviceNeighbor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborDeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceNeighborsWithDevice = `-- name: ListDeviceNeighborsWithDevice :many
SELECT
    device_neighbors.id AS id,
    device_neighbors.device_id AS device_id,
    device_neighbors.neighbor_mac AS neighbor_mac,
    device_neighbors.protocol AS protocol,
    device_neighbors.local_port AS local_port,
    device_neighbors.remote_port AS remote_port,
    device_neighbors.first_seen AS first_seen,
    device_neighbors.last_seen AS last_seen,
    d.id   AS resolved_device_id,
    d.name AS neighbor_name,
    d.ip_address AS neighbor_ip,
    d.type AS neighbor_type,
    d.status AS neighbor_status
FROM device_neighbors
LEFT JOIN devices d ON device_neighbors.neighbor_mac = d.mac_address
WHERE device_neighbors.device_id = ?
ORDER BY device_neighbors.protocol, device_neighbors.neighbor_mac
`

type ListDeviceNeighborsWithDeviceRow struct {
	ID               int64      `json:"id"`
	DeviceID         int64      `json:"device_id"`
	NeighborMac      string     `json:"neighbor_mac"`
	Protocol         string     `json:"protocol"`
	LocalPort        *string    `json:"local_port"`
	RemotePort       *string    `json:"remote_port"`
	FirstSeen        *time.Time `json:"first_seen"`
	LastSeen         *time.Time `json:"last_seen"`
	ResolvedDeviceID *int64     `json:"resolved_device_id"`
	NeighborName     *string    `json:"neighbor_name"`
	NeighborIp       *string    `json:"neighbor_ip"`
	NeighborType     *string    `json:"neighbor_type"`
	NeighborStatus   *string    `json:"neighbor_status"`
}

// Like ListDeviceNeighbors, but LEFT JOINs devices on neighbor_mac so the
// caller can show the neighbor's name/IP/type (not just its MAC) when the
// neighbor has itself been scanned. The neighbor_* fields are NULL when the
// neighbor device is not in the registry yet (unidentified neighbor).
// Columns listed explicitly: sqlc v1.27.0's sqlc.embed() corrupts sibling
// query generation, so it is avoided here.
func (q *Queries) ListDeviceNeighborsWithDevice(ctx context.Context, deviceID int64) ([]ListDeviceNeighborsWithDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceNeighborsWithDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceNeighborsWithDeviceRow{}
	for rows.Next() {
		var i ListDeviceNeighborsWithDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedDeviceID,
			&i.NeighborName,
			&i.NeighborIp,
			&i.NeighborType,
			&i.NeighborStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyEdges = `-- name: ListTopologyEdges :many
SELECT
    dn.id, dn.device_id, dn.neighbor_mac, dn.protocol, dn.local_port, dn.remote_port,
    dn.first_seen, dn.last_seen,
    d.id AS to_device_id
FROM device_neighbors dn
LEFT JOIN devices d ON dn.neighbor_mac = d.mac_address
WHERE (? <= 0 OR dn.network_id = ?)
ORDER BY dn.id
`

type ListTopologyEdgesParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID *int64      `json:"network_id"`
}

type ListTopologyEdgesRow struct {
	ID          int64      `json:"id"`
	DeviceID    int64      `json:"device_id"`
	NeighborMac string     `json:"neighbor_mac"`
	Protocol    string     `json:"protocol"`
	LocalPort   *string    `json:"local_port"`
	RemotePort  *string    `json:"remote_port"`
	FirstSeen   *time.Time `json:"first_seen"`
	LastSeen    *time.Time `json:"last_seen"`
	ToDeviceID  *int64     `json:"to_device_id"`
}

// Every neighbor edge across all devices, JOINed to resolve the neighbor's
// device_id (so the topology graph can draw device-to-device edges as solid and
// device-to-unidentified-MAC edges as dashed). network_id <= 0 means all networks.
func (q *Queries) ListTopologyEdges(ctx context.Context, arg ListTopologyEdgesParams) ([]ListTopologyEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopologyEdges, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopologyEdgesRow{}
	for rows.Next() {
		var i ListTopologyEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NeighborMac,
			&i.Protocol,
			&i.LocalPort,
			&i.RemotePort,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ToDeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceNeighbor = `-- name: UpsertDeviceNeighbor :exec
INSERT INTO device_neighbors (device_id, neighbor_mac, protocol, local_port, remote_port, network_id, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(device_id, neighbor_mac, protocol) DO UPDATE SET
    local_port = CASE WHEN excluded.local_port != '' THEN excluded.local_port ELSE device_neighbors.local_port END,
    remote_port = CASE WHEN excluded.remote_port != '' THEN excluded.remote_port ELSE device_neighbors.remote_port END,
    network_id = COALESCE(excluded.network_id, device_neighbors.network_id),
    last_seen = excluded.last_seen
`

type UpsertDeviceNeighborParams struct {
	DeviceID    int64      `json:"device_id"`
	NeighborMac string     `json:"neighbor_mac"`
	Protocol    string     `json:"protocol"`
	LocalPort   *string    `json:"local_port"`
	RemotePort  *string    `json:"remote_port"`
	NetworkID   *int64     `json:"network_id"`
	FirstSeen   *time.Time `json:"first_seen"`
	LastSeen    *time.Time `json:"last_seen"`
}

// Insert or refresh a neighbor edge. ON CONFLICT updates last_seen (and ports
// if they changed) without losing first_seen. The UNIQUE(device_id, neighbor_mac,
// protocol) constraint backs the conflict target.
func (q *Queries) UpsertDeviceNeighbor(ctx context.Context, arg UpsertDeviceNeighborParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceNeighbor,
		arg.DeviceID,
		arg.NeighborMac,
		arg.Protocol,
		arg.LocalPort,
		arg.RemotePort,
		arg.NetworkID,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
