// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_liveness.sql

package db

import (
	"context"
	"time"
)

const countDeviceLiveness = `-- name: CountDeviceLiveness :one
SELECT COUNT(*) FROM device_liveness
WHERE device_id = ? AND checked_at >= ? AND checked_at <= ?
`

type CountDeviceLivenessParams struct {
	DeviceID    int64     `json:"device_id"`
	CheckedAt   time.Time `json:"checked_at"`
	CheckedAt_2 time.Time `json:"checked_at_2"`
}

func (q *Queries) CountDeviceLiveness(ctx context.Context, arg CountDeviceLivenessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeviceLiveness, arg.DeviceID, arg.CheckedAt, arg.CheckedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLivenessByDevice = `-- name: DeleteLivenessByDevice :execrows
DELETE FROM device_liveness WHERE device_id = ?
`

func (q *Queries) DeleteLivenessByDevice(ctx context.Context, deviceID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLivenessByDevice, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLivenessOlderThanBatched = `-- name: DeleteLivenessOlderThanBatched :execrows
DELETE FROM device_liveness
WHERE rowid IN (
    SELECT rowid FROM device_liveness WHERE device_liveness.checked_at < ? LIMIT ?
)
`

type DeleteLivenessOlderThanBatchedParams struct {
	CheckedAt time.Time `json:"checked_at"`
	Limit     int64     `json:"limit"`
}

func (q *Queries) DeleteLivenessOlderThanBatched(ctx context.Context, arg DeleteLivenessOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLivenessOlderThanBatched, arg.CheckedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLastOnlineAt = `-- name: GetLastOnlineAt :one
SELECT checked_at FROM device_liveness
WHERE device_id = ? AND status = 'online'
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLastOnlineAt(ctx context.Context, deviceID int64) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastOnlineAt, deviceID)
	var checked_at time.Time
	err := row.Scan(&checked_at)
	return checked_at, err
}

const getOnlineRatio = `-- name: GetOnlineRatio :one
SELECT
    CAST(COALESCE(CAST(SUM(CASE WHEN status = 'online' THEN 1 ELSE 0 END) AS REAL) / COUNT(*), 0.0) AS REAL) AS online_ratio,
    CAST(COUNT(*) AS INTEGER) AS sample_count
FROM device_liveness
WHERE device_id = ? AND checked_at >= ?
`

type GetOnlineRatioParams struct {
	DeviceID  int64     `json:"device_id"`
	CheckedAt time.Time `json:"checked_at"`
}

type GetOnlineRatioRow struct {
	OnlineRatio float64 `json:"online_ratio"`
	SampleCount int64   `json:"sample_count"`
}

func (q *Queries) GetOnlineRatio(ctx context.Context, arg GetOnlineRatioParams) (GetOnlineRatioRow, error) {
	row := q.db.QueryRowContext(ctx, getOnlineRatio, arg.DeviceID, arg.CheckedAt)
	var i GetOnlineRatioRow
	err := row.Scan(&i.OnlineRatio, &i.SampleCount)
	return i, err
}

const listDeviceLiveness = `-- name: ListDeviceLiveness :many


SELECT id, device_id, status, source, checked_at
FROM device_liveness
WHERE device_id = ? AND checked_at >= ? AND checked_at <= ?
ORDER BY checked_at DESC
LIMIT ? OFFSET ?
`

type ListDeviceLivenessParams struct {
	DeviceID    int64     `json:"device_id"`
	CheckedAt   time.Time `json:"checked_at"`
	CheckedAt_2 time.Time `json:"checked_at_2"`
	Limit       int64     `json:"limit"`
	Offset      int64     `json:"offset"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// device_liveness queries. The table physically lives in heartbeat.db (declared
// in db/schema.sql only so sqlc can generate this code). checked_at is stored as
// RFC3339 text (see heartbeat_store.go commitLivenessBatch), so range filters
// use plain comparison (text-lexicographic == chronological for RFC3339) and
// avoid SQLite date() arithmetic which is NULL on that format.
func (q *Queries) ListDeviceLiveness(ctx context.Context, arg ListDeviceLivenessParams) ([]DeviceLiveness, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceLiveness,
		arg.DeviceID,
		arg.CheckedAt,
		arg.CheckedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceLiveness{}
	for rows.Next() {
		var i DeviceLiveness
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Status,
			&i.Source,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
