// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: devices.sql

package db

import (
	"context"
	"time"
)

const countByStatus = `-- name: CountByStatus :many
SELECT status, COUNT(*) AS count
FROM devices
GROUP BY status
`

type CountByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountByStatus(ctx context.Context) ([]CountByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByStatusRow{}
	for rows.Next() {
		var i CountByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByStatusForNetwork = `-- name: CountByStatusForNetwork :many
SELECT status, COUNT(*) AS count
FROM devices
WHERE (? = 0 OR network_id = ?)
GROUP BY status
`

type CountByStatusForNetworkParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID *int64      `json:"network_id"`
}

type CountByStatusForNetworkRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Filters to a single network before grouping (multi-LAN dashboards).
// Column1=0 disables the filter (matches all networks incl. NULL-network).
func (q *Queries) CountByStatusForNetwork(ctx context.Context, arg CountByStatusForNetworkParams) ([]CountByStatusForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, countByStatusForNetwork, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountByStatusForNetworkRow{}
	for rows.Next() {
		var i CountByStatusForNetworkRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*)
FROM devices
WHERE (? = '' OR status = ?)
  AND (? = '' OR type = ?)
`

type CountDevicesParams struct {
	Column1 interface{} `json:"column_1"`
	Status  string      `json:"status"`
	Column3 interface{} `json:"column_3"`
	Type    string      `json:"type"`
}

func (q *Queries) CountDevices(ctx context.Context, arg CountDevicesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.Type,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevicesByType = `-- name: CountDevicesByType :many
SELECT type, COUNT(*) AS count
FROM devices
GROUP BY type
`

type CountDevicesByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) CountDevicesByType(ctx context.Context) ([]CountDevicesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countDevicesByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDevicesByTypeRow{}
	for rows.Next() {
		var i CountDevicesByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDevicesByTypeForNetwork = `-- name: CountDevicesByTypeForNetwork :many
SELECT type, COUNT(*) AS count
FROM devices
WHERE (? = 0 OR network_id = ?)
GROUP BY type
`

type CountDevicesByTypeForNetworkParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID *int64      `json:"network_id"`
}

type CountDevicesByTypeForNetworkRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

func (q *Queries) CountDevicesByTypeForNetwork(ctx context.Context, arg CountDevicesByTypeForNetworkParams) ([]CountDevicesByTypeForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, countDevicesByTypeForNetwork, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDevicesByTypeForNetworkRow{}
	for rows.Next() {
		var i CountDevicesByTypeForNetworkRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (
    name, type, brand, model, location, purpose, description,
    status, ip_address, mac_address, serial_number,
    purchase_date, warranty_expiry, tags, user_attributes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
`

type CreateDeviceParams struct {
	Name           string `json:"name"`
	Type           string `json:"type"`
	Brand          string `json:"brand"`
	Model          string `json:"model"`
	Location       string `json:"location"`
	Purpose        string `json:"purpose"`
	Description    string `json:"description"`
	Status         string `json:"status"`
	IpAddress      string `json:"ip_address"`
	MacAddress     string `json:"mac_address"`
	SerialNumber   string `json:"serial_number"`
	PurchaseDate   string `json:"purchase_date"`
	WarrantyExpiry string `json:"warranty_expiry"`
	Tags           string `json:"tags"`
	UserAttributes string `json:"user_attributes"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.Name,
		arg.Type,
		arg.Brand,
		arg.Model,
		arg.Location,
		arg.Purpose,
		arg.Description,
		arg.Status,
		arg.IpAddress,
		arg.MacAddress,
		arg.SerialNumber,
		arg.PurchaseDate,
		arg.WarrantyExpiry,
		arg.Tags,
		arg.UserAttributes,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Location,
		&i.Purpose,
		&i.Description,
		&i.Status,
		&i.IpAddress,
		&i.MacAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.Tags,
		&i.ScanSource,
		&i.PrometheusLabels,
		&i.LastScannedAt,
		&i.LastScanTaskID,
		&i.OpenPorts,
		&i.DetectedServices,
		&i.PrometheusUrl,
		&i.NodeExporterUrl,
		&i.LastScanRttMs,
		&i.ScanAttributes,
		&i.UserAttributes,
		&i.ScanVendor,
		&i.ScanMac,
		&i.ScanOs,
		&i.ScanHostname,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices
WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
FROM devices
WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Location,
		&i.Purpose,
		&i.Description,
		&i.Status,
		&i.IpAddress,
		&i.MacAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.Tags,
		&i.ScanSource,
		&i.PrometheusLabels,
		&i.LastScannedAt,
		&i.LastScanTaskID,
		&i.OpenPorts,
		&i.DetectedServices,
		&i.PrometheusUrl,
		&i.NodeExporterUrl,
		&i.LastScanRttMs,
		&i.ScanAttributes,
		&i.UserAttributes,
		&i.ScanVendor,
		&i.ScanMac,
		&i.ScanOs,
		&i.ScanHostname,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByIP = `-- name: GetDeviceByIP :one
SELECT id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
FROM devices
WHERE ip_address = ?
LIMIT 1
`

func (q *Queries) GetDeviceByIP(ctx context.Context, ipAddress string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByIP, ipAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Location,
		&i.Purpose,
		&i.Description,
		&i.Status,
		&i.IpAddress,
		&i.MacAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.Tags,
		&i.ScanSource,
		&i.PrometheusLabels,
		&i.LastScannedAt,
		&i.LastScanTaskID,
		&i.OpenPorts,
		&i.DetectedServices,
		&i.PrometheusUrl,
		&i.NodeExporterUrl,
		&i.LastScanRttMs,
		&i.ScanAttributes,
		&i.UserAttributes,
		&i.ScanVendor,
		&i.ScanMac,
		&i.ScanOs,
		&i.ScanHostname,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
FROM devices
WHERE json_extract(scan_attributes, '$.mac') = ?
LIMIT 1
`

// Looks up by normalized scan MAC. Uses json_extract so the query works on
// both fresh installs (which have the scan_mac generated column) and upgraded
// DBs (which have an expression index on json_extract instead). The expression
// index idx_devices_scan_mac_expr covers this WHERE clause on either shape.
func (q *Queries) GetDeviceByMAC(ctx context.Context, scanAttributes string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByMAC, scanAttributes)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Location,
		&i.Purpose,
		&i.Description,
		&i.Status,
		&i.IpAddress,
		&i.MacAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.Tags,
		&i.ScanSource,
		&i.PrometheusLabels,
		&i.LastScannedAt,
		&i.LastScanTaskID,
		&i.OpenPorts,
		&i.DetectedServices,
		&i.PrometheusUrl,
		&i.NodeExporterUrl,
		&i.LastScanRttMs,
		&i.ScanAttributes,
		&i.UserAttributes,
		&i.ScanVendor,
		&i.ScanMac,
		&i.ScanOs,
		&i.ScanHostname,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
FROM devices
WHERE (? = '' OR status = ?)
  AND (? = '' OR type = ?)
ORDER BY id
LIMIT ? OFFSET ?
`

type ListDevicesParams struct {
	Column1 interface{} `json:"column_1"`
	Status  string      `json:"status"`
	Column3 interface{} `json:"column_3"`
	Type    string      `json:"type"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Brand,
			&i.Model,
			&i.Location,
			&i.Purpose,
			&i.Description,
			&i.Status,
			&i.IpAddress,
			&i.MacAddress,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.WarrantyExpiry,
			&i.Tags,
			&i.ScanSource,
			&i.PrometheusLabels,
			&i.LastScannedAt,
			&i.LastScanTaskID,
			&i.OpenPorts,
			&i.DetectedServices,
			&i.PrometheusUrl,
			&i.NodeExporterUrl,
			&i.LastScanRttMs,
			&i.ScanAttributes,
			&i.UserAttributes,
			&i.ScanVendor,
			&i.ScanMac,
			&i.ScanOs,
			&i.ScanHostname,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyDevices = `-- name: ListTopologyDevices :many
SELECT id, name, ip_address, mac_address, type, status, scan_vendor, scan_mac, scan_os, scan_hostname, network_id
FROM devices
WHERE (? <= 0 OR network_id = ?)
ORDER BY id
`

type ListTopologyDevicesParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID *int64      `json:"network_id"`
}

type ListTopologyDevicesRow struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	IpAddress    string  `json:"ip_address"`
	MacAddress   string  `json:"mac_address"`
	Type         string  `json:"type"`
	Status       string  `json:"status"`
	ScanVendor   *string `json:"scan_vendor"`
	ScanMac      *string `json:"scan_mac"`
	ScanOs       *string `json:"scan_os"`
	ScanHostname *string `json:"scan_hostname"`
	NetworkID    *int64  `json:"network_id"`
}

// Lightweight node projection for the topology graph: only the columns the
// graph needs (id/name/ip/mac/type/status + inferred type/brand from scan_*).
// network_id <= 0 means "all networks".
func (q *Queries) ListTopologyDevices(ctx context.Context, arg ListTopologyDevicesParams) ([]ListTopologyDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopologyDevices, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopologyDevicesRow{}
	for rows.Next() {
		var i ListTopologyDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.MacAddress,
			&i.Type,
			&i.Status,
			&i.ScanVendor,
			&i.ScanMac,
			&i.ScanOs,
			&i.ScanHostname,
			&i.NetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET name = ?, type = ?, brand = ?, model = ?, location = ?, purpose = ?, description = ?,
    status = ?, ip_address = ?, mac_address = ?, serial_number = ?,
    purchase_date = ?, warranty_expiry = ?, tags = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, brand, model, location, purpose, description, status, ip_address, mac_address, serial_number, purchase_date, warranty_expiry, tags, scan_source, prometheus_labels, last_scanned_at, last_scan_task_id, open_ports, detected_services, prometheus_url, node_exporter_url, last_scan_rtt_ms, scan_attributes, user_attributes, scan_vendor, scan_mac, scan_os, scan_hostname, network_id, first_seen, last_seen, created_at, updated_at
`

type UpdateDeviceParams struct {
	Name           string `json:"name"`
	Type           string `json:"type"`
	Brand          string `json:"brand"`
	Model          string `json:"model"`
	Location       string `json:"location"`
	Purpose        string `json:"purpose"`
	Description    string `json:"description"`
	Status         string `json:"status"`
	IpAddress      string `json:"ip_address"`
	MacAddress     string `json:"mac_address"`
	SerialNumber   string `json:"serial_number"`
	PurchaseDate   string `json:"purchase_date"`
	WarrantyExpiry string `json:"warranty_expiry"`
	Tags           string `json:"tags"`
	ID             int64  `json:"id"`
}

// Note: scan_attributes is engine-owned and intentionally NOT updated here.
// user_attributes is updated via UpdateUserAttributes so the full-row update
// can't race the user-edit path.
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.Name,
		arg.Type,
		arg.Brand,
		arg.Model,
		arg.Location,
		arg.Purpose,
		arg.Description,
		arg.Status,
		arg.IpAddress,
		arg.MacAddress,
		arg.SerialNumber,
		arg.PurchaseDate,
		arg.WarrantyExpiry,
		arg.Tags,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Brand,
		&i.Model,
		&i.Location,
		&i.Purpose,
		&i.Description,
		&i.Status,
		&i.IpAddress,
		&i.MacAddress,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.WarrantyExpiry,
		&i.Tags,
		&i.ScanSource,
		&i.PrometheusLabels,
		&i.LastScannedAt,
		&i.LastScanTaskID,
		&i.OpenPorts,
		&i.DetectedServices,
		&i.PrometheusUrl,
		&i.NodeExporterUrl,
		&i.LastScanRttMs,
		&i.ScanAttributes,
		&i.UserAttributes,
		&i.ScanVendor,
		&i.ScanMac,
		&i.ScanOs,
		&i.ScanHostname,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceScanInfo = `-- name: UpdateDeviceScanInfo :exec
UPDATE devices
SET scan_source = ?, prometheus_labels = ?, last_scanned_at = ?, last_scan_task_id = ?, open_ports = ?, detected_services = ?, prometheus_url = ?, node_exporter_url = ?, last_scan_rtt_ms = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDeviceScanInfoParams struct {
	ScanSource       string     `json:"scan_source"`
	PrometheusLabels string     `json:"prometheus_labels"`
	LastScannedAt    *time.Time `json:"last_scanned_at"`
	LastScanTaskID   *int64     `json:"last_scan_task_id"`
	OpenPorts        string     `json:"open_ports"`
	DetectedServices string     `json:"detected_services"`
	PrometheusUrl    string     `json:"prometheus_url"`
	NodeExporterUrl  string     `json:"node_exporter_url"`
	LastScanRttMs    int64      `json:"last_scan_rtt_ms"`
	ID               int64      `json:"id"`
}

func (q *Queries) UpdateDeviceScanInfo(ctx context.Context, arg UpdateDeviceScanInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceScanInfo,
		arg.ScanSource,
		arg.PrometheusLabels,
		arg.LastScannedAt,
		arg.LastScanTaskID,
		arg.OpenPorts,
		arg.DetectedServices,
		arg.PrometheusUrl,
		arg.NodeExporterUrl,
		arg.LastScanRttMs,
		arg.ID,
	)
	return err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :exec
UPDATE devices
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDeviceStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

// Updates ONLY the status column (and updated_at). Used by the heartbeat
// service so a status transition doesn't clobber other columns (name, tags,
// location, ...) that may have been edited between the GetDevice read and this
// write -- the full-row UpdateDevice path is racy in that window.
func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceStatus, arg.Status, arg.ID)
	return err
}

const updateScanAttributes = `-- name: UpdateScanAttributes :exec
UPDATE devices SET scan_attributes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateScanAttributesParams struct {
	ScanAttributes string `json:"scan_attributes"`
	ID             int64  `json:"id"`
}

// Engine-only: replaces the full scan_attributes document. Device bridge and
// store/sqlite call this with the freshly-marshalled JSON after a scan run.
func (q *Queries) UpdateScanAttributes(ctx context.Context, arg UpdateScanAttributesParams) error {
	_, err := q.db.ExecContext(ctx, updateScanAttributes, arg.ScanAttributes, arg.ID)
	return err
}

const updateUserAttributes = `-- name: UpdateUserAttributes :exec
UPDATE devices SET user_attributes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserAttributesParams struct {
	UserAttributes string `json:"user_attributes"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateUserAttributes(ctx context.Context, arg UpdateUserAttributesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAttributes, arg.UserAttributes, arg.ID)
	return err
}
