// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package db

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (title, type, url, file_path, file_size, mime_type, description)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, type, url, file_path, file_size, mime_type, description, created_at, updated_at
`

type CreateDocumentParams struct {
	Title       string `json:"title"`
	Type        string `json:"type"`
	Url         string `json:"url"`
	FilePath    string `json:"file_path"`
	FileSize    int64  `json:"file_size"`
	MimeType    string `json:"mime_type"`
	Description string `json:"description"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.Title,
		arg.Type,
		arg.Url,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.Description,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Url,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, type, url, file_path, file_size, mime_type, description, created_at, updated_at
FROM documents
WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Url,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, type, url, file_path, file_size, mime_type, description, created_at, updated_at
FROM documents
ORDER BY id
LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Url,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = ?, type = ?, url = ?, file_path = ?, file_size = ?, mime_type = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, type, url, file_path, file_size, mime_type, description, created_at, updated_at
`

type UpdateDocumentParams struct {
	Title       string `json:"title"`
	Type        string `json:"type"`
	Url         string `json:"url"`
	FilePath    string `json:"file_path"`
	FileSize    int64  `json:"file_size"`
	MimeType    string `json:"mime_type"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.Title,
		arg.Type,
		arg.Url,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.Description,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Url,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
