// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: heartbeat_configs.sql

package db

import (
	"context"
)

const createHeartbeatConfig = `-- name: CreateHeartbeatConfig :one

INSERT INTO heartbeat_configs (device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled, created_at, updated_at
`

type CreateHeartbeatConfigParams struct {
	DeviceID        int64  `json:"device_id"`
	Method          string `json:"method"`
	Target          string `json:"target"`
	IntervalSeconds int64  `json:"interval_seconds"`
	TimeoutSeconds  int64  `json:"timeout_seconds"`
	SnmpCommunity   string `json:"snmp_community"`
	SnmpOid         string `json:"snmp_oid"`
	Enabled         int64  `json:"enabled"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateHeartbeatConfig(ctx context.Context, arg CreateHeartbeatConfigParams) (HeartbeatConfig, error) {
	row := q.db.QueryRowContext(ctx, createHeartbeatConfig,
		arg.DeviceID,
		arg.Method,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.SnmpCommunity,
		arg.SnmpOid,
		arg.Enabled,
	)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Method,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.SnmpCommunity,
		&i.SnmpOid,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHeartbeatConfig = `-- name: DeleteHeartbeatConfig :execrows
DELETE FROM heartbeat_configs
WHERE id = ?
`

func (q *Queries) DeleteHeartbeatConfig(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHeartbeatConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHeartbeatConfig = `-- name: GetHeartbeatConfig :one
SELECT id, device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled, created_at, updated_at
FROM heartbeat_configs
WHERE id = ?
`

func (q *Queries) GetHeartbeatConfig(ctx context.Context, id int64) (HeartbeatConfig, error) {
	row := q.db.QueryRowContext(ctx, getHeartbeatConfig, id)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Method,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.SnmpCommunity,
		&i.SnmpOid,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledConfigs = `-- name: ListEnabledConfigs :many
SELECT id, device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled, created_at, updated_at
FROM heartbeat_configs
WHERE enabled = 1
`

func (q *Queries) ListEnabledConfigs(ctx context.Context) ([]HeartbeatConfig, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatConfig{}
	for rows.Next() {
		var i HeartbeatConfig
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Method,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.SnmpCommunity,
			&i.SnmpOid,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatConfigsByDevice = `-- name: ListHeartbeatConfigsByDevice :many
SELECT id, device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled, created_at, updated_at
FROM heartbeat_configs
WHERE device_id = ?
`

func (q *Queries) ListHeartbeatConfigsByDevice(ctx context.Context, deviceID int64) ([]HeartbeatConfig, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatConfigsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatConfig{}
	for rows.Next() {
		var i HeartbeatConfig
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Method,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.SnmpCommunity,
			&i.SnmpOid,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeartbeatConfig = `-- name: UpdateHeartbeatConfig :one
UPDATE heartbeat_configs
SET method = ?, target = ?, interval_seconds = ?, timeout_seconds = ?,
    snmp_community = ?, snmp_oid = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, device_id, method, target, interval_seconds, timeout_seconds, snmp_community, snmp_oid, enabled, created_at, updated_at
`

type UpdateHeartbeatConfigParams struct {
	Method          string `json:"method"`
	Target          string `json:"target"`
	IntervalSeconds int64  `json:"interval_seconds"`
	TimeoutSeconds  int64  `json:"timeout_seconds"`
	SnmpCommunity   string `json:"snmp_community"`
	SnmpOid         string `json:"snmp_oid"`
	Enabled         int64  `json:"enabled"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateHeartbeatConfig(ctx context.Context, arg UpdateHeartbeatConfigParams) (HeartbeatConfig, error) {
	row := q.db.QueryRowContext(ctx, updateHeartbeatConfig,
		arg.Method,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.SnmpCommunity,
		arg.SnmpOid,
		arg.Enabled,
		arg.ID,
	)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Method,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.SnmpCommunity,
		&i.SnmpOid,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
