// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: host_tls_certs.sql

package db

import (
	"context"
	"time"
)

const deleteHostTLSCertsStaleBatched = `-- name: DeleteHostTLSCertsStaleBatched :execrows
DELETE FROM host_tls_certs
WHERE id IN (
    SELECT sub.id FROM host_tls_certs AS sub WHERE sub.updated_at < ? LIMIT ?
)
`

type DeleteHostTLSCertsStaleBatchedParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int64     `json:"limit"`
}

// Retention sweep (batched) for host_tls_certs. Mirrors the host_services
// retention pattern: rows for hosts that have gone silent are never refreshed
// and linger, so this removes rows whose updated_at is older than the cutoff,
// in batches to avoid holding the write lock on large tables.
func (q *Queries) DeleteHostTLSCertsStaleBatched(ctx context.Context, arg DeleteHostTLSCertsStaleBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHostTLSCertsStaleBatched, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTLSCertsByDeviceID = `-- name: ListTLSCertsByDeviceID :many
SELECT c.id, c.ip, c.port, c.cert_index, c.subject_cn, c.subject_org, c.subject, c.issuer_cn, c.issuer_org, c.issuer, c.san_dns, c.san_ip, c.san_email, c.serial, c.not_before, c.not_after, c.sig_algorithm, c.key_algorithm, c.key_bits, c.is_ca, c.self_signed, c.fingerprint_sha256, c.pem, c.tls_version, c.cipher_suite, c.trusted, c.error, c.updated_at
FROM host_tls_certs AS c
JOIN devices AS d ON d.ip_address = c.ip
WHERE d.id = ?
ORDER BY c.port ASC, c.cert_index ASC
`

// Join through devices (composite-unique on (ip_address, network_id) means a
// device's IP is its cert lookup key). Includes certs from every port on the
// device, ordered for stable UI display (port, then chain order).
func (q *Queries) ListTLSCertsByDeviceID(ctx context.Context, id int64) ([]HostTlsCert, error) {
	rows, err := q.db.QueryContext(ctx, listTLSCertsByDeviceID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostTlsCert{}
	for rows.Next() {
		var i HostTlsCert
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Port,
			&i.CertIndex,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.Subject,
			&i.IssuerCn,
			&i.IssuerOrg,
			&i.Issuer,
			&i.SanDns,
			&i.SanIp,
			&i.SanEmail,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.SigAlgorithm,
			&i.KeyAlgorithm,
			&i.KeyBits,
			&i.IsCa,
			&i.SelfSigned,
			&i.FingerprintSha256,
			&i.Pem,
			&i.TlsVersion,
			&i.CipherSuite,
			&i.Trusted,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTLSCertsByIP = `-- name: ListTLSCertsByIP :many
SELECT id, ip, port, cert_index, subject_cn, subject_org, subject, issuer_cn, issuer_org, issuer, san_dns, san_ip, san_email, serial, not_before, not_after, sig_algorithm, key_algorithm, key_bits, is_ca, self_signed, fingerprint_sha256, pem, tls_version, cipher_suite, trusted, error, updated_at FROM host_tls_certs
WHERE ip = ?
ORDER BY port ASC, cert_index ASC
`

func (q *Queries) ListTLSCertsByIP(ctx context.Context, ip string) ([]HostTlsCert, error) {
	rows, err := q.db.QueryContext(ctx, listTLSCertsByIP, ip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostTlsCert{}
	for rows.Next() {
		var i HostTlsCert
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Port,
			&i.CertIndex,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.Subject,
			&i.IssuerCn,
			&i.IssuerOrg,
			&i.Issuer,
			&i.SanDns,
			&i.SanIp,
			&i.SanEmail,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.SigAlgorithm,
			&i.KeyAlgorithm,
			&i.KeyBits,
			&i.IsCa,
			&i.SelfSigned,
			&i.FingerprintSha256,
			&i.Pem,
			&i.TlsVersion,
			&i.CipherSuite,
			&i.Trusted,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
