// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_tls_certs.sql

package db

import (
	"context"
	"time"
)

const deleteHostTLSCertsForIPPort = `-- name: DeleteHostTLSCertsForIPPort :exec
DELETE FROM host_tls_certs WHERE ip = ? AND port = ?
`

type DeleteHostTLSCertsForIPPortParams struct {
	Ip   string `json:"ip"`
	Port int64  `json:"port"`
}

// Per-(ip, port) wholesale replace (the delete half of the store
// RecordTLSCerts, #269): a rotated cert must not linger, but ports NOT in
// this call keep their rows (a partial scan must not wipe untouched ports).
func (q *Queries) DeleteHostTLSCertsForIPPort(ctx context.Context, arg DeleteHostTLSCertsForIPPortParams) error {
	_, err := q.db.ExecContext(ctx, deleteHostTLSCertsForIPPort, arg.Ip, arg.Port)
	return err
}

const deleteHostTLSCertsStaleBatched = `-- name: DeleteHostTLSCertsStaleBatched :execrows
DELETE FROM host_tls_certs
WHERE id IN (
    SELECT sub.id FROM host_tls_certs AS sub WHERE sub.updated_at < ? LIMIT ?
)
`

type DeleteHostTLSCertsStaleBatchedParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int64     `json:"limit"`
}

// Retention sweep (batched) for host_tls_certs. Mirrors the host_services
// retention pattern: rows for hosts that have gone silent are never refreshed
// and linger, so this removes rows whose updated_at is older than the cutoff,
// in batches to avoid holding the write lock on large tables.
func (q *Queries) DeleteHostTLSCertsStaleBatched(ctx context.Context, arg DeleteHostTLSCertsStaleBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHostTLSCertsStaleBatched, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHostTLSCert = `-- name: InsertHostTLSCert :exec
INSERT INTO host_tls_certs (
    ip, device_uuid, port, cert_index,
    subject_cn, subject_org, subject, issuer_cn, issuer_org, issuer,
    san_dns, san_ip, san_email, serial,
    not_before, not_after,
    sig_algorithm, key_algorithm, key_bits, is_ca, self_signed,
    fingerprint_sha256, pem,
    tls_version, cipher_suite, trusted, error, updated_at
) VALUES (?, ?, ?, ?,  ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?,  CAST(? AS TEXT), CAST(? AS TEXT),  ?, ?, ?, ?, ?,  ?, ?,  ?, ?, ?, ?, CAST(? AS TEXT))
`

type InsertHostTLSCertParams struct {
	Ip                string `json:"ip"`
	DeviceUuid        string `json:"device_uuid"`
	Port              int64  `json:"port"`
	CertIndex         int64  `json:"cert_index"`
	SubjectCn         string `json:"subject_cn"`
	SubjectOrg        string `json:"subject_org"`
	Subject           string `json:"subject"`
	IssuerCn          string `json:"issuer_cn"`
	IssuerOrg         string `json:"issuer_org"`
	Issuer            string `json:"issuer"`
	SanDns            string `json:"san_dns"`
	SanIp             string `json:"san_ip"`
	SanEmail          string `json:"san_email"`
	Serial            string `json:"serial"`
	Column15          string `json:"column_15"`
	Column16          string `json:"column_16"`
	SigAlgorithm      string `json:"sig_algorithm"`
	KeyAlgorithm      string `json:"key_algorithm"`
	KeyBits           int64  `json:"key_bits"`
	IsCa              int64  `json:"is_ca"`
	SelfSigned        int64  `json:"self_signed"`
	FingerprintSha256 string `json:"fingerprint_sha256"`
	Pem               string `json:"pem"`
	TlsVersion        string `json:"tls_version"`
	CipherSuite       string `json:"cipher_suite"`
	Trusted           int64  `json:"trusted"`
	Error             string `json:"error"`
	Column28          string `json:"column_28"`
}

// One certificate-chain row (cert_index 0 = leaf); the per-(ip, port)
// DELETE runs first in the same tx. Column list mirrors the store raw
// insert verbatim; not_before/not_after/updated_at are RFC3339 text.
func (q *Queries) InsertHostTLSCert(ctx context.Context, arg InsertHostTLSCertParams) error {
	_, err := q.db.ExecContext(ctx, insertHostTLSCert,
		arg.Ip,
		arg.DeviceUuid,
		arg.Port,
		arg.CertIndex,
		arg.SubjectCn,
		arg.SubjectOrg,
		arg.Subject,
		arg.IssuerCn,
		arg.IssuerOrg,
		arg.Issuer,
		arg.SanDns,
		arg.SanIp,
		arg.SanEmail,
		arg.Serial,
		arg.Column15,
		arg.Column16,
		arg.SigAlgorithm,
		arg.KeyAlgorithm,
		arg.KeyBits,
		arg.IsCa,
		arg.SelfSigned,
		arg.FingerprintSha256,
		arg.Pem,
		arg.TlsVersion,
		arg.CipherSuite,
		arg.Trusted,
		arg.Error,
		arg.Column28,
	)
	return err
}

const listTLSCertsByDeviceID = `-- name: ListTLSCertsByDeviceID :many
SELECT c.id, c.ip, c.device_uuid, c.port, c.cert_index, c.subject_cn, c.subject_org, c.subject, c.issuer_cn, c.issuer_org, c.issuer, c.san_dns, c.san_ip, c.san_email, c.serial, c.not_before, c.not_after, c.sig_algorithm, c.key_algorithm, c.key_bits, c.is_ca, c.self_signed, c.fingerprint_sha256, c.pem, c.tls_version, c.cipher_suite, c.trusted, c.error, c.updated_at
FROM host_tls_certs AS c
JOIN devices AS d ON (
    (d.device_uuid != '' AND c.device_uuid = d.device_uuid)
    OR (c.device_uuid = '' AND c.ip = d.ip_address)
)
WHERE d.id = ?
ORDER BY c.port ASC, c.cert_index ASC
`

// Join through devices on device_uuid so certs follow the device across a DHCP
// roam (a device's IP is NOT stable, so the old ip-based join stranded the cert
// rows on the pre-roam IP). Transition rows with empty device_uuid fall back to
// the IP join. Ordered for stable UI display (port, then chain order).
func (q *Queries) ListTLSCertsByDeviceID(ctx context.Context, id int64) ([]HostTlsCert, error) {
	rows, err := q.db.QueryContext(ctx, listTLSCertsByDeviceID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostTlsCert{}
	for rows.Next() {
		var i HostTlsCert
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.DeviceUuid,
			&i.Port,
			&i.CertIndex,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.Subject,
			&i.IssuerCn,
			&i.IssuerOrg,
			&i.Issuer,
			&i.SanDns,
			&i.SanIp,
			&i.SanEmail,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.SigAlgorithm,
			&i.KeyAlgorithm,
			&i.KeyBits,
			&i.IsCa,
			&i.SelfSigned,
			&i.FingerprintSha256,
			&i.Pem,
			&i.TlsVersion,
			&i.CipherSuite,
			&i.Trusted,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTLSCertsByIP = `-- name: ListTLSCertsByIP :many

SELECT id, ip, device_uuid, port, cert_index, subject_cn, subject_org, subject, issuer_cn, issuer_org, issuer, san_dns, san_ip, san_email, serial, not_before, not_after, sig_algorithm, key_algorithm, key_bits, is_ca, self_signed, fingerprint_sha256, pem, tls_version, cipher_suite, trusted, error, updated_at FROM host_tls_certs
WHERE ip = ?
ORDER BY port ASC, cert_index ASC
`

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) ListTLSCertsByIP(ctx context.Context, ip string) ([]HostTlsCert, error) {
	rows, err := q.db.QueryContext(ctx, listTLSCertsByIP, ip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostTlsCert{}
	for rows.Next() {
		var i HostTlsCert
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.DeviceUuid,
			&i.Port,
			&i.CertIndex,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.Subject,
			&i.IssuerCn,
			&i.IssuerOrg,
			&i.Issuer,
			&i.SanDns,
			&i.SanIp,
			&i.SanEmail,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.SigAlgorithm,
			&i.KeyAlgorithm,
			&i.KeyBits,
			&i.IsCa,
			&i.SelfSigned,
			&i.FingerprintSha256,
			&i.Pem,
			&i.TlsVersion,
			&i.CipherSuite,
			&i.Trusted,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
