// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type AgentCommand struct {
	ID             int64      `json:"id"`
	AgentID        string     `json:"agent_id"`
	Command        string     `json:"command"`
	Payload        string     `json:"payload"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"created_at"`
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	Result         *string    `json:"result"`
}

type AgentToken struct {
	ID         int64      `json:"id"`
	AgentID    string     `json:"agent_id"`
	TokenHash  string     `json:"token_hash"`
	NetworkID  *int64     `json:"network_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type AuditLog struct {
	ID           int64      `json:"id"`
	UserID       *int64     `json:"user_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *string    `json:"resource_id"`
	IpAddress    *string    `json:"ip_address"`
	UserAgent    *string    `json:"user_agent"`
	Details      *string    `json:"details"`
	CreatedAt    *time.Time `json:"created_at"`
}

type ChangeLog struct {
	ID         int64     `json:"id"`
	AgentID    *string   `json:"agent_id"`
	NetworkID  *int64    `json:"network_id"`
	ChangeType string    `json:"change_type"`
	EntityType string    `json:"entity_type"`
	EntityID   *int64    `json:"entity_id"`
	BeforeData *string   `json:"before_data"`
	AfterData  *string   `json:"after_data"`
	DetectedAt time.Time `json:"detected_at"`
}

type DashboardConfig struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	Type            string    `json:"type"`
	DataSource      string    `json:"data_source"`
	Query           string    `json:"query"`
	RefreshInterval int64     `json:"refresh_interval"`
	Position        string    `json:"position"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Device struct {
	ID               int64      `json:"id"`
	Name             string     `json:"name"`
	Type             string     `json:"type"`
	Brand            string     `json:"brand"`
	Model            string     `json:"model"`
	Location         string     `json:"location"`
	Purpose          string     `json:"purpose"`
	Description      string     `json:"description"`
	Status           string     `json:"status"`
	IpAddress        string     `json:"ip_address"`
	MacAddress       string     `json:"mac_address"`
	SerialNumber     string     `json:"serial_number"`
	PurchaseDate     string     `json:"purchase_date"`
	WarrantyExpiry   string     `json:"warranty_expiry"`
	Tags             string     `json:"tags"`
	ScanSource       string     `json:"scan_source"`
	PrometheusLabels string     `json:"prometheus_labels"`
	LastScannedAt    *time.Time `json:"last_scanned_at"`
	LastScanTaskID   *int64     `json:"last_scan_task_id"`
	OpenPorts        string     `json:"open_ports"`
	DetectedServices string     `json:"detected_services"`
	PrometheusUrl    string     `json:"prometheus_url"`
	NodeExporterUrl  string     `json:"node_exporter_url"`
	LastScanRttMs    int64      `json:"last_scan_rtt_ms"`
	ScanAttributes   string     `json:"scan_attributes"`
	UserAttributes   string     `json:"user_attributes"`
	ScanVendor       *string    `json:"scan_vendor"`
	ScanMac          *string    `json:"scan_mac"`
	ScanOs           *string    `json:"scan_os"`
	ScanHostname     *string    `json:"scan_hostname"`
	NetworkID        *int64     `json:"network_id"`
	FirstSeen        *time.Time `json:"first_seen"`
	LastSeen         *time.Time `json:"last_seen"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type DeviceDocument struct {
	DeviceID   int64     `json:"device_id"`
	DocumentID int64     `json:"document_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type DeviceNeighbor struct {
	ID               int64      `json:"id"`
	DeviceID         int64      `json:"device_id"`
	NeighborDeviceID *int64     `json:"neighbor_device_id"`
	NeighborMac      string     `json:"neighbor_mac"`
	Protocol         string     `json:"protocol"`
	LocalPort        *string    `json:"local_port"`
	RemotePort       *string    `json:"remote_port"`
	NetworkID        *int64     `json:"network_id"`
	FirstSeen        *time.Time `json:"first_seen"`
	LastSeen         *time.Time `json:"last_seen"`
}

type DeviceSystem struct {
	ID             int64     `json:"id"`
	DeviceID       int64     `json:"device_id"`
	Name           string    `json:"name"`
	EntryUrl       string    `json:"entry_url"`
	Description    string    `json:"description"`
	Category       string    `json:"category"`
	MetricsUrl     string    `json:"metrics_url"`
	MetricsEnabled int64     `json:"metrics_enabled"`
	Tags           string    `json:"tags"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Document struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Type        string    `json:"type"`
	Url         string    `json:"url"`
	FilePath    string    `json:"file_path"`
	FileSize    int64     `json:"file_size"`
	MimeType    string    `json:"mime_type"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type HeartbeatConfig struct {
	ID              int64     `json:"id"`
	DeviceID        int64     `json:"device_id"`
	Method          string    `json:"method"`
	Target          string    `json:"target"`
	IntervalSeconds int64     `json:"interval_seconds"`
	TimeoutSeconds  int64     `json:"timeout_seconds"`
	SnmpCommunity   string    `json:"snmp_community"`
	SnmpOid         string    `json:"snmp_oid"`
	Enabled         int64     `json:"enabled"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type HeartbeatResult struct {
	ID           int64     `json:"id"`
	DeviceID     int64     `json:"device_id"`
	ConfigID     int64     `json:"config_id"`
	Status       string    `json:"status"`
	LatencyMs    float64   `json:"latency_ms"`
	ErrorMessage string    `json:"error_message"`
	CheckedAt    time.Time `json:"checked_at"`
}

type HostService struct {
	ID         int64     `json:"id"`
	Ip         string    `json:"ip"`
	Service    string    `json:"service"`
	Port       int64     `json:"port"`
	Protocol   string    `json:"protocol"`
	Confidence float64   `json:"confidence"`
	Metadata   string    `json:"metadata"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Network struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Cidr      *string   `json:"cidr"`
	Site      *string   `json:"site"`
	AgentID   *string   `json:"agent_id"`
	Metadata  string    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationChannel struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Config    string    `json:"config"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationLog struct {
	ID           int64     `json:"id"`
	RuleID       *int64    `json:"rule_id"`
	ChannelID    *int64    `json:"channel_id"`
	Status       string    `json:"status"`
	Payload      string    `json:"payload"`
	ErrorMessage string    `json:"error_message"`
	SentAt       time.Time `json:"sent_at"`
}

type ScanResult struct {
	ID                   int64     `json:"id"`
	TaskID               int64     `json:"task_id"`
	RunID                *int64    `json:"run_id"`
	Ip                   string    `json:"ip"`
	Alive                int64     `json:"alive"`
	RttMs                int64     `json:"rtt_ms"`
	Ports                string    `json:"ports"`
	Services             string    `json:"services"`
	SnmpData             string    `json:"snmp_data"`
	PrometheusDetected   int64     `json:"prometheus_detected"`
	PrometheusUrl        string    `json:"prometheus_url"`
	NodeExporterDetected int64     `json:"node_exporter_detected"`
	NodeExporterUrl      string    `json:"node_exporter_url"`
	NodeExporterData     string    `json:"node_exporter_data"`
	ScannedAt            time.Time `json:"scanned_at"`
}

type ScanSnapshot struct {
	ID         int64     `json:"id"`
	NetworkID  int64     `json:"network_id"`
	TaskID     *int64    `json:"task_id"`
	Ip         string    `json:"ip"`
	Mac        string    `json:"mac"`
	MissCount  int64     `json:"miss_count"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type ScanTask struct {
	ID              int64      `json:"id"`
	Name            string     `json:"name"`
	Targets         string     `json:"targets"`
	CronExpr        string     `json:"cron_expr"`
	PipelineConfig  string     `json:"pipeline_config"`
	GlobalLabels    string     `json:"global_labels"`
	Timeout         int64      `json:"timeout"`
	ConcurrentHosts int64      `json:"concurrent_hosts"`
	Enabled         int64      `json:"enabled"`
	LastRunAt       *time.Time `json:"last_run_at"`
	NextRunAt       *time.Time `json:"next_run_at"`
	LastRunStatus   *string    `json:"last_run_status"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type ScanTaskRun struct {
	ID           int64      `json:"id"`
	TaskID       int64      `json:"task_id"`
	Status       string     `json:"status"`
	TotalHosts   int64      `json:"total_hosts"`
	AliveHosts   int64      `json:"alive_hosts"`
	NewHosts     int64      `json:"new_hosts"`
	UpdatedHosts int64      `json:"updated_hosts"`
	DurationMs   int64      `json:"duration_ms"`
	ErrorMessage string     `json:"error_message"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type ServiceEvidence struct {
	ID         int64     `json:"id"`
	Ip         string    `json:"ip"`
	Source     string    `json:"source"`
	Kind       string    `json:"kind"`
	Port       int64     `json:"port"`
	Protocol   string    `json:"protocol"`
	RawData    string    `json:"raw_data"`
	Confidence float64   `json:"confidence"`
	ObservedAt time.Time `json:"observed_at"`
}

type Subnet struct {
	ID        int64      `json:"id"`
	NetworkID int64      `json:"network_id"`
	Cidr      string     `json:"cidr"`
	VlanID    *int64     `json:"vlan_id"`
	Gateway   *string    `json:"gateway"`
	Metadata  string     `json:"metadata"`
	FirstSeen *time.Time `json:"first_seen"`
	LastSeen  *time.Time `json:"last_seen"`
}

type TopologyEdge struct {
	ID           int64      `json:"id"`
	FromDeviceID int64      `json:"from_device_id"`
	ToDeviceID   int64      `json:"to_device_id"`
	EdgeType     string     `json:"edge_type"`
	ViaProtocol  *string    `json:"via_protocol"`
	Confidence   *float64   `json:"confidence"`
	Metadata     string     `json:"metadata"`
	FirstSeen    *time.Time `json:"first_seen"`
	LastSeen     *time.Time `json:"last_seen"`
}

type User struct {
	ID                  int64      `json:"id"`
	Username            string     `json:"username"`
	Email               string     `json:"email"`
	PasswordHash        string     `json:"password_hash"`
	Role                string     `json:"role"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	FailedLoginAttempts int64      `json:"failed_login_attempts"`
	LockedUntil         *time.Time `json:"locked_until"`
	PasswordChangedAt   *time.Time `json:"password_changed_at"`
	MustChangePassword  bool       `json:"must_change_password"`
}

type UserTotp struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Secret      string    `json:"secret"`
	Verified    int64     `json:"verified"`
	BackupCodes string    `json:"backup_codes"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Vlan struct {
	ID          int64      `json:"id"`
	VlanTag     int64      `json:"vlan_tag"`
	Name        *string    `json:"name"`
	Description *string    `json:"description"`
	NetworkID   *int64     `json:"network_id"`
	FirstSeen   *time.Time `json:"first_seen"`
	LastSeen    *time.Time `json:"last_seen"`
}
