// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: networks.sql

package db

import (
	"context"
)

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (name, cidr, site)
VALUES (?, ?, ?)
RETURNING id, name, cidr, site, agent_id, metadata, created_at, updated_at
`

type CreateNetworkParams struct {
	Name string  `json:"name"`
	Cidr *string `json:"cidr"`
	Site *string `json:"site"`
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRowContext(ctx, createNetwork, arg.Name, arg.Cidr, arg.Site)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.Site,
		&i.AgentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNetwork = `-- name: DeleteNetwork :exec
DELETE FROM networks WHERE id = ?
`

// Delete a logical network. All FK references are ON DELETE SET NULL or
// CASCADE, so this is safe at the DB level.
func (q *Queries) DeleteNetwork(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNetwork, id)
	return err
}

const getNetwork = `-- name: GetNetwork :one
SELECT id, name, cidr, site, agent_id, metadata, created_at, updated_at
FROM networks
WHERE id = ?
`

func (q *Queries) GetNetwork(ctx context.Context, id int64) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetwork, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.Site,
		&i.AgentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, name, cidr, site, agent_id, metadata, created_at, updated_at
FROM networks
ORDER BY id
`

func (q *Queries) ListNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.Site,
			&i.AgentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNetworkAgentID = `-- name: SetNetworkAgentID :exec
UPDATE networks SET agent_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetNetworkAgentIDParams struct {
	AgentID *string `json:"agent_id"`
	ID      int64   `json:"id"`
}

// Stamp (or clear) the discovering-agent id on a network. Called by the agent-
// token admin handler: when an admin mints a token bound to a network, the
// network is marked agent-managed so the center's heartbeat excludes it (the
// agent's reports ARE the liveness signal) and the lease sweeper scopes to it.
// Passing an empty string CLEARS the agent_id (used on token revoke/delete).
// Note: the value is a bind parameter (not a SQL literal), so this is safe from
// the sqlc SQLite empty-string-literal truncation bug that affects heartbeat.go
// and lease_sweeper.go (those use raw SQL for that reason).
func (q *Queries) SetNetworkAgentID(ctx context.Context, arg SetNetworkAgentIDParams) error {
	_, err := q.db.ExecContext(ctx, setNetworkAgentID, arg.AgentID, arg.ID)
	return err
}
