// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: networks.sql

package db

import (
	"context"
)

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (name, cidr, site)
VALUES (?, ?, ?)
RETURNING id, name, cidr, site, agent_id, metadata, created_at, updated_at
`

type CreateNetworkParams struct {
	Name string  `json:"name"`
	Cidr *string `json:"cidr"`
	Site *string `json:"site"`
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRowContext(ctx, createNetwork, arg.Name, arg.Cidr, arg.Site)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.Site,
		&i.AgentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNetwork = `-- name: GetNetwork :one
SELECT id, name, cidr, site, agent_id, metadata, created_at, updated_at
FROM networks
WHERE id = ?
`

func (q *Queries) GetNetwork(ctx context.Context, id int64) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetwork, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.Site,
		&i.AgentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, name, cidr, site, agent_id, metadata, created_at, updated_at
FROM networks
ORDER BY id
`

func (q *Queries) ListNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Network{}
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.Site,
			&i.AgentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
