// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"
)

const countNotificationLogs = `-- name: CountNotificationLogs :one
SELECT COUNT(*) FROM notification_log
`

func (q *Queries) CountNotificationLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotificationLogsForUser = `-- name: CountUnreadNotificationLogsForUser :one
SELECT COUNT(*) FROM notification_log l
WHERE NOT EXISTS(
    SELECT 1 FROM notification_read_states s
    WHERE s.user_id = ? AND s.notification_log_id = l.id
)
`

// Unread count for a user (logs with no matching read_state row).
func (q *Queries) CountUnreadNotificationLogsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotificationLogsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO notification_channels (name, type, config, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type CreateChannelParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO notification_log (rule_id, channel_id, status, payload, error_message)
VALUES (?, ?, ?, ?, ?)
RETURNING id, rule_id, channel_id, status, payload, error_message, sent_at
`

type CreateNotificationLogParams struct {
	RuleID       *int64 `json:"rule_id"`
	ChannelID    *int64 `json:"channel_id"`
	Status       string `json:"status"`
	Payload      string `json:"payload"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, createNotificationLog,
		arg.RuleID,
		arg.ChannelID,
		arg.Status,
		arg.Payload,
		arg.ErrorMessage,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.Status,
		&i.Payload,
		&i.ErrorMessage,
		&i.SentAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const deleteNotificationLogsOlderThanBatched = `-- name: DeleteNotificationLogsOlderThanBatched :execrows
DELETE FROM notification_log
WHERE rowid IN (
    SELECT rowid FROM notification_log WHERE notification_log.sent_at < ? LIMIT ?
)
`

type DeleteNotificationLogsOlderThanBatchedParams struct {
	SentAt time.Time `json:"sent_at"`
	Limit  int64     `json:"limit"`
}

// Retention sweep (batched): deletes up to ? rows older than the cutoff.
func (q *Queries) DeleteNotificationLogsOlderThanBatched(ctx context.Context, arg DeleteNotificationLogsOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationLogsOlderThanBatched, arg.SentAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels WHERE id = ?
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationLogByID = `-- name: GetNotificationLogByID :one
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE id = ?
`

func (q *Queries) GetNotificationLogByID(ctx context.Context, id int64) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, getNotificationLogByID, id)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.Status,
		&i.Payload,
		&i.ErrorMessage,
		&i.SentAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels ORDER BY created_at DESC
`

func (q *Queries) ListChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogs = `-- name: ListNotificationLogs :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log ORDER BY sent_at DESC LIMIT ? OFFSET ?
`

type ListNotificationLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotificationLogs(ctx context.Context, arg ListNotificationLogsParams) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsByChannel = `-- name: ListNotificationLogsByChannel :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE channel_id = ? ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogsByChannel(ctx context.Context, channelID *int64) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsByRule = `-- name: ListNotificationLogsByRule :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE rule_id = ? ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogsByRule(ctx context.Context, ruleID *int64) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsForUser = `-- name: ListNotificationLogsForUser :many
SELECT l.id, l.rule_id, l.channel_id, l.status, l.payload, l.error_message, l.sent_at,
       EXISTS(
           SELECT 1 FROM notification_read_states s
           WHERE s.user_id = ? AND s.notification_log_id = l.id
       ) AS is_read
FROM notification_log l
ORDER BY l.sent_at DESC
LIMIT ? OFFSET ?
`

type ListNotificationLogsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListNotificationLogsForUserRow struct {
	ID           int64     `json:"id"`
	RuleID       *int64    `json:"rule_id"`
	ChannelID    *int64    `json:"channel_id"`
	Status       string    `json:"status"`
	Payload      string    `json:"payload"`
	ErrorMessage string    `json:"error_message"`
	SentAt       time.Time `json:"sent_at"`
	IsRead       bool      `json:"is_read"`
}

// Recent notification logs with a per-user is_read flag (drives the bell's
// unread styling).notification_log is system-wide; read state is per-user.
func (q *Queries) ListNotificationLogsForUser(ctx context.Context, arg ListNotificationLogsForUserParams) ([]ListNotificationLogsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationLogsForUserRow{}
	for rows.Next() {
		var i ListNotificationLogsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationLogsRead = `-- name: MarkAllNotificationLogsRead :execrows
INSERT OR IGNORE INTO notification_read_states (user_id, notification_log_id)
SELECT ?, l.id FROM notification_log l
WHERE NOT EXISTS(
    SELECT 1 FROM notification_read_states s
    WHERE s.user_id = ? AND s.notification_log_id = l.id
)
`

type MarkAllNotificationLogsReadParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

// Idempotently mark all currently-unread notification logs as read for a
// user (INSERT OR IGNORE skips any pair already present). Returns the number
// of rows inserted (i.e. newly-read logs).
func (q *Queries) MarkAllNotificationLogsRead(ctx context.Context, arg MarkAllNotificationLogsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationLogsRead, arg.UserID, arg.UserID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setChannelEnabled = `-- name: SetChannelEnabled :one
UPDATE notification_channels
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type SetChannelEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

// Single-field UPDATE for the dedicated PATCH /channels/{id} toggle endpoint.
// Writing only `enabled` (not the full row) makes the intent explicit and
// avoids any GET-then-write race on name/type/config. See service.SetChannelEnabled.
func (q *Queries) SetChannelEnabled(ctx context.Context, arg SetChannelEnabledParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, setChannelEnabled, arg.Enabled, arg.ID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE notification_channels
SET name = ?, type = ?, config = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type UpdateChannelParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
