// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_rules.sql

package db

import (
	"context"
)

const createNotificationRule = `-- name: CreateNotificationRule :one
INSERT INTO notification_rules (name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at
`

type CreateNotificationRuleParams struct {
	Name            string `json:"name"`
	EventType       string `json:"event_type"`
	ScopeType       string `json:"scope_type"`
	ScopeNetworkID  *int64 `json:"scope_network_id"`
	ScopeDeviceUuid string `json:"scope_device_uuid"`
	ChannelID       int64  `json:"channel_id"`
	CooldownMinutes int64  `json:"cooldown_minutes"`
	Enabled         int64  `json:"enabled"`
}

func (q *Queries) CreateNotificationRule(ctx context.Context, arg CreateNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRowContext(ctx, createNotificationRule,
		arg.Name,
		arg.EventType,
		arg.ScopeType,
		arg.ScopeNetworkID,
		arg.ScopeDeviceUuid,
		arg.ChannelID,
		arg.CooldownMinutes,
		arg.Enabled,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventType,
		&i.ScopeType,
		&i.ScopeNetworkID,
		&i.ScopeDeviceUuid,
		&i.ChannelID,
		&i.CooldownMinutes,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationRule = `-- name: DeleteNotificationRule :exec
DELETE FROM notification_rules WHERE id = ?
`

func (q *Queries) DeleteNotificationRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationRule, id)
	return err
}

const getNotificationRule = `-- name: GetNotificationRule :one
SELECT id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at FROM notification_rules WHERE id = ?
`

func (q *Queries) GetNotificationRule(ctx context.Context, id int64) (NotificationRule, error) {
	row := q.db.QueryRowContext(ctx, getNotificationRule, id)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventType,
		&i.ScopeType,
		&i.ScopeNetworkID,
		&i.ScopeDeviceUuid,
		&i.ChannelID,
		&i.CooldownMinutes,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRulesByEventType = `-- name: ListEnabledRulesByEventType :many
SELECT id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at FROM notification_rules WHERE enabled = 1 AND event_type = ? ORDER BY id
`

func (q *Queries) ListEnabledRulesByEventType(ctx context.Context, eventType string) ([]NotificationRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRulesByEventType, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventType,
			&i.ScopeType,
			&i.ScopeNetworkID,
			&i.ScopeDeviceUuid,
			&i.ChannelID,
			&i.CooldownMinutes,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRules = `-- name: ListNotificationRules :many
SELECT id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at FROM notification_rules ORDER BY created_at DESC
`

func (q *Queries) ListNotificationRules(ctx context.Context) ([]NotificationRule, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventType,
			&i.ScopeType,
			&i.ScopeNetworkID,
			&i.ScopeDeviceUuid,
			&i.ChannelID,
			&i.CooldownMinutes,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRuleTriggered = `-- name: MarkNotificationRuleTriggered :exec
UPDATE notification_rules SET last_triggered_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkNotificationRuleTriggered(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNotificationRuleTriggered, id)
	return err
}

const setNotificationRuleEnabled = `-- name: SetNotificationRuleEnabled :one
UPDATE notification_rules SET enabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at
`

type SetNotificationRuleEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetNotificationRuleEnabled(ctx context.Context, arg SetNotificationRuleEnabledParams) (NotificationRule, error) {
	row := q.db.QueryRowContext(ctx, setNotificationRuleEnabled, arg.Enabled, arg.ID)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventType,
		&i.ScopeType,
		&i.ScopeNetworkID,
		&i.ScopeDeviceUuid,
		&i.ChannelID,
		&i.CooldownMinutes,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationRule = `-- name: UpdateNotificationRule :one
UPDATE notification_rules SET name = ?, event_type = ?, scope_type = ?, scope_network_id = ?, scope_device_uuid = ?, channel_id = ?, cooldown_minutes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, event_type, scope_type, scope_network_id, scope_device_uuid, channel_id, cooldown_minutes, enabled, last_triggered_at, created_at, updated_at
`

type UpdateNotificationRuleParams struct {
	Name            string `json:"name"`
	EventType       string `json:"event_type"`
	ScopeType       string `json:"scope_type"`
	ScopeNetworkID  *int64 `json:"scope_network_id"`
	ScopeDeviceUuid string `json:"scope_device_uuid"`
	ChannelID       int64  `json:"channel_id"`
	CooldownMinutes int64  `json:"cooldown_minutes"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateNotificationRule(ctx context.Context, arg UpdateNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationRule,
		arg.Name,
		arg.EventType,
		arg.ScopeType,
		arg.ScopeNetworkID,
		arg.ScopeDeviceUuid,
		arg.ChannelID,
		arg.CooldownMinutes,
		arg.ID,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventType,
		&i.ScopeType,
		&i.ScopeNetworkID,
		&i.ScopeDeviceUuid,
		&i.ChannelID,
		&i.CooldownMinutes,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
