// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"
)

const countNotificationLogs = `-- name: CountNotificationLogs :one
SELECT COUNT(*) FROM notification_log
`

func (q *Queries) CountNotificationLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name            string `json:"name"`
	DeviceID        *int64 `json:"device_id"`
	ConditionType   string `json:"condition_type"`
	Threshold       int64  `json:"threshold"`
	ChannelID       int64  `json:"channel_id"`
	Enabled         int64  `json:"enabled"`
	CooldownSeconds int64  `json:"cooldown_seconds"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, createAlertRule,
		arg.Name,
		arg.DeviceID,
		arg.ConditionType,
		arg.Threshold,
		arg.ChannelID,
		arg.Enabled,
		arg.CooldownSeconds,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.ConditionType,
		&i.Threshold,
		&i.ChannelID,
		&i.Enabled,
		&i.CooldownSeconds,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO notification_channels (name, type, config, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type CreateChannelParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO notification_log (rule_id, channel_id, status, payload, error_message)
VALUES (?, ?, ?, ?, ?)
RETURNING id, rule_id, channel_id, status, payload, error_message, sent_at
`

type CreateNotificationLogParams struct {
	RuleID       *int64 `json:"rule_id"`
	ChannelID    *int64 `json:"channel_id"`
	Status       string `json:"status"`
	Payload      string `json:"payload"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, createNotificationLog,
		arg.RuleID,
		arg.ChannelID,
		arg.Status,
		arg.Payload,
		arg.ErrorMessage,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.Status,
		&i.Payload,
		&i.ErrorMessage,
		&i.SentAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = ?
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertRule, id)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const getAlertRuleByID = `-- name: GetAlertRuleByID :one
SELECT id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at FROM alert_rules WHERE id = ?
`

func (q *Queries) GetAlertRuleByID(ctx context.Context, id int64) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, getAlertRuleByID, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.ConditionType,
		&i.Threshold,
		&i.ChannelID,
		&i.Enabled,
		&i.CooldownSeconds,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels WHERE id = ?
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationLogByID = `-- name: GetNotificationLogByID :one
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE id = ?
`

func (q *Queries) GetNotificationLogByID(ctx context.Context, id int64) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, getNotificationLogByID, id)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ChannelID,
		&i.Status,
		&i.Payload,
		&i.ErrorMessage,
		&i.SentAt,
	)
	return i, err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at FROM alert_rules ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceID,
			&i.ConditionType,
			&i.Threshold,
			&i.ChannelID,
			&i.Enabled,
			&i.CooldownSeconds,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesByDevice = `-- name: ListAlertRulesByDevice :many
SELECT id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at FROM alert_rules WHERE device_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAlertRulesByDevice(ctx context.Context, deviceID *int64) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRulesByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceID,
			&i.ConditionType,
			&i.Threshold,
			&i.ChannelID,
			&i.Enabled,
			&i.CooldownSeconds,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels ORDER BY created_at DESC
`

func (q *Queries) ListChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at FROM alert_rules WHERE enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceID,
			&i.ConditionType,
			&i.Threshold,
			&i.ChannelID,
			&i.Enabled,
			&i.CooldownSeconds,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogs = `-- name: ListNotificationLogs :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log ORDER BY sent_at DESC LIMIT ? OFFSET ?
`

type ListNotificationLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotificationLogs(ctx context.Context, arg ListNotificationLogsParams) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsByChannel = `-- name: ListNotificationLogsByChannel :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE channel_id = ? ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogsByChannel(ctx context.Context, channelID *int64) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsByRule = `-- name: ListNotificationLogsByRule :many
SELECT id, rule_id, channel_id, status, payload, error_message, sent_at FROM notification_log WHERE rule_id = ? ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogsByRule(ctx context.Context, ruleID *int64) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ChannelID,
			&i.Status,
			&i.Payload,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = ?, device_id = ?, condition_type = ?, threshold = ?, channel_id = ?,
    enabled = ?, cooldown_seconds = ?, last_triggered_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, device_id, condition_type, threshold, channel_id, enabled, cooldown_seconds, last_triggered_at, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	Name            string     `json:"name"`
	DeviceID        *int64     `json:"device_id"`
	ConditionType   string     `json:"condition_type"`
	Threshold       int64      `json:"threshold"`
	ChannelID       int64      `json:"channel_id"`
	Enabled         int64      `json:"enabled"`
	CooldownSeconds int64      `json:"cooldown_seconds"`
	LastTriggeredAt *time.Time `json:"last_triggered_at"`
	ID              int64      `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, updateAlertRule,
		arg.Name,
		arg.DeviceID,
		arg.ConditionType,
		arg.Threshold,
		arg.ChannelID,
		arg.Enabled,
		arg.CooldownSeconds,
		arg.LastTriggeredAt,
		arg.ID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.ConditionType,
		&i.Threshold,
		&i.ChannelID,
		&i.Enabled,
		&i.CooldownSeconds,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE notification_channels
SET name = ?, type = ?, config = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type UpdateChannelParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
