// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, used_at, created_at FROM password_reset_tokens WHERE token = ?
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPasswordResetTokensByUser = `-- name: ListPasswordResetTokensByUser :many
SELECT id, user_id, token, expires_at, used_at, created_at FROM password_reset_tokens WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPasswordResetTokensByUser(ctx context.Context, userID int64) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, listPasswordResetTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE token = ? AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, token)
	return err
}
