// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe_tls_certs.sql

package db

import (
	"context"
)

const createProbeTLSCert = `-- name: CreateProbeTLSCert :exec
INSERT INTO probe_tls_certs (target_id, port, cert_index, subject_cn, subject_org, subject, issuer_cn, issuer_org, issuer,
    san_dns, san_ip, san_email, serial, not_before, not_after, sig_algorithm, key_algorithm, key_bits,
    is_ca, self_signed, fingerprint_sha256, pem, tls_version, cipher_suite, trusted, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProbeTLSCertParams struct {
	TargetID          int64  `json:"target_id"`
	Port              int64  `json:"port"`
	CertIndex         int64  `json:"cert_index"`
	SubjectCn         string `json:"subject_cn"`
	SubjectOrg        string `json:"subject_org"`
	Subject           string `json:"subject"`
	IssuerCn          string `json:"issuer_cn"`
	IssuerOrg         string `json:"issuer_org"`
	Issuer            string `json:"issuer"`
	SanDns            string `json:"san_dns"`
	SanIp             string `json:"san_ip"`
	SanEmail          string `json:"san_email"`
	Serial            string `json:"serial"`
	NotBefore         string `json:"not_before"`
	NotAfter          string `json:"not_after"`
	SigAlgorithm      string `json:"sig_algorithm"`
	KeyAlgorithm      string `json:"key_algorithm"`
	KeyBits           int64  `json:"key_bits"`
	IsCa              int64  `json:"is_ca"`
	SelfSigned        int64  `json:"self_signed"`
	FingerprintSha256 string `json:"fingerprint_sha256"`
	Pem               string `json:"pem"`
	TlsVersion        string `json:"tls_version"`
	CipherSuite       string `json:"cipher_suite"`
	Trusted           int64  `json:"trusted"`
	Error             string `json:"error"`
}

func (q *Queries) CreateProbeTLSCert(ctx context.Context, arg CreateProbeTLSCertParams) error {
	_, err := q.db.ExecContext(ctx, createProbeTLSCert,
		arg.TargetID,
		arg.Port,
		arg.CertIndex,
		arg.SubjectCn,
		arg.SubjectOrg,
		arg.Subject,
		arg.IssuerCn,
		arg.IssuerOrg,
		arg.Issuer,
		arg.SanDns,
		arg.SanIp,
		arg.SanEmail,
		arg.Serial,
		arg.NotBefore,
		arg.NotAfter,
		arg.SigAlgorithm,
		arg.KeyAlgorithm,
		arg.KeyBits,
		arg.IsCa,
		arg.SelfSigned,
		arg.FingerprintSha256,
		arg.Pem,
		arg.TlsVersion,
		arg.CipherSuite,
		arg.Trusted,
		arg.Error,
	)
	return err
}

const deleteProbeTLSCertsByTarget = `-- name: DeleteProbeTLSCertsByTarget :execrows

DELETE FROM probe_tls_certs
WHERE target_id = ?
`

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later; see LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// First half of the delete-then-insert upsert (the table always holds the
// CURRENT chain of the target). Also the explicit cascade on target delete:
// the main DB does not enable the SQLite foreign_keys pragma.
func (q *Queries) DeleteProbeTLSCertsByTarget(ctx context.Context, targetID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProbeTLSCertsByTarget, targetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listProbeTLSCertsByTarget = `-- name: ListProbeTLSCertsByTarget :many
SELECT id, target_id, port, cert_index, subject_cn, subject_org, subject, issuer_cn, issuer_org, issuer,
    san_dns, san_ip, san_email, serial, not_before, not_after, sig_algorithm, key_algorithm, key_bits,
    is_ca, self_signed, fingerprint_sha256, pem, tls_version, cipher_suite, trusted, error, updated_at
FROM probe_tls_certs
WHERE target_id = ?
ORDER BY cert_index ASC
`

func (q *Queries) ListProbeTLSCertsByTarget(ctx context.Context, targetID int64) ([]ProbeTlsCert, error) {
	rows, err := q.db.QueryContext(ctx, listProbeTLSCertsByTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeTlsCert{}
	for rows.Next() {
		var i ProbeTlsCert
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Port,
			&i.CertIndex,
			&i.SubjectCn,
			&i.SubjectOrg,
			&i.Subject,
			&i.IssuerCn,
			&i.IssuerOrg,
			&i.Issuer,
			&i.SanDns,
			&i.SanIp,
			&i.SanEmail,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.SigAlgorithm,
			&i.KeyAlgorithm,
			&i.KeyBits,
			&i.IsCa,
			&i.SelfSigned,
			&i.FingerprintSha256,
			&i.Pem,
			&i.TlsVersion,
			&i.CipherSuite,
			&i.Trusted,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
