// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe_targets.sql

package db

import (
	"context"
)

const countProbeTargetsSearch = `-- name: CountProbeTargetsSearch :one
SELECT COUNT(*)
FROM probe_targets
WHERE (? = '' OR INSTR(lower(name), lower(?)) > 0 OR INSTR(lower(target), lower(?)) > 0)
`

type CountProbeTargetsSearchParams struct {
	Column1 interface{} `json:"column_1"`
	LOWER   string      `json:"LOWER"`
	LOWER_2 string      `json:"LOWER_2"`
}

func (q *Queries) CountProbeTargetsSearch(ctx context.Context, arg CountProbeTargetsSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProbeTargetsSearch, arg.Column1, arg.LOWER, arg.LOWER_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProbeTarget = `-- name: CreateProbeTarget :one


INSERT INTO probe_targets (name, module, target, interval_seconds, timeout_seconds, enabled, notes, vantage)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
`

type CreateProbeTargetParams struct {
	Name            string `json:"name"`
	Module          string `json:"module"`
	Target          string `json:"target"`
	IntervalSeconds int64  `json:"interval_seconds"`
	TimeoutSeconds  int64  `json:"timeout_seconds"`
	Enabled         int64  `json:"enabled"`
	Notes           string `json:"notes"`
	Vantage         string `json:"vantage"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// vantage (#277): the execution plan - 'center' | 'agent:{agent_id}' | 'all'
// ('all' expands to center + every agent at run time, never stored expanded).
// Not part of identity: name stays UNIQUE alone.
func (q *Queries) CreateProbeTarget(ctx context.Context, arg CreateProbeTargetParams) (ProbeTarget, error) {
	row := q.db.QueryRowContext(ctx, createProbeTarget,
		arg.Name,
		arg.Module,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.Notes,
		arg.Vantage,
	)
	var i ProbeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Module,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Notes,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vantage,
	)
	return i, err
}

const deleteProbeTarget = `-- name: DeleteProbeTarget :execrows
DELETE FROM probe_targets
WHERE id = ?
`

func (q *Queries) DeleteProbeTarget(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProbeTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProbeTarget = `-- name: GetProbeTarget :one
SELECT id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
FROM probe_targets
WHERE id = ?
`

func (q *Queries) GetProbeTarget(ctx context.Context, id int64) (ProbeTarget, error) {
	row := q.db.QueryRowContext(ctx, getProbeTarget, id)
	var i ProbeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Module,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Notes,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vantage,
	)
	return i, err
}

const getProbeTargetByName = `-- name: GetProbeTargetByName :one
SELECT id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
FROM probe_targets
WHERE name = ?
`

// Duplicate-name detection for CRUD validation (name is the metric label, so
// duplicates would make mibee_probe_* series ambiguous).
func (q *Queries) GetProbeTargetByName(ctx context.Context, name string) (ProbeTarget, error) {
	row := q.db.QueryRowContext(ctx, getProbeTargetByName, name)
	var i ProbeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Module,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Notes,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vantage,
	)
	return i, err
}

const listEnabledProbeTargets = `-- name: ListEnabledProbeTargets :many
SELECT id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
FROM probe_targets
WHERE enabled = 1
`

// The engine re-reads this every tick so CRUD changes apply without restart.
// Targets whose vantage is agent-only are filtered in the engine (Go), not
// here: the center engine runs 'center' and 'all' vantages and leaves
// 'agent:{id}' plans to the agent command channel (#277 step 2).
func (q *Queries) ListEnabledProbeTargets(ctx context.Context) ([]ProbeTarget, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledProbeTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeTarget{}
	for rows.Next() {
		var i ProbeTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Module,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.Notes,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Vantage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeTargetsSearch = `-- name: ListProbeTargetsSearch :many
SELECT id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
FROM probe_targets
WHERE (? = '' OR INSTR(lower(name), lower(?)) > 0 OR INSTR(lower(target), lower(?)) > 0)
ORDER BY id
LIMIT ? OFFSET ?
`

type ListProbeTargetsSearchParams struct {
	Column1 interface{} `json:"column_1"`
	LOWER   string      `json:"LOWER"`
	LOWER_2 string      `json:"LOWER_2"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

// Optional case-insensitive substring search over name + target, using the
// same empty-string short-circuit idiom as ListScanTasksSearch (INSTR so
// search terms need no escaping). CountProbeTargetsSearch MUST mirror this
// WHERE.
func (q *Queries) ListProbeTargetsSearch(ctx context.Context, arg ListProbeTargetsSearchParams) ([]ProbeTarget, error) {
	rows, err := q.db.QueryContext(ctx, listProbeTargetsSearch,
		arg.Column1,
		arg.LOWER,
		arg.LOWER_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeTarget{}
	for rows.Next() {
		var i ProbeTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Module,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.Notes,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Vantage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProbeTargetLastResult = `-- name: SetProbeTargetLastResult :exec
UPDATE probe_targets
SET last_run_at = ?, last_status = ?, last_latency_ms = ?, last_error = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetProbeTargetLastResultParams struct {
	LastRunAt     string  `json:"last_run_at"`
	LastStatus    string  `json:"last_status"`
	LastLatencyMs float64 `json:"last_latency_ms"`
	LastError     string  `json:"last_error"`
	ID            int64   `json:"id"`
}

// Denormalizes the newest outcome for the list view. last_run_at is an
// RFC3339 UTC string (modernc time.Time breaks SQLite date()); it is also
// the next-due anchor used by the engine on restart.
func (q *Queries) SetProbeTargetLastResult(ctx context.Context, arg SetProbeTargetLastResultParams) error {
	_, err := q.db.ExecContext(ctx, setProbeTargetLastResult,
		arg.LastRunAt,
		arg.LastStatus,
		arg.LastLatencyMs,
		arg.LastError,
		arg.ID,
	)
	return err
}

const toggleProbeTargetEnabled = `-- name: ToggleProbeTargetEnabled :exec
UPDATE probe_targets
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ToggleProbeTargetEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) ToggleProbeTargetEnabled(ctx context.Context, arg ToggleProbeTargetEnabledParams) error {
	_, err := q.db.ExecContext(ctx, toggleProbeTargetEnabled, arg.Enabled, arg.ID)
	return err
}

const updateProbeTarget = `-- name: UpdateProbeTarget :one
UPDATE probe_targets
SET name = ?, module = ?, target = ?, interval_seconds = ?, timeout_seconds = ?,
    enabled = ?, notes = ?, vantage = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, module, target, interval_seconds, timeout_seconds, enabled, notes, last_run_at, last_status, last_latency_ms, last_error, created_at, updated_at, vantage
`

type UpdateProbeTargetParams struct {
	Name            string `json:"name"`
	Module          string `json:"module"`
	Target          string `json:"target"`
	IntervalSeconds int64  `json:"interval_seconds"`
	TimeoutSeconds  int64  `json:"timeout_seconds"`
	Enabled         int64  `json:"enabled"`
	Notes           string `json:"notes"`
	Vantage         string `json:"vantage"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateProbeTarget(ctx context.Context, arg UpdateProbeTargetParams) (ProbeTarget, error) {
	row := q.db.QueryRowContext(ctx, updateProbeTarget,
		arg.Name,
		arg.Module,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.Notes,
		arg.Vantage,
		arg.ID,
	)
	var i ProbeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Module,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Notes,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vantage,
	)
	return i, err
}
