// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_tasks.sql

package db

import (
	"context"
	"time"
)

const countScanTasks = `-- name: CountScanTasks :one
SELECT COUNT(*)
FROM scan_tasks
`

func (q *Queries) CountScanTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScanTasksSearch = `-- name: CountScanTasksSearch :one
SELECT COUNT(*)
FROM scan_tasks
WHERE (? = '' OR INSTR(lower(name), lower(?)) > 0 OR INSTR(lower(targets), lower(?)) > 0)
`

type CountScanTasksSearchParams struct {
	Column1 interface{} `json:"column_1"`
	LOWER   string      `json:"LOWER"`
	LOWER_2 string      `json:"LOWER_2"`
}

// Mirrors ListScanTasksSearch's WHERE clause so the pagination total reflects
// the active search (not the unfiltered row count).
func (q *Queries) CountScanTasksSearch(ctx context.Context, arg CountScanTasksSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanTasksSearch, arg.Column1, arg.LOWER, arg.LOWER_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanTask = `-- name: CreateScanTask :one

INSERT INTO scan_tasks (name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)
RETURNING id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
`

type CreateScanTaskParams struct {
	Name            string `json:"name"`
	Targets         string `json:"targets"`
	CronExpr        string `json:"cron_expr"`
	PipelineConfig  string `json:"pipeline_config"`
	GlobalLabels    string `json:"global_labels"`
	Timeout         int64  `json:"timeout"`
	ConcurrentHosts int64  `json:"concurrent_hosts"`
	CredentialID    *int64 `json:"credential_id"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateScanTask(ctx context.Context, arg CreateScanTaskParams) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, createScanTask,
		arg.Name,
		arg.Targets,
		arg.CronExpr,
		arg.PipelineConfig,
		arg.GlobalLabels,
		arg.Timeout,
		arg.ConcurrentHosts,
		arg.CredentialID,
	)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.CredentialID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScanTask = `-- name: DeleteScanTask :execrows
DELETE FROM scan_tasks
WHERE id = ?
`

func (q *Queries) DeleteScanTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScanTask = `-- name: GetScanTask :one
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
WHERE id = ?
`

func (q *Queries) GetScanTask(ctx context.Context, id int64) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, getScanTask, id)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.CredentialID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledScanTasks = `-- name: ListEnabledScanTasks :many
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
WHERE enabled = 1
`

func (q *Queries) ListEnabledScanTasks(ctx context.Context) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledScanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Targets,
			&i.CronExpr,
			&i.PipelineConfig,
			&i.GlobalLabels,
			&i.Timeout,
			&i.ConcurrentHosts,
			&i.CredentialID,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastRunStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanTasks = `-- name: ListScanTasks :many
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
ORDER BY id
LIMIT ? OFFSET ?
`

type ListScanTasksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListScanTasks(ctx context.Context, arg ListScanTasksParams) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listScanTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Targets,
			&i.CronExpr,
			&i.PipelineConfig,
			&i.GlobalLabels,
			&i.Timeout,
			&i.ConcurrentHosts,
			&i.CredentialID,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastRunStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanTasksSearch = `-- name: ListScanTasksSearch :many
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
WHERE (? = '' OR INSTR(lower(name), lower(?)) > 0 OR INSTR(lower(targets), lower(?)) > 0)
ORDER BY id
LIMIT ? OFFSET ?
`

type ListScanTasksSearchParams struct {
	Column1 interface{} `json:"column_1"`
	LOWER   string      `json:"LOWER"`
	LOWER_2 string      `json:"LOWER_2"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

// Optional case-insensitive substring search over name + targets. The first
// param is the raw search term; when it is ” the (? = ”) short-circuits to
// TRUE so this behaves like ListScanTasks (no filter). INSTR() is used instead
// of LIKE so the search term needs no escaping (literal %/_ are not wildcards)
// and we pass the same value to both columns + the empty-check.
// CountScanTasksSearch below MUST use the same WHERE clause so totals match.
func (q *Queries) ListScanTasksSearch(ctx context.Context, arg ListScanTasksSearchParams) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listScanTasksSearch,
		arg.Column1,
		arg.LOWER,
		arg.LOWER_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Targets,
			&i.CronExpr,
			&i.PipelineConfig,
			&i.GlobalLabels,
			&i.Timeout,
			&i.ConcurrentHosts,
			&i.CredentialID,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastRunStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleScanTaskEnabled = `-- name: ToggleScanTaskEnabled :exec
UPDATE scan_tasks
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ToggleScanTaskEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) ToggleScanTaskEnabled(ctx context.Context, arg ToggleScanTaskEnabledParams) error {
	_, err := q.db.ExecContext(ctx, toggleScanTaskEnabled, arg.Enabled, arg.ID)
	return err
}

const updateScanTask = `-- name: UpdateScanTask :one
UPDATE scan_tasks
SET name = ?, targets = ?, cron_expr = ?, pipeline_config = ?, global_labels = ?,
    timeout = ?, concurrent_hosts = ?, credential_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, credential_id, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
`

type UpdateScanTaskParams struct {
	Name            string `json:"name"`
	Targets         string `json:"targets"`
	CronExpr        string `json:"cron_expr"`
	PipelineConfig  string `json:"pipeline_config"`
	GlobalLabels    string `json:"global_labels"`
	Timeout         int64  `json:"timeout"`
	ConcurrentHosts int64  `json:"concurrent_hosts"`
	CredentialID    *int64 `json:"credential_id"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateScanTask(ctx context.Context, arg UpdateScanTaskParams) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, updateScanTask,
		arg.Name,
		arg.Targets,
		arg.CronExpr,
		arg.PipelineConfig,
		arg.GlobalLabels,
		arg.Timeout,
		arg.ConcurrentHosts,
		arg.CredentialID,
		arg.ID,
	)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.CredentialID,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScanTaskStatus = `-- name: UpdateScanTaskStatus :exec
UPDATE scan_tasks
SET last_run_at = ?, next_run_at = ?, last_run_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScanTaskStatusParams struct {
	LastRunAt     *time.Time `json:"last_run_at"`
	NextRunAt     *time.Time `json:"next_run_at"`
	LastRunStatus *string    `json:"last_run_status"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateScanTaskStatus(ctx context.Context, arg UpdateScanTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanTaskStatus,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.LastRunStatus,
		arg.ID,
	)
	return err
}
