// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_snapshots.sql

package db

import (
	"context"
	"time"
)

const deleteScanSnapshotsForNetwork = `-- name: DeleteScanSnapshotsForNetwork :execrows
.ip;

DELETE FROM scan_snapshots WHERE network_id
`

// Remove all snapshots for a network (e.g. when a network is deleted).
func (q *Queries) DeleteScanSnapshotsForNetwork(ctx context.Context, networkID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanSnapshotsForNetwork, networkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementSnapshotMisses = `-- name: IncrementSnapshotMisses :execrows

SELECT s.id, s.network_id, s.task_id, s.ip, s.mac, s.miss_count, s.last_seen_at,
       d.id AS device_id, d.name, d.type, d.status
FROM scan_snapshots s
JOIN devices d ON d.ip_address = s.ip AND (d.network_id = s.network_id OR d.network_id IS NULL)
WHERE s.network_id = ?
  AND s.miss_count >= ?
  AND d.status = 'online'
ORDER BY
`

type IncrementSnapshotMissesParams struct {
	NetworkID int64 `json:"network_id"`
	MissCount int64 `json:"miss_count"`
}

// Bump miss_count for every snapshot on this network whose ip is NOT in the
// seen-set (the alive IPs from the scan that just ran). This is the set
// difference that drives device_lost detection. The placeholders (?, ?, ...)
// are expanded inline by the caller (not via sqlc params) because IN-lists
// can't be parameterized directly in sqlite — built in Go as a quoted literal
// list of IPs. Never interpolates user data directly: the IPs are the
// scan's own output, validated as IPs before use.
// NOTE: this query is hand-written SQL executed via dbConn.Exec (not sqlc)
// because of the dynamic IN-list. Kept here for documentation/discoverability.
// Snapshots whose miss_count has crossed the lost threshold, joined to devices
// to filter to currently-online ones (a device already offline was already
// declared lost — don't re-emit). The grace period (miss_count >= threshold)
// prevents single-scan jitter from flapping a device offline.
func (q *Queries) IncrementSnapshotMisses(ctx context.Context, arg IncrementSnapshotMissesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementSnapshotMisses, arg.NetworkID, arg.MissCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertScanSnapshot = `-- name: UpsertScanSnapshot :exec
INSERT INTO scan_snapshots (network_id, task_id, ip, mac, miss_count, last_seen_at)
VALUES (?, ?, ?, ?, 0, ?)
ON CONFLICT(network_id, ip) DO UPDATE SET
    task_id = excluded.task_id,
    mac = CASE WHEN excluded.mac != '' THEN excluded.mac ELSE scan_snapshots.mac END,
    miss_count = 0,
    last_seen_at = excluded.last_seen_at
`

type UpsertScanSnapshotParams struct {
	NetworkID  int64     `json:"network_id"`
	TaskID     *int64    `json:"task_id"`
	Ip         string    `json:"ip"`
	Mac        string    `json:"mac"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

// Mark an IP as seen in this scan: insert or reset miss_count to 0 + refresh
// last_seen_at. Called for every alive host in a scan.
func (q *Queries) UpsertScanSnapshot(ctx context.Context, arg UpsertScanSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertScanSnapshot,
		arg.NetworkID,
		arg.TaskID,
		arg.Ip,
		arg.Mac,
		arg.LastSeenAt,
	)
	return err
}
