// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scan_tasks.sql

package db

import (
	"context"
	"time"
)

const countScanTasks = `-- name: CountScanTasks :one
SELECT COUNT(*)
FROM scan_tasks
`

func (q *Queries) CountScanTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanTask = `-- name: CreateScanTask :one
INSERT INTO scan_tasks (name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, 1)
RETURNING id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
`

type CreateScanTaskParams struct {
	Name            string `json:"name"`
	Targets         string `json:"targets"`
	CronExpr        string `json:"cron_expr"`
	PipelineConfig  string `json:"pipeline_config"`
	GlobalLabels    string `json:"global_labels"`
	Timeout         int64  `json:"timeout"`
	ConcurrentHosts int64  `json:"concurrent_hosts"`
}

func (q *Queries) CreateScanTask(ctx context.Context, arg CreateScanTaskParams) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, createScanTask,
		arg.Name,
		arg.Targets,
		arg.CronExpr,
		arg.PipelineConfig,
		arg.GlobalLabels,
		arg.Timeout,
		arg.ConcurrentHosts,
	)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScanTask = `-- name: DeleteScanTask :execrows
DELETE FROM scan_tasks
WHERE id = ?
`

func (q *Queries) DeleteScanTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScanTask = `-- name: GetScanTask :one
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
WHERE id = ?
`

func (q *Queries) GetScanTask(ctx context.Context, id int64) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, getScanTask, id)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledScanTasks = `-- name: ListEnabledScanTasks :many
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
WHERE enabled = 1
`

func (q *Queries) ListEnabledScanTasks(ctx context.Context) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledScanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Targets,
			&i.CronExpr,
			&i.PipelineConfig,
			&i.GlobalLabels,
			&i.Timeout,
			&i.ConcurrentHosts,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastRunStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanTasks = `-- name: ListScanTasks :many
SELECT id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
FROM scan_tasks
ORDER BY id
LIMIT ? OFFSET ?
`

type ListScanTasksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListScanTasks(ctx context.Context, arg ListScanTasksParams) ([]ScanTask, error) {
	rows, err := q.db.QueryContext(ctx, listScanTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTask{}
	for rows.Next() {
		var i ScanTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Targets,
			&i.CronExpr,
			&i.PipelineConfig,
			&i.GlobalLabels,
			&i.Timeout,
			&i.ConcurrentHosts,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.LastRunStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleScanTaskEnabled = `-- name: ToggleScanTaskEnabled :exec
UPDATE scan_tasks
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ToggleScanTaskEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) ToggleScanTaskEnabled(ctx context.Context, arg ToggleScanTaskEnabledParams) error {
	_, err := q.db.ExecContext(ctx, toggleScanTaskEnabled, arg.Enabled, arg.ID)
	return err
}

const updateScanTask = `-- name: UpdateScanTask :one
UPDATE scan_tasks
SET name = ?, targets = ?, cron_expr = ?, pipeline_config = ?, global_labels = ?,
    timeout = ?, concurrent_hosts = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, targets, cron_expr, pipeline_config, global_labels, timeout, concurrent_hosts, enabled, last_run_at, next_run_at, last_run_status, created_at, updated_at
`

type UpdateScanTaskParams struct {
	Name            string `json:"name"`
	Targets         string `json:"targets"`
	CronExpr        string `json:"cron_expr"`
	PipelineConfig  string `json:"pipeline_config"`
	GlobalLabels    string `json:"global_labels"`
	Timeout         int64  `json:"timeout"`
	ConcurrentHosts int64  `json:"concurrent_hosts"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateScanTask(ctx context.Context, arg UpdateScanTaskParams) (ScanTask, error) {
	row := q.db.QueryRowContext(ctx, updateScanTask,
		arg.Name,
		arg.Targets,
		arg.CronExpr,
		arg.PipelineConfig,
		arg.GlobalLabels,
		arg.Timeout,
		arg.ConcurrentHosts,
		arg.ID,
	)
	var i ScanTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Targets,
		&i.CronExpr,
		&i.PipelineConfig,
		&i.GlobalLabels,
		&i.Timeout,
		&i.ConcurrentHosts,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.LastRunStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScanTaskStatus = `-- name: UpdateScanTaskStatus :exec
UPDATE scan_tasks
SET last_run_at = ?, next_run_at = ?, last_run_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScanTaskStatusParams struct {
	LastRunAt     *time.Time `json:"last_run_at"`
	NextRunAt     *time.Time `json:"next_run_at"`
	LastRunStatus *string    `json:"last_run_status"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateScanTaskStatus(ctx context.Context, arg UpdateScanTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanTaskStatus,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.LastRunStatus,
		arg.ID,
	)
	return err
}
