// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scan_snapshots.sql

package db

import (
	"context"
	"time"
)

const deleteScanSnapshotsForNetwork = `-- name: DeleteScanSnapshotsForNetwork :execrows
DELETE FROM scan_snapshots WHERE network_id = ?
`

// Remove all snapshots for a network (e.g. when a network is deleted).
func (q *Queries) DeleteScanSnapshotsForNetwork(ctx context.Context, networkID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScanSnapshotsForNetwork, networkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementSnapshotMiss = `-- name: IncrementSnapshotMiss :exec
UPDATE scan_snapshots SET miss_count = miss_count + 1 WHERE id = ?
`

// Bump miss_count for ONE snapshot (by id). Called per missing device from Go
// after computing the set difference.
func (q *Queries) IncrementSnapshotMiss(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementSnapshotMiss, id)
	return err
}

const listLostSnapshots = `-- name: ListLostSnapshots :many
SELECT
    s.id AS id, s.network_id AS network_id, s.task_id AS task_id,
    s.ip AS ip, s.mac AS mac, s.miss_count AS miss_count, s.last_seen_at AS last_seen_at,
    d.id AS device_id, d.name AS device_name, d.type AS device_type, d.status AS device_status
FROM scan_snapshots s
JOIN devices d ON d.ip_address = s.ip AND (d.network_id = s.network_id OR d.network_id IS NULL)
WHERE s.network_id = ?
  AND s.miss_count >= ?
  AND d.status = 'online'
`

type ListLostSnapshotsParams struct {
	NetworkID int64 `json:"network_id"`
	MissCount int64 `json:"miss_count"`
}

type ListLostSnapshotsRow struct {
	ID           int64     `json:"id"`
	NetworkID    int64     `json:"network_id"`
	TaskID       *int64    `json:"task_id"`
	Ip           string    `json:"ip"`
	Mac          string    `json:"mac"`
	MissCount    int64     `json:"miss_count"`
	LastSeenAt   time.Time `json:"last_seen_at"`
	DeviceID     int64     `json:"device_id"`
	DeviceName   string    `json:"device_name"`
	DeviceType   string    `json:"device_type"`
	DeviceStatus string    `json:"device_status"`
}

// Snapshots whose miss_count crossed the lost threshold, joined to devices
// to filter to currently-online ones (a device already offline was already
// declared lost, so do not re-emit). The grace period (miss_count >= threshold)
// prevents single-scan jitter from flapping a device offline.
func (q *Queries) ListLostSnapshots(ctx context.Context, arg ListLostSnapshotsParams) ([]ListLostSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLostSnapshots, arg.NetworkID, arg.MissCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLostSnapshotsRow{}
	for rows.Next() {
		var i ListLostSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.TaskID,
			&i.Ip,
			&i.Mac,
			&i.MissCount,
			&i.LastSeenAt,
			&i.DeviceID,
			&i.DeviceName,
			&i.DeviceType,
			&i.DeviceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsForNetwork = `-- name: ListSnapshotsForNetwork :many
SELECT id, network_id, task_id, ip, mac, miss_count, last_seen_at
FROM scan_snapshots
WHERE network_id = ?
`

// All snapshots for a network (the known alive set). Used to compute the set
// difference: which of these did NOT appear in the current scan, then
// increment their miss_count (done in Go since the IN-list is dynamic).
func (q *Queries) ListSnapshotsForNetwork(ctx context.Context, networkID int64) ([]ScanSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanSnapshot{}
	for rows.Next() {
		var i ScanSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.TaskID,
			&i.Ip,
			&i.Mac,
			&i.MissCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScanSnapshot = `-- name: UpsertScanSnapshot :exec

INSERT INTO scan_snapshots (network_id, task_id, ip, mac, miss_count, last_seen_at)
VALUES (?, ?, ?, ?, 0, ?)
ON CONFLICT(network_id, ip) DO UPDATE SET
    task_id = excluded.task_id,
    mac = CASE WHEN excluded.mac != '' THEN excluded.mac ELSE scan_snapshots.mac END,
    miss_count = 0,
    last_seen_at = excluded.last_seen_at
`

type UpsertScanSnapshotParams struct {
	NetworkID  int64     `json:"network_id"`
	TaskID     *int64    `json:"task_id"`
	Ip         string    `json:"ip"`
	Mac        string    `json:"mac"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// Mark an IP as seen in this scan: insert or reset miss_count to 0 + refresh
// last_seen_at. Called for every alive host in a scan.
func (q *Queries) UpsertScanSnapshot(ctx context.Context, arg UpsertScanSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertScanSnapshot,
		arg.NetworkID,
		arg.TaskID,
		arg.Ip,
		arg.Mac,
		arg.LastSeenAt,
	)
	return err
}
