// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan_task_runs.sql

package db

import (
	"context"
	"time"
)

const countScanTaskRuns = `-- name: CountScanTaskRuns :one
SELECT COUNT(*)
FROM scan_task_runs
WHERE (? = 0 OR task_id = ?)
`

type CountScanTaskRunsParams struct {
	Column1 interface{} `json:"column_1"`
	TaskID  int64       `json:"task_id"`
}

func (q *Queries) CountScanTaskRuns(ctx context.Context, arg CountScanTaskRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScanTaskRuns, arg.Column1, arg.TaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanTaskRun = `-- name: CreateScanTaskRun :one
INSERT INTO scan_task_runs (task_id, status, total_hosts, alive_hosts, new_hosts, updated_hosts, duration_ms, error_message, started_at)
VALUES (?, 'running', 0, 0, 0, 0, 0, '', ?)
RETURNING id, task_id, status, total_hosts, alive_hosts, new_hosts, updated_hosts, duration_ms, error_message, started_at, finished_at, created_at
`

type CreateScanTaskRunParams struct {
	TaskID    int64      `json:"task_id"`
	StartedAt *time.Time `json:"started_at"`
}

func (q *Queries) CreateScanTaskRun(ctx context.Context, arg CreateScanTaskRunParams) (ScanTaskRun, error) {
	row := q.db.QueryRowContext(ctx, createScanTaskRun, arg.TaskID, arg.StartedAt)
	var i ScanTaskRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.TotalHosts,
		&i.AliveHosts,
		&i.NewHosts,
		&i.UpdatedHosts,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRun = `-- name: GetLatestRun :one
SELECT id, task_id, status, total_hosts, alive_hosts, new_hosts, updated_hosts, duration_ms, error_message, started_at, finished_at, created_at
FROM scan_task_runs
WHERE task_id = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestRun(ctx context.Context, taskID int64) (ScanTaskRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestRun, taskID)
	var i ScanTaskRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.TotalHosts,
		&i.AliveHosts,
		&i.NewHosts,
		&i.UpdatedHosts,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScanTaskRun = `-- name: GetScanTaskRun :one
SELECT id, task_id, status, total_hosts, alive_hosts, new_hosts, updated_hosts, duration_ms, error_message, started_at, finished_at, created_at
FROM scan_task_runs
WHERE id = ?
`

func (q *Queries) GetScanTaskRun(ctx context.Context, id int64) (ScanTaskRun, error) {
	row := q.db.QueryRowContext(ctx, getScanTaskRun, id)
	var i ScanTaskRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.TotalHosts,
		&i.AliveHosts,
		&i.NewHosts,
		&i.UpdatedHosts,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScanTaskRuns = `-- name: ListScanTaskRuns :many
SELECT id, task_id, status, total_hosts, alive_hosts, new_hosts, updated_hosts, duration_ms, error_message, started_at, finished_at, created_at
FROM scan_task_runs
WHERE (? = 0 OR task_id = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListScanTaskRunsParams struct {
	Column1 interface{} `json:"column_1"`
	TaskID  int64       `json:"task_id"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) ListScanTaskRuns(ctx context.Context, arg ListScanTaskRunsParams) ([]ScanTaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listScanTaskRuns,
		arg.Column1,
		arg.TaskID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanTaskRun{}
	for rows.Next() {
		var i ScanTaskRun
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Status,
			&i.TotalHosts,
			&i.AliveHosts,
			&i.NewHosts,
			&i.UpdatedHosts,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanTaskRun = `-- name: UpdateScanTaskRun :exec
UPDATE scan_task_runs
SET status = ?, total_hosts = ?, alive_hosts = ?, new_hosts = ?, updated_hosts = ?,
    duration_ms = ?, error_message = ?, finished_at = ?
WHERE id = ?
`

type UpdateScanTaskRunParams struct {
	Status       string     `json:"status"`
	TotalHosts   int64      `json:"total_hosts"`
	AliveHosts   int64      `json:"alive_hosts"`
	NewHosts     int64      `json:"new_hosts"`
	UpdatedHosts int64      `json:"updated_hosts"`
	DurationMs   int64      `json:"duration_ms"`
	ErrorMessage string     `json:"error_message"`
	FinishedAt   *time.Time `json:"finished_at"`
	ID           int64      `json:"id"`
}

func (q *Queries) UpdateScanTaskRun(ctx context.Context, arg UpdateScanTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScanTaskRun,
		arg.Status,
		arg.TotalHosts,
		arg.AliveHosts,
		arg.NewHosts,
		arg.UpdatedHosts,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
