// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: service_evidence.sql

package db

import (
	"context"
	"time"
)

const deleteServiceEvidenceOlderThanBatched = `-- name: DeleteServiceEvidenceOlderThanBatched :execrows

DELETE FROM service_evidence
WHERE rowid IN (
    SELECT rowid FROM service_evidence WHERE service_evidence.observed_at < ? LIMIT ?
)
`

type DeleteServiceEvidenceOlderThanBatchedParams struct {
	ObservedAt time.Time `json:"observed_at"`
	Limit      int64     `json:"limit"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// Retention sweep (batched) for service_evidence. Only written when
// scanner.persist_raw_evidence is on (default off), but can still accumulate
// heavily: each raw probe observation is a row.
func (q *Queries) DeleteServiceEvidenceOlderThanBatched(ctx context.Context, arg DeleteServiceEvidenceOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServiceEvidenceOlderThanBatched, arg.ObservedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
