// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_evidence.sql

package db

import (
	"context"
	"time"
)

const deleteServiceEvidenceOlderThanBatched = `-- name: DeleteServiceEvidenceOlderThanBatched :execrows

DELETE FROM service_evidence
WHERE rowid IN (
    SELECT rowid FROM service_evidence WHERE service_evidence.observed_at < ? LIMIT ?
)
`

type DeleteServiceEvidenceOlderThanBatchedParams struct {
	ObservedAt time.Time `json:"observed_at"`
	Limit      int64     `json:"limit"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
// Retention sweep (batched) for service_evidence. Only written when
// scanner.persist_raw_evidence is on (default off), but can still accumulate
// heavily: each raw probe observation is a row.
func (q *Queries) DeleteServiceEvidenceOlderThanBatched(ctx context.Context, arg DeleteServiceEvidenceOlderThanBatchedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServiceEvidenceOlderThanBatched, arg.ObservedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertServiceEvidence = `-- name: InsertServiceEvidence :exec
INSERT INTO service_evidence (ip, device_uuid, source, kind, port, protocol, raw_data, confidence, observed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS TEXT))
`

type InsertServiceEvidenceParams struct {
	Ip         string  `json:"ip"`
	DeviceUuid string  `json:"device_uuid"`
	Source     string  `json:"source"`
	Kind       string  `json:"kind"`
	Port       int64   `json:"port"`
	Protocol   string  `json:"protocol"`
	RawData    string  `json:"raw_data"`
	Confidence float64 `json:"confidence"`
	Column9    string  `json:"column_9"`
}

// One raw evidence row (scannerv2/store RecordEvidence, #269: moved to
// sqlc so CI sqlc-verify guards the schema binding). observed_at is bound
// as RFC3339 text by the caller (scannerv2.DBTime; NEVER time.Time, whose
// String() form breaks SQLite date(), see #257). The CAST names the bind as
// text; sqlc names positional cast params ColumnN.
func (q *Queries) InsertServiceEvidence(ctx context.Context, arg InsertServiceEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceEvidence,
		arg.Ip,
		arg.DeviceUuid,
		arg.Source,
		arg.Kind,
		arg.Port,
		arg.Protocol,
		arg.RawData,
		arg.Confidence,
		arg.Column9,
	)
	return err
}
