// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subnets.sql

package db

import (
	"context"
	"time"
)

const getSubnetByCIDR = `-- name: GetSubnetByCIDR :one
SELECT id, network_id, cidr, vlan_id, gateway, metadata, first_seen, last_seen FROM subnets WHERE network_id = ? AND cidr = ?
`

type GetSubnetByCIDRParams struct {
	NetworkID int64  `json:"network_id"`
	Cidr      string `json:"cidr"`
}

// Look up a subnet row by its (network_id, cidr) to decide insert-vs-update.
func (q *Queries) GetSubnetByCIDR(ctx context.Context, arg GetSubnetByCIDRParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByCIDR, arg.NetworkID, arg.Cidr)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.Cidr,
		&i.VlanID,
		&i.Gateway,
		&i.Metadata,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, network_id, cidr, vlan_id, gateway, metadata, first_seen, last_seen FROM subnets
WHERE (? <= 0 OR network_id = ?)
ORDER BY cidr
`

type ListSubnetsParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID int64       `json:"network_id"`
}

// All subnets observed on a network. network_id <= 0 = all networks.
func (q *Queries) ListSubnets(ctx context.Context, arg ListSubnetsParams) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnets, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subnet{}
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.Cidr,
			&i.VlanID,
			&i.Gateway,
			&i.Metadata,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubnetLastSeen = `-- name: UpdateSubnetLastSeen :execrows
UPDATE subnets SET last_seen = ?
WHERE network_id = ? AND cidr = ?
`

type UpdateSubnetLastSeenParams struct {
	LastSeen  *time.Time `json:"last_seen"`
	NetworkID int64      `json:"network_id"`
	Cidr      string     `json:"cidr"`
}

// Refresh last_seen for a subnet identified by (network_id, cidr).
func (q *Queries) UpdateSubnetLastSeen(ctx context.Context, arg UpdateSubnetLastSeenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubnetLastSeen, arg.LastSeen, arg.NetworkID, arg.Cidr)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSubnet = `-- name: UpsertSubnet :exec

INSERT INTO subnets (network_id, cidr, vlan_id, gateway, metadata, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertSubnetParams struct {
	NetworkID int64      `json:"network_id"`
	Cidr      string     `json:"cidr"`
	VlanID    *int64     `json:"vlan_id"`
	Gateway   *string    `json:"gateway"`
	Metadata  string     `json:"metadata"`
	FirstSeen *time.Time `json:"first_seen"`
	LastSeen  *time.Time `json:"last_seen"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. See LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// Insert or refresh a subnet observed during a scan. There is no natural UNIQUE
// on (network_id, cidr) in the base schema, so the conflict target is a soft
// match: the caller first checks existence then inserts/updates. This query is
// the insert path; use UpdateSubnetLastSeen to refresh an existing row.
func (q *Queries) UpsertSubnet(ctx context.Context, arg UpsertSubnetParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubnet,
		arg.NetworkID,
		arg.Cidr,
		arg.VlanID,
		arg.Gateway,
		arg.Metadata,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
