// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: topology_edges.sql

package db

import (
	"context"
	"time"
)

const deleteStaleTopologyEdges = `-- name: DeleteStaleTopologyEdges :execrows
d;

DELETE FROM topology_edges
WHERE id IN (
    SELECT sub.id FROM topology_edges AS sub WHERE sub.last_seen < ? LIMIT ?
`

type DeleteStaleTopologyEdgesParams struct {
	LastSeen *time.Time `json:"last_seen"`
	Limit    int64      `json:"limit"`
}

// Retention sweep: remove edges whose last_seen is older than the cutoff.
func (q *Queries) DeleteStaleTopologyEdges(ctx context.Context, arg DeleteStaleTopologyEdgesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleTopologyEdges, arg.LastSeen, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTopologyEdgesByNetwork = `-- name: ListTopologyEdgesByNetwork :many

SELECT DISTINCT
    te.id, te.from_device_id, te.to_device_id, te.edge_type, te.via_protocol,
    te.confidence, te.metadata, te.first_seen, te.last_seen
FROM topology_edges te
JOIN devices df ON te.from_device_id = df.id
JOIN devices dt ON te.to_device_id = dt.id
WHERE (? <= 0 OR df.network_id = ? OR dt.network_id = ?)
ORDER BY te.edge_type, te.confidence DESC, te.
`

type ListTopologyEdgesByNetworkParams struct {
	Column1     interface{} `json:"column_1"`
	NetworkID   *int64      `json:"network_id"`
	NetworkID_2 *int64      `json:"network_id_2"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. See LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// All device↔device edges for one network's devices (used by the topology
// graph). Filters by either endpoint belonging to the network so an edge
// spanning a known + an external device still appears. network_id <= 0 = all.
func (q *Queries) ListTopologyEdgesByNetwork(ctx context.Context, arg ListTopologyEdgesByNetworkParams) ([]TopologyEdge, error) {
	rows, err := q.db.QueryContext(ctx, listTopologyEdgesByNetwork, arg.Column1, arg.NetworkID, arg.NetworkID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopologyEdge{}
	for rows.Next() {
		var i TopologyEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromDeviceID,
			&i.ToDeviceID,
			&i.EdgeType,
			&i.ViaProtocol,
			&i.Confidence,
			&i.Metadata,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
