// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package db

import (
	"context"
)

const consumeBackupCode = `-- name: ConsumeBackupCode :one
UPDATE user_totp
SET backup_codes = ?
WHERE user_id = ?
RETURNING id, user_id, secret, verified, backup_codes, enabled, created_at, updated_at
`

type ConsumeBackupCodeParams struct {
	BackupCodes string `json:"backup_codes"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (UserTotp, error) {
	row := q.db.QueryRowContext(ctx, consumeBackupCode, arg.BackupCodes, arg.UserID)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTOTP = `-- name: DeleteTOTP :exec
DELETE FROM user_totp WHERE user_id = ?
`

func (q *Queries) DeleteTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTOTP, userID)
	return err
}

const getTOTPByUserID = `-- name: GetTOTPByUserID :one
SELECT id, user_id, secret, verified, backup_codes, enabled, created_at, updated_at FROM user_totp WHERE user_id = ?
`

func (q *Queries) GetTOTPByUserID(ctx context.Context, userID int64) (UserTotp, error) {
	row := q.db.QueryRowContext(ctx, getTOTPByUserID, userID)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTOTPSecret = `-- name: SetTOTPSecret :one
INSERT INTO user_totp (user_id, secret, backup_codes)
VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    secret = excluded.secret,
    backup_codes = excluded.backup_codes,
    verified = 0,
    enabled = 0,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, secret, verified, backup_codes, enabled, created_at, updated_at
`

type SetTOTPSecretParams struct {
	UserID      int64  `json:"user_id"`
	Secret      string `json:"secret"`
	BackupCodes string `json:"backup_codes"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) (UserTotp, error) {
	row := q.db.QueryRowContext(ctx, setTOTPSecret, arg.UserID, arg.Secret, arg.BackupCodes)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTOTPEnabled = `-- name: UpdateTOTPEnabled :one
UPDATE user_totp
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
RETURNING id, user_id, secret, verified, backup_codes, enabled, created_at, updated_at
`

type UpdateTOTPEnabledParams struct {
	Enabled int64 `json:"enabled"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) UpdateTOTPEnabled(ctx context.Context, arg UpdateTOTPEnabledParams) (UserTotp, error) {
	row := q.db.QueryRowContext(ctx, updateTOTPEnabled, arg.Enabled, arg.UserID)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTOTPVerified = `-- name: UpdateTOTPVerified :one
UPDATE user_totp
SET verified = ?, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
RETURNING id, user_id, secret, verified, backup_codes, enabled, created_at, updated_at
`

type UpdateTOTPVerifiedParams struct {
	Verified int64 `json:"verified"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) UpdateTOTPVerified(ctx context.Context, arg UpdateTOTPVerifiedParams) (UserTotp, error) {
	row := q.db.QueryRowContext(ctx, updateTOTPVerified, arg.Verified, arg.UserID)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
