// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, email, password_hash, role, failed_login_attempts, locked_until, must_change_password)
VALUES (?, ?, ?, ?, 0, NULL, ?)
RETURNING id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
`

type CreateUserParams struct {
	Username           string `json:"username"`
	Email              string `json:"email"`
	PasswordHash       string `json:"password_hash"`
	Role               string `json:"role"`
	MustChangePassword bool   `json:"must_change_password"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. You may use, modify, and redistribute it under
// those terms; see LICENSE for the full text. A commercial license is available
// for use cases the AGPL does not accommodate; see LICENSE-COMMERCIAL.md.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
FROM users
ORDER BY id
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.PasswordChangedAt,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetLoginAttempts, id)
	return err
}

const setMustChangePassword = `-- name: SetMustChangePassword :exec
UPDATE users
SET must_change_password = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetMustChangePasswordParams struct {
	MustChangePassword bool  `json:"must_change_password"`
	ID                 int64 `json:"id"`
}

func (q *Queries) SetMustChangePassword(ctx context.Context, arg SetMustChangePasswordParams) error {
	_, err := q.db.ExecContext(ctx, setMustChangePassword, arg.MustChangePassword, arg.ID)
	return err
}

const updateLoginAttempts = `-- name: UpdateLoginAttempts :exec
UPDATE users
SET failed_login_attempts = ?, locked_until = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLoginAttemptsParams struct {
	FailedLoginAttempts int64      `json:"failed_login_attempts"`
	LockedUntil         *time.Time `json:"locked_until"`
	ID                  int64      `json:"id"`
}

func (q *Queries) UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginAttempts, arg.FailedLoginAttempts, arg.LockedUntil, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = ?, email = ?, password_hash = ?, role = ?, failed_login_attempts = ?, locked_until = ?, must_change_password = ?, password_changed_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, email, password_hash, role, created_at, updated_at, failed_login_attempts, locked_until, password_changed_at, must_change_password
`

type UpdateUserParams struct {
	Username            string     `json:"username"`
	Email               string     `json:"email"`
	PasswordHash        string     `json:"password_hash"`
	Role                string     `json:"role"`
	FailedLoginAttempts int64      `json:"failed_login_attempts"`
	LockedUntil         *time.Time `json:"locked_until"`
	MustChangePassword  bool       `json:"must_change_password"`
	PasswordChangedAt   *time.Time `json:"password_changed_at"`
	ID                  int64      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.MustChangePassword,
		arg.PasswordChangedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
	)
	return i, err
}
