// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vlans.sql

package db

import (
	"context"
	"time"
)

const listVLANs = `-- name: ListVLANs :many
SELECT id, vlan_tag, name, description, network_id, first_seen, last_seen FROM vlans
WHERE (? <= 0 OR network_id = ?)
ORDER BY vlan_tag
`

type ListVLANsParams struct {
	Column1   interface{} `json:"column_1"`
	NetworkID *int64      `json:"network_id"`
}

// All VLANs observed on a network. network_id <= 0 = all networks.
func (q *Queries) ListVLANs(ctx context.Context, arg ListVLANsParams) ([]Vlan, error) {
	rows, err := q.db.QueryContext(ctx, listVLANs, arg.Column1, arg.NetworkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vlan{}
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.ID,
			&i.VlanTag,
			&i.Name,
			&i.Description,
			&i.NetworkID,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVLAN = `-- name: UpsertVLAN :one

INSERT INTO vlans (vlan_tag, name, description, network_id, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(vlan_tag, network_id) DO UPDATE SET
    name        = CASE WHEN excluded.name != '' THEN excluded.name ELSE vlans.name END,
    description = CASE WHEN excluded.description != '' THEN excluded.description ELSE vlans.description END,
    last_seen   = excluded.last_seen
RETURNING id, vlan_tag, name, description, network_id, first_seen, last_seen
`

type UpsertVLANParams struct {
	VlanTag     int64      `json:"vlan_tag"`
	Name        *string    `json:"name"`
	Description *string    `json:"description"`
	NetworkID   *int64     `json:"network_id"`
	FirstSeen   *time.Time `json:"first_seen"`
	LastSeen    *time.Time `json:"last_seen"`
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Copyright (c) 2026 Mi-Bee Studio. All rights reserved.
//
// This file is part of MiBee Steward, distributed under the GNU Affero General
// Public License v3.0 or later. See LICENSE for the full text. A commercial
// license is available for use cases the AGPL does not accommodate; see
// LICENSE-COMMERCIAL.md.
// Insert a VLAN or refresh its last_seen. The UNIQUE(vlan_tag, network_id)
// constraint backs the conflict target. Returns the row so the caller can
// resolve the id when inserting a linked subnet.
func (q *Queries) UpsertVLAN(ctx context.Context, arg UpsertVLANParams) (Vlan, error) {
	row := q.db.QueryRowContext(ctx, upsertVLAN,
		arg.VlanTag,
		arg.Name,
		arg.Description,
		arg.NetworkID,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.VlanTag,
		&i.Name,
		&i.Description,
		&i.NetworkID,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}
